### ISSUE TITLE
Setting up integration now working

### ISSUE THREAD

**Issue by iz3man** [jeroenterheerdt/HAsmartirrigation#1]
Wanted to try your irrigation code, but I didn't come very far.

Going to integration -> Add -> searched for it, clicked it -> had to do another search, clicked again, and this is the result:

![Screenshot from 2020-05-17 20-27-28](https://user-images.githubusercontent.com/11553674/82156695-0fb3d880-987d-11ea-8e66-77ce925db5b1.png)

Is it supposed to look that way? If yes: What do you have to fill where?

**Comment by jeroenterheerdt** [comment]
Thanks for trying! It is obviously not supposed to be this way, it is expected to show labels. I will check. Thanks.

**Comment by jeroenterheerdt** [comment]
It turns out I had a bug - this commit should fix it. let me know if you need more help! otherwise, please close.

**Comment by iz3man** [comment]
Much better :)

![image](https://user-images.githubusercontent.com/11553674/82245401-2de40c00-9943-11ea-89d7-cdd840380bbf.png)

Will try now and let you know how it works. Thanks!

**Comment by iz3man** [comment]
Ok. Tried to enter the values.

First of all: EV values are only available for US. So bad, can't use it, and haven't found those values for where I live.

Second: You can't scroll down to the value after September (in my case). Depends on resolution of the monitor. This is missing a scroll bar.

**Comment by jeroenterheerdt** [comment]
Thanks, I have found EV values for more places than just the US, you don't have to use the sources I provided. Scrollbar is not something I control.

**Comment by jeroenterheerdt** [comment]
http://wcatlas.iwmi.org/ contains information for the whole world AFAIK.

**Comment by ciechompl** [comment]
hi
what am I ding wrong ? :)  ... "User input malformed"

![image](https://user-images.githubusercontent.com/27088154/82264941-2a15b100-9966-11ea-812b-7ab4421ee85a.png)

**Comment by ciechompl** [comment]
and one question reg number of sprinklers. 
In my setup I have 8 zones. Each zone contain from 2 to 4 sprinklers and 3 of those zones are drip lines not sprinklers. 
Should I count them all and put total number of sprinklers or just 8 as each zone can/should be represented by one sprinkler ? (to simplify everything :)

**Comment by jeroenterheerdt** [comment]
@ciechompl you have used a ',' instead of a '.' in the first entry (January ET). Make sure it is consistent with your regional settings.

The system currently does not irrigate or measure separate zones. The number of sprinklers and flow per sprinkler is just used to calculate total system throughput: throughput = number of sprinklers * flow.
So if you know the flow of the system or can calculate it you could set the number of sprinklers to one. Or, what I did, I have a mix of sprinklers with different flows so I calculated their average and used that as flow and used to correct number of sprinklers.

**Comment by jeroenterheerdt** [comment]
@iz3man - were you able to get it working? The scrollbar is a bug in the frontend which they are looking into fixing.

**Comment by jeroenterheerdt** [comment]
@ciechompl - were you able to make it work? if you need more help, please create a new issue so we can track it separately from this discussion.

**Comment by iz3man** [comment]
> @iz3man - were you able to get it working? The scrollbar is a bug in the frontend which they are looking into fixing.

Nope. Sure, the not reachable parts can be circumvented by doing some CTRL-.
But still it doesn't accept the values.

![image](https://user-images.githubusercontent.com/11553674/82360686-0c9a2300-9a0a-11ea-8e86-5be2a9b69b9c.png)

**Comment by jeroenterheerdt** [comment]
@iz3man you are using an older version, please update to at least 0.0.9 using HACS and try again after rebooting.

**Comment by iz3man** [comment]
> @iz3man you are using an older version, please update to at least 0.0.9 using HACS and try again after rebooting.

I realized myself, but new version was doing the same. Will try with newest version asap

**Comment by iz3man** [comment]
> > @iz3man you are using an older version, please update to at least 0.0.9 using HACS and try again after rebooting.
> 
> I realized myself, but new version was doing the same. Will try with newest version asap

Ok. Installation went fine now. I got three sensors. Now let's work on documentation and how to really use it :) Thanks

**Comment by jeroenterheerdt** [comment]
Yep, working on that right now.

**Comment by ciechompl** [comment]
> were you able to make it work?

sorry for not responding ... was offline today ... with the latest version success :) ... so testing now how it works :)

**Comment by ciechompl** [comment]
btw @jeroenterheerdt may I suggest you to open a dedicated topic on a HA forum ? just to have a place to discuss things rather than raising new issues on github :)

**Comment by jeroenterheerdt** [comment]
@iz3man , @ciechompl: documentation updated here: https://github.com/jeroenterheerdt/HAsmartirrigation.
I made a topic on HA forum as well: https://community.home-assistant.io/t/smart-irrigation-safe-water-by-precisely-watering-your-lawn-garden/
