### ISSUE TITLE
[Bug] Cannot add zone without irrigation details

### ISSUE THREAD

**Issue by DutchessNicole** [jeroenterheerdt/HAsmartirrigation#102]
**Describe the bug**
Cannot enable zone without irrigation system

**To Reproduce**
1. Create new irrigation zone (using a new instance of the smart irrigation integration)
2. Enter zone name, sensors etc.. until you get to step 7/7
3. Leave all values at default (0)
4. Submit zone
5. See error

**Result**
Instance fails to load with the following log statements:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smart_irrigation/__init__.py", line 117, in async_setup_entry
    precipitation_rate = (throughput * 60) / area
ZeroDivisionError: float division by zero
```
If I enter a nonzero number in the area field, the error instead refers to the next zero entry

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smart_irrigation/__init__.py", line 118, in async_setup_entry
    base_schedule_index = (peak_et / precipitation_rate * 60) * 60  # in seconds
ZeroDivisionError: float division by zero
```

**Expected behavior**
A new instance of the integration is added with all functionality

**Screenshots**
![Screenshot from 2022-07-05 14-11-49](https://user-images.githubusercontent.com/1487918/177324527-d8e1d352-48c7-4c44-b1e2-d5856ce2d9c8.png)
![Screenshot from 2022-07-05 14-11-26](https://user-images.githubusercontent.com/1487918/177324532-957ae995-0ed0-487a-9071-c68c81719871.png)

**Installed version**
Which version of the component are you running? 
0.0.77

**Additional context**
Given its description, I would expect the integration to simply make a calculation of the amount of water/time required to run a fictional irrigation system.

Since my irrigation system consists of me with a garden hose, I don't need an automation to hook into this to run devices. Instead I simply want to know when to water my plants.

If no irrigation system exists, it should still be possible to set up the integration and use the calculated values in other ways, like sending a notification only.

**Comment by jeroenterheerdt** [comment]
I did not cater for this scenario, will look at it.

**Comment by jeroenterheerdt** [comment]
not sure if this is still relevant for you, but I think you can do this using the 2.0 version which is now in beta. please confirm and close.

**Comment by gatonero** [comment]
This issue no longer exists and should get closed.
