### ISSUE TITLE
[REQ] Greenhouse option

### ISSUE THREAD

**Issue by scharc** [jeroenterheerdt/HAsmartirrigation#103]
Thanks for the great work of this! It really helps us to lower our water consumtion! 

I was wondering if there is a possibility to add a greenhouse function? The evaporation is still valid for greenhouses but there is no rain or snow coming in.

**Comment by ScratMan** [comment]
I would say it's already possible. Just use a thermal sensor in the greenhouse for temperature and create a virtual rain sensor which always returns 0.

**Comment by scharc** [comment]
@ScratMan Thanks for the hint. I will see how it performs if there is any rain (soon?)

**Comment by jeroenterheerdt** [comment]
yeah, this should be easily done using a virtual sensor or in the 2.0 version (now in beta) a mapping to the same virtual sensor.

**Comment by jeroenterheerdt** [comment]
> yeah, this should be easily done using a virtual sensor or in the 2.0 version (now in beta) a mapping to the same virtual sensor. Please confirm and close the issue.

You can actually in v2 just set static values for precipitation.
