### ISSUE TITLE
Evaporation values for the Netherlands

### ISSUE THREAD

**Issue by omenick** [jeroenterheerdt/HAsmartirrigation#104]
First of all: thanks for this Smart Irrigation custom component for Home Assistant!

I found reference evaporation values for 14 stations in the Netherlands. The file contains evaporation values from January 1981 till December 2010. You can use the data to calculate average values based on your preference, e.g. most recent average (2010), average over the last x years or average over the period 1981 - 2010. The data is provided by the KNMI:

[https://dataplatform.knmi.nl/nl/dataset/knmi14-referentieverdamping-3-2](https://dataplatform.knmi.nl/nl/dataset/knmi14-referentieverdamping-3-2)

[KNMI14____ref_evmk___19810101-20101231_v3.2.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/9144172/KNMI14____ref_evmk___19810101-20101231_v3.2.txt)

I have also attached the file in case it is taken down. 

The 14 weather stations in the data can be identified through their GPS coordinates. Use Google Maps or the attached list_dx.txt to find the one closest to your home.

[list_dx.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/9144173/list_dx.txt)

Additional tip: I have used the sensor.smart_irrigation_daily_adjusted_run_time to display the remaining time in the [Lovelace Timer Bar Card](https://github.com/rianadon/timer-bar-card). Looks super nice!

**Comment by arcidodo** [comment]
nice :-) i am new here.. i think the nearest knmi station from Drachten is Leeuwarden how do i get the evaporation values?

**Comment by omenick** [comment]
> nice :-) i am new here.. i think the nearest knmi station from Drachten is Leeuwarden how do i get the evaporation values?

In the data provided by the KNMI, look for the values in the column below 270 (= station Leeuwarden).

**Comment by jeroenterheerdt** [comment]
very very late reply, but thanks for finding this. Added to the Wiki.
