### ISSUE TITLE
Wiki entry for country specific evaporation (Germany) should be updated

### ISSUE THREAD

**Issue by Cyb3rPre4cher** [jeroenterheerdt/HAsmartirrigation#105]
**Describe the bug**
I did some research and found, that the measurement unit for the german evaporation table is not 1/10mm. As stated in this document: https://opendata.dwd.de/climate_environment/CDC/derived_germany/soil/monthly/historical/BESCHREIBUNG_derivgermany_soil_monthly_historical_de.pdf

It's mm. Perhaps you could edit the German part?
Correct me if I'm wrong.

**To Reproduce**
1. Go to https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Country-specific-Evapotranspiration-info
2. See the Section with the information for Germany

*edit*
**What just came to my mind. If we need the mm/day, shouldn't we divide the monthly evapotranspiration by the amount of days of the specific month? :)** I checked that by multiplying the specific real evaporation per day of my region (https://www.dwd.de/DE/leistungen/verdunstung/verdunstung.html) with the days of the month.. as a result I get roughly the values stated in the table: https://opendata.dwd.de/climate_environment/CDC/derived_germany/soil/multi_annual/mean_91-10/derived_germany_soil_multi_annual_mean_91-10_VGLS.txt

Perhaps it would be useful to add "mm/day" to the Input fields where you put the Monthly evapotranspiration rates.

**Comment by Cyb3rPre4cher** [comment]
I divided them by the number of days each month has.
I think they're the total amount of precipitation over the month. In January i divided the number by 31, February by 28, March by 31 and so on.
I double checked with actual values and the numbers seemed to mach with the daily precipitation that is stated here: https://www.dwd.de/DE/leistungen/verdunstung/verdunstung.html

**Comment by jeroenterheerdt** [comment]
version 2.0 no longer uses ET values, so you don't need them. Please install the beta.
