### ISSUE TITLE
[REQ] service to add manual irrigation to the calculation/bucket

### ISSUE THREAD

**Issue by Cyb3rPre4cher** [jeroenterheerdt/HAsmartirrigation#106]
I really love the irrigation plugin :) Awesome work!
I didn't see any option or possibility to add "manual irrigation" to the calculation of the sensors.
I tried around by filling the bucket by hand and so on but didn't get it to work.

Perhaps some day you could think about a service or sth. like that, that passes just an amount of water depending on how long i run my system e.g. in liters to the bucket. So that if i run my irrigation by hand at some point, that amount is calculated for the automatic irrigation process the next day :)

Kindest regards

**Comment by jeroenterheerdt** [comment]
This capability is provided in the 2.0 version which is now in beta (using the Static module).
