### ISSUE TITLE
[REQ] support for flow meters

### ISSUE THREAD

**Issue by Test-subj** [jeroenterheerdt/HAsmartirrigation#107]
**Is your feature request related to a problem? Please describe.**

I have a large tank for my reverse osmosis waste water and use it to water the garden. Since pressure depends on how full the tank is, I can't set a specific flow rate and use a flow meter to know how much is dispensed. 

**Describe the solution you'd like**
I would like support for a flow meter volume instead of a time setting

**Describe alternatives you've considered**
To have a steady flow rate, I'd have to use a pump instead of automated valves. 

**Additional context**

The output of the tank is controlled by an electric ball valve that will either let it flow or not.
Immediately after that valve is a 3-way electric ball valve that switches between zones. 
Both valves and liters/zone are already configured and working in HA. Currently the automation dispenses n liters per day based on input sliders for each zone. If that input could take the place of the baseline time setting then it could directly control how many liters are dispensed instead of converting it to time.

**Comment by jeroenterheerdt** [comment]
Interesting. I was busy on the 2.0 version which is now in beta. I think this is a very cool idea, but will take time to implement as it changes the foundation of the component (switch out duration for volume)... is it still relevant to you?

**Comment by Test-subj** [comment]
Oh shoot. I never saw that you replied. I would still use this.

**Comment by jeroenterheerdt** [comment]
Thanks, I will put it back on the list

**Comment by Test-subj** [comment]
Thanks a bunch!

**Comment by jeroenterheerdt** [comment]
so I have been thinking about this... since this component figures out how long to run the irrigation for you can do: `duration x (throughput/60)` to get the gallons / liters it is instructing you to irrigate for (duration is in seconds, throughput is in gpm/lpm). Isn't that what you control your system?

**Comment by Test-subj** [comment]
It does, but there's an initial rush as the pipes fill so it's really only
good for counting totals

**Comment by jeroenterheerdt** [comment]
Not sure I understand this. If you set the throughput to 1 then you know exactly how much liters to water by taking duration. Can you not instruct your flow meter to pass that amount?

**Comment by Test-subj** [comment]
Sorry, maybe my situation is too niche.. I have a ro wastewater/rain tank
and watering is done with an automatic ball valve. Water pressure on the
output depends on how full the tank is so there isn't a standard flow level.

Maybe I just need to set it up as a dummy system and take the time result
and feed that to the liters input for my watering automation.
