### ISSUE TITLE
Monthly ET values help

### ISSUE THREAD

**Issue by Axydas** [jeroenterheerdt/HAsmartirrigation#111]
Hi,

the only ET values i found for my country is one excel that has hourly ET values for the whole year. For example:
....
2019-01-01T12:00:00 | 0,13392
2019-01-01T13:00:00 | 0,16704
2019-01-01T14:00:00 | 0,16992
2019-01-01T15:00:00 | 0,18864
2019-01-01T16:00:00 | 0,1368
2019-01-01T17:00:00 | 0,07776
2019-01-01T18:00:00 | 0,01152
2019-01-01T19:00:00 | 0,00864
etc.....

What i did was to find the monthly average and insert the values in the add-on. The result for the Base Schedule Index was 0.9 sec and the Daily Adjusted Run Time was 372 sec. Something is wrong with these results.... 

Can somebody help me?

**Comment by EmanueleBenedettini** [comment]
Hi, I'm a bit late but that's what i found.

This method can be used worldwide.

1. got to [https://www.fao.org/land-water/databases-and-software/climwat-for-cropwat/en/](url) and dowload the available software.
2. install and open program
3. fill the coordinate section whit yours, than proceed and select the first result it gives you (nearest location available)
4. click on "export selected stations" and then "export .PEN and .CLI files"
5. download this software [https://www.fao.org/land-water/databases-and-software/eto-calculator/en/](url) and start it
6. "import climatic data from file" -> select CLIMWAT file -> select the directory where step 4 saved those files. you should see a file appear on the left, click it, then hit import. this is going to generate an error. click OK.
7. fill the missing file name whit something of your choice and the click import.
8. Click on "ETo calculation", in the "plot data" tab you should see something. if not, try changing something in "input data description"
9. once you are good, go to "export result" and click "Compose ETo report". save it
10. you can now open your report as a text file, the last column will contain your ET value

I may have missed something so I'm not sure if those are the correct values.
I summed it all up and it seem to be around the annual value i found for my area

**Comment by jeroenterheerdt** [comment]
in version 2.0 you don't  need the ET values any more. Please install it and give it a try.
