### ISSUE TITLE
[Bug] is_metric` property of the unit system is deprecated

### ISSUE THREAD

**Issue by omenick** [jeroenterheerdt/HAsmartirrigation#114]
Upon upgrading to HA 2022.11, i got the following warning message:

![image](https://user-images.githubusercontent.com/98217270/199947296-9cc6cc5b-552c-4a2d-ab63-d7adbc6c9c40.png)

**Comment by daxy01** [comment]
Hey @jeroenterheerdt 
Thanks for the quick first fix! So far the Metric changes you made seem to work!

I've tried this fix however it seems HA is choking on the version number in the manifest file. It doesn't seem to like characters, only numbers allowed. As soon as I remove the beta text in const.py and manifest.json the integration loads successful.

This was the error reported btw:
`2022-11-09 10:22:45.953 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'smart_irrigation' does not have a valid version key (0.0.77 beta) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by jsbowling42** [comment]
you can change the manifest.json file yourself until @jeroenterheerdt fixes his release. "0.0.77-beta" should work or "0.0.77b0" you will have to restart HA after.

**Comment by jeroenterheerdt** [comment]
thanks, just pushed a new release, please let me know if this resolves the issue.

**Comment by omenick** [comment]
It does, thanks for your support!

**Comment by posixx** [comment]
@jeroenterheerdt when do you make this a new release version? I'm still getting this error when restarting so as it has been confirmed to work i'm looking forward having this auto-resolved on my installation.

**Comment by jeroenterheerdt** [comment]
@posixx I did already, but apparently that did not work. Have pushed v0.0.78 now.
