### ISSUE TITLE
[Bug] Does Not have Valid key in Manifest file

### ISSUE THREAD

**Issue by jsbowling42** [jeroenterheerdt/HAsmartirrigation#117]
**Describe the bug**
the Beta v0.0.77 does not have a valid key in HS manifest file. i updated to try the fix for bug #114 
**To Reproduce**
1. upgrade from v0.0.77 to v0.0.77Beta
2. go to logs

Error: 

The custom integration 'smart_irrigation' does not have a valid version key (0.0.77 beta) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by jeroenterheerdt** [comment]
thanks - just pushed a new release
