### ISSUE TITLE
REQ: Use actual weather values instead of OWM

### ISSUE THREAD

**Issue by posixx** [jeroenterheerdt/HAsmartirrigation#12]
Jeroen,

I see you use the following info from OWM:

        rain = data["rain"]
        snow = data["snow"]
        t_day = d["temp"]["day"]
        t_min = d["temp"]["min"]
        t_max = d["temp"]["max"]
        t_dew = float(d["dew_point"])
        pressure = d["pressure"]
        RH_hr = d["humidity"]
        u_2 = d["wind_speed"]

For all of us having our own weatherstation we would like to make use of actual weatherdata instead of forecasted data as actual data will be much more precise, especially outside of the US.

So my request is during integration setup; ask weather to use OWM or hass sensors. When selecting OWM use the functionality as is now, when using hass sensors display 8 textboxes to insert sensor names (weatherstation doesn't know difference between rain and snow so 1 sensor for that):

daily rain 
current temperature
minimum temperature
maximum temperature
dew point
air pressure
humidity
average windspeed

I hope you can see the value here, also no need to setup OMW accounts and, when using multiple instances, no redundant api calls..

**Comment by posixx** [comment]
To see the differences here is a copy of OWM current weather and actual weatherdata from my davis weatherstation:

![image](https://user-images.githubusercontent.com/2280400/83010399-7de46200-a018-11ea-9aa7-68830164ee7d.png)

![image](https://user-images.githubusercontent.com/2280400/83010448-90f73200-a018-11ea-8d5e-9b5ea189f9f0.png)

**Comment by jeroenterheerdt** [comment]
Good idea, I will see what I can do. Cannot test it though since I don't have a weather station myself.

**Comment by jeroenterheerdt** [comment]
By the way, which weatherstation is this?

**Comment by posixx** [comment]
Davis Vantage Pro2. I use a WifiLogger card in the console which pushed my info to WOW and publishes all readings as json to my home assistant MQTT instance. Within home assistant i made a MQTT discovery plugin which adds all avalable sensors automatically

**Comment by jeroenterheerdt** [comment]
OK, got it. I think we will need to allow people to choose which value to get from OWM and which from a weatherstation. I am thinking of building my own station, but that will probably not be able to provide all the values right away.

**Comment by posixx** [comment]
Ah great idea. As long as it is possible to completely disable OWM api calls as we don't want the extra overhead and creation of api key. So maybe start with aking which sensors to use or OWM; when using sensors for al valuesl skip the OWM setip..

**Comment by jeroenterheerdt** [comment]
Yes, exactly that was what I was thinking.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ciechompl** [comment]
+1 :) I use Netatmo weather station, so also knows precisely what is the temperature, wind, rain etc in MY location ... so would like to finally make a use of it in a way providing some real value ... not just nice information shown on the tablet in the kitchen :)

**Comment by jeroenterheerdt** [comment]
Sooo.. Since all these weather values eventually roll up into `hourly_adjusted_run_time` what is the correct behavior for basing `daily_adjusted_run_time` on it? Take the minimum of hourly art? Maximum? Average? Last value? Currently I take the last as I assume the most recent prediction for today is best since most of the day has progressed. With a weather station we are not using predictions any longer but actuals..so average or min or max would make more sense.. Thoughts?

**Comment by posixx** [comment]
I would opt for average: take actual calculations from every hour, and devide through the number of hours. This will take into account sudden weather changes based on the actual readings.

**Comment by jeroenterheerdt** [comment]
daily art is now the average of the hourly values collected, regardless if you call it yourself or if it's auto-calculated.

**Comment by jeroenterheerdt** [comment]
first version of this is ready for testing! @posixx

**Comment by posixx** [comment]
Great. Before i do: can you give us the unit_of_measurements the integration expects? Or set them on the setup step so we now what to expect. For instance, my windspeed sensor uses km/h but i think the integrations expects m/s..

**Comment by jeroenterheerdt** [comment]
Right, there's that and there is the imperial / metric system to deal with. I'll specify it somehow and document it as well. Stay tuned.

**Comment by jeroenterheerdt** [comment]
@posixx @ciechompl : v0.0.25 is available which should allow you to test. Units are indicated and documented in the readme as well. Looking forward to your feedback, since I have not been able to test this as I don't have a weather station. I have been using random value sensors...

**Comment by posixx** [comment]
looks good so far! added integration for both my zones, no errors / warnings in the logs, and hourly sensors display results.. keep you posted!

**Comment by glowery** [comment]
I've used the updated component as well with an Ambient Weather station integration and so far sensors are displaying and looking good.  Thanks for your work on this! Great feature addition!

**Comment by jeroenterheerdt** [comment]
thanks @posixx and @glowery for letting me know. Please keep an eye on the values, especially the interaction with daily adjusted run time and the bucket. I suspect something is not right, but I cannot put my finger on it yet. More data helps.

**Comment by glowery** [comment]
Sure thing, will do.  Thanks for heads up!

**Comment by posixx** [comment]
First ompressions; run time looks lower then yesterday, when today was hotter then yesterday:

![image](https://user-images.githubusercontent.com/2280400/83449775-7c6dcc00-a454-11ea-8378-4407e923b3e2.png)

Let's see in about an hour what daily sensor looks like..

**Comment by jeroenterheerdt** [comment]
let's keep in mind there was a bug where the code passed in hPa where the calculations required kPa, so that was fixed. These calculations should be better. The thing I worry about is how hourly is brought into daily :)

**Comment by posixx** [comment]
i'm using latest build so my pressure sensor in mbar should be correct?

**Comment by jeroenterheerdt** [comment]
@posixx yes mbar=hPa. The code divided it by ten to get kPa when it's needed,because both OWM and most sensors provide hpa / mbar.

**Comment by jeroenterheerdt** [comment]
@posixx  yes mbar=hPa. The code divided it by ten to get kPa when it's needed,because both OWM and most sensors provide hpa / mbar.

**Comment by posixx** [comment]
Ok 23h past, here are my readings:

![image](https://user-images.githubusercontent.com/2280400/83454003-c312f480-a45b-11ea-821e-bfa5d3d12b82.png)

Compared to yesterday, when using old component with OWM sensors:

![image](https://user-images.githubusercontent.com/2280400/83454108-f35a9300-a45b-11ea-833b-e9109e43ad84.png)

Yesterday: 1052 seconds
Today: 1157 seconds.

As i told before today the temperatures were higher this looks promising:-)

**Comment by posixx** [comment]
And the one from my backyard:

![image](https://user-images.githubusercontent.com/2280400/83454248-36b50180-a45c-11ea-9ca7-c1d98fc14524.png)

**Comment by posixx** [comment]
THis is found in the core log of hassio:

2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating for last time today, calculating adjusted run time for next irrigation time!
2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating bucket: 0.0 with netto_precipitation: -5.817398976711855
2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Bucket for today is: -5.817398976711855 mm
2020-06-01 23:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 404, in _async_update_last_of_day
    return data
UnboundLocalError: local variable 'data' referenced before assignment
2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating for last time today, calculating adjusted run time for next irrigation time!
2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating bucket: 0.0 with netto_precipitation: -5.817412771934118
2020-06-01 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Bucket for today is: -5.817412771934118 mm
2020-06-01 23:00:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 404, in _async_update_last_of_day
    return data
UnboundLocalError: local variable 'data' referenced before assignment

So it's not enirely without problems..

**Comment by jeroenterheerdt** [comment]
ok - this is not good. Bucket looks like it is behaving. Can you confirm you are only using sensors at this point, no OWM?

**Comment by posixx** [comment]
Yes, never inserted the OWM API key during setup. Alle sensors are from my weatherstation

**Comment by jeroenterheerdt** [comment]
found the bug and fixed it.

**Comment by posixx** [comment]
great will update in the morning and let you know in about 24h

**Comment by jeroenterheerdt** [comment]
a new version is here: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.28, there was a bug where I added lead_time twice, both to hourly and daily calculations. oops.

**Comment by posixx** [comment]
ok installed. Does a HA restart affect the calculation of the daily run time? As the hourly sensor is back to zero when restarting HA..

**Comment by jeroenterheerdt** [comment]
daily run time and bucket should survive a HA reboot. Hourly is set to 0.

**Comment by posixx** [comment]
ok. daily sensors are 0 most of the time so didn't notice that. Will keep an eye on it when these have values and i need to restart.

**Comment by posixx** [comment]
On the core log i see:

2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 2.0191281227459372 and adjusted_run_time: 1385 for type: Hourly Adjusted Run Time. Bucket value was: -6.9659920234734845, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 2.0191281227459372 and adjusted_run_time: 1385 for type: Hourly Adjusted Run Time. Bucket value was: -6.9659920234734845, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 0 and adjusted_run_time: 0 for type: Daily Adjusted Run Time. Bucket value was: 0.0, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 0 and adjusted_run_time: 0 for type: Daily Adjusted Run Time. Bucket value was: 0.0, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation] Updating Smart Irrigation Data
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 2.0191281227459372 and adjusted_run_time: 4628 for type: Hourly Adjusted Run Time. Bucket value was: -6.9659920234734845, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] rain: 0.0, snow: 0.0
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 2.0191281227459372 and adjusted_run_time: 4628 for type: Hourly Adjusted Run Time. Bucket value was: -6.9659920234734845, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 0 and adjusted_run_time: 0 for type: Daily Adjusted Run Time. Bucket value was: 0.0, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1
2020-06-02 17:44:45 INFO (MainThread) [custom_components.smart_irrigation.sensor] Calculated water_budget = 0 and adjusted_run_time: 0 for type: Daily Adjusted Run Time. Bucket value was: 0.0, and force mode is: False, force mode duration is: 0, lead_time is: 0, maximum_duration: -1

It looks like the calculations of daily adjusted runtime are ran every routine?

**Comment by jeroenterheerdt** [comment]
yeah, daily should not be called unless it is time for it or if you call the service.

**Comment by posixx** [comment]
Ok that looks like a minor issue then as these are called every 5 minutes, when the hourly sensor are calculated.

**Comment by jeroenterheerdt** [comment]
yeah, I see that. hourly was not even supposed to be updated every 5 minutes, but that is a Development configuration that made it into the release. Figuring out now why daily is updating this frequently as well.

**Comment by ciechompl** [comment]
one question :) ... let's say yesterday at 23:00 daily sensor got value 19 min, but today at 3:00 irrigation hasn't happened as hourly got value 0 in a meantime (we had a rain between 23:00 and 3:00 :)) => reset_bucked not called ... so what will be next daily value today at 23:00 ? average from last 24 h ignoring previous daily ? or average from 48 h as reset bucket haven't been called ?

**Comment by jeroenterheerdt** [comment]
@ciechompl daily is an average of hourly values. Right now daily is updated way to often. That is a bug. It is supposed to be updated once per day due to auto refresh or calling the service. Then daily takes the accumulated hourly values since the last call, and takes the average to update itself. Afterwards the accumulated hourly values are emptied. This happens regardless of irrigation automation triggering or not since that should be based based on the daily value itself, not on hourly. So unless you use hourly values (which you should not) to make the decision to irrigation this should not happen once the bug is fixed.

**Comment by ciechompl** [comment]
ok understood ... I use hourly only as a condition for automation: daily>0 AND hourly>0 => start irrigation. as per your suggestion to eliminate over irrigation in case if next day/hours will be rainy :)

**Comment by jeroenterheerdt** [comment]
turns out I was wrong - updating daily is fine every hour. The bucket is the one that needs to be updated just daily and that is happening correctly (once a day for auto refresh or when called manually). Fixed a bug with the updates happening every five minutes though (that is what I was using during development...). New release is 0.0.29

@ciechompl  if hourly dropped below zero just at the moment you run your automation it will not run while daily indicates that it needs to run. regardless, as long as you don't call `reset_bucket` the values will still persist and your daily value will keep increasing, which is what you want.

**Comment by posixx** [comment]
Ok past 23h now. COre log:

2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating for last time today, calculating adjusted run time for next irrigation time!
2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating bucket: 0.0 with netto_precipitation: -3.922710742963342, which should be average of: [0.0, 0.0, -5.787587216971071, -5.787587216971071, -5.2869868742166215, -5.2869868742166215, -4.616268880665675, -4.616268880665675]
2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Bucket for today is: -3.922710742963342 mm
2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating for last time today, calculating adjusted run time for next irrigation time!
2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Updating bucket: 0.0 with netto_precipitation: -3.922710742963342, which should be average of: [0.0, 0.0, -5.787587216971071, -5.787587216971071, -5.2869868742166215, -5.2869868742166215, -4.616268880665675, -4.616268880665675]
2020-06-02 23:00:00 INFO (MainThread) [custom_components.smart_irrigation] Bucket for today is: -3.922710742963342 mm

Installed latest version ar about 19:30 as you can see here:

![image](https://user-images.githubusercontent.com/2280400/83569822-63811b80-a525-11ea-928e-3b1d410acb89.png)

So hourly sensors seem forget past hours after restart. Don't know if this can be persisted to prevent lower runtimes as a result of restarting HA?

**Comment by posixx** [comment]
Also my Davis sensors are null / empty right after restart so it would be nice to have the integration starting hourly calculations after 5 or 10 minutes

**Comment by jeroenterheerdt** [comment]
@posixx restoring hourly is not easy. But I should be able to make the hourly update quicker after a reboot. I will try to get a option setting for it and default it to 10 minutes.

**Comment by posixx** [comment]
Great, that will help a lot

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.30 implements this initial delay setting. Also, @ciechompl I have added a % increase setting so you do not have to do that on your own any more.

**Comment by posixx** [comment]
Delay works, after 300 seconds the daily sensor was updated. A small cosmetic bug:

![image](https://user-images.githubusercontent.com/2280400/83606808-76720b00-a57a-11ea-92d2-86d8f2e31236.png)

initial_update_delay displays milliseconds instead of seconds.

**Comment by ciechompl** [comment]
> Also, @ciechompl I have added a % increase setting so you do not have to do that on your own any more.

cool :) thank you :) just only to be 100% sure :) .. I looked into the code:
```
 CONF_INCREASE_PERCENT * 100, DEFAULT_INCREASE_PERCENT
```
are you sure you should multiply by 100 not divide by 100 ?  :) 
I might be wrong byt by my simple thinking :) when I put e.g. 50 in the config (my goal would be to get result only 50% of the calculated time) it will be 5000 as a factor for further adjustments. In general, my idea was to allow to tune up and tune down in meaning that users can decide to irrigate only for 50% of calculated time. I might be wrong :) but looking at this part I think you allow only to tune up (1.0 + ) in meaning that whatever we put into config it will be added to the time .. .e,g, 50% -> run time*1.5: 
```
adjusted_run_time = adjusted_run_time * float(1.0 +
   self.coordinator.increase_percent
```    
so if you would put into the config as a default 100% (not 0) and later you would just multiply adjusted run time by this % , users would be able to do whatever they want :) -> from 0% to infinity % :) adjust up and down ... full flexibility :)

**Comment by jeroenterheerdt** [comment]
@ciechompl just enter a percentage. I store 50 as .50. The multiplication is just for display purposes. Also, you can enter a negative value since what the logic is that you enter a value with which you want to increase or decrease the ART value, so mathematically what you are suggesting and what I do are the same right?

**Comment by ciechompl** [comment]
that's correct :) I prefer just % factor (50%, 70%, 100% or e.g. 150%) and that's it ... just take this factor and multiply adjusted run time by it :) that's much easier to understand how it works without need to figure out whether should I put minus or not. Baseline in config should be 100% -> no touch = no change in calcs.   

re code:
custom_components/smart_irrigation/config_flow.py line 364
custom_components/smart_irrigation/sensor.py line 675 

next time will make a reference more precisely :)

**Comment by jeroenterheerdt** [comment]
ok, will make the change as you suggested. will also take a look at the formatting issue @posixx reported above.
Regarding the code:
- https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/custom_components/smart_irrigation/config_flow.py#L374 is just for display purposes. The value is stored as .50, so to show it properly to the user I multiple it by 100 here.
- the value is actually stored here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/custom_components/smart_irrigation/config_flow.py#L464

**Comment by jeroenterheerdt** [comment]
@posixx @ciechompl new version here: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.31. I am going to close this to keep my sanity. please feel free to open new issues for further discussion or problems, but please keep each thread limited to just one subject. If you have multiple ideas, problems, open multiple issues.

**Comment by jeroenterheerdt** [comment]
hey @posixx just wanted to check - you are using your own sensors right? Are you using the sensor that provides the total precipitation for the day? The one that accumulates during the day? Let's say it is dry in the morning, then the sensor is 0, if it starts raining this sensor will increase, but never decrease.
If so, are your results ok? The reason for asking is that I am looking at the code at it calculates an average, so if it is dry in the morning then the rain becomes heavier during the day, you will actually get a lower value than the real precipitation... just thinking about how people use this solution.

**Comment by posixx** [comment]
Hello Jeroen,

Yes i'm using a "daily rain" sensor containing the total mm of rain which has fallen during the day. It looks like the values are ok:

![image](https://user-images.githubusercontent.com/2280400/84774483-2feec880-afde-11ea-8751-b34cfa9a19d4.png)

This is from a couple of days ago, i will look into this when it starts to rain again..

**Comment by jeroenterheerdt** [comment]
@posixx thanks - so this "daily rain" sensor, it is additive right? I mean, it starts at 0 when the day starts and if it rains during the day the value increases, but never decreases until the reset at 00:00 right?
Because that means that taking an average of the values reported is then not correct as I explained above, we should be taking a max of the values instead of an average. The average is fine if we deal with forecasts though (from OWM for example)

**Comment by posixx** [comment]
Yes it's additive, only increases and is reset at 00:00. So indeed you should use the value at 23h instead of the average.

**Comment by jeroenterheerdt** [comment]
right.. and you did not complain about this at all? :)

**Comment by posixx** [comment]
Hehe not a lot of rain has fallen here from the start of using your plugin, so i didn't have the opportunity to monitor. ALso i hope you are doing a good job:-)

**Comment by jeroenterheerdt** [comment]
@posixx right, well, you're wrong about me doing a good job, this is just a hobby project ;)
