### ISSUE TITLE
[Bug] OpenWeather API calls return an error 401

### ISSUE THREAD

**Issue by Cook23** [jeroenterheerdt/HAsmartirrigation#120]
Hello,

OpenWeather API calls return an error 401 with good API key. 

in OWMClient.py need to change:

https://api.openweathermap.org/data/2.5/onecall?units=metric&lat={}&lon={}&appid={} 

by:

https://api.openweathermap.org/data/3.0/onecall?units=metric&lat={}&lon={}&appid={}

And subscribe for onecall 3.0 plan (free but need bank card)

**Comment by Sebastiaanhubar** [comment]
I keep getting the error: Cannot talk to OWM API, check API key.
The account and API key at OWM is already more then a week old. Also tried the aboved montioned fix but it didn't work.
Some suggestions?
Where can I track the API key to double check or it is logged correctly?

Thanks for the help!

**Comment by SebastianSiegl** [comment]
The PR fixed the issue with the 401 error but the "TypeError: 'NoneType' object is not subscriptable" is still existing

**Comment by Miroslavgapa** [comment]
> I keep getting the error: Cannot talk to OWM API, check API key. The account and API key at OWM is already more then a week old. Also tried the aboved montioned fix but it didn't work. Some suggestions? Where can I track the API key to double check or it is logged correctly?
> 
> Thanks for the help!
> 
> Solved it by using this solution: #119

HI, please how you fix the issue? I change the file OWMclient.py with insertion of api 3 call, but still getting error 

Cannot talk to OWM API, check API key.

Please help. API key is functional i use it for openweathermap integration so is working since Jan 2023 correctly.

**Comment by Sebastiaanhubar** [comment]
> > I keep getting the error: Cannot talk to OWM API, check API key. The account and API key at OWM is already more then a week old. Also tried the aboved montioned fix but it didn't work. Some suggestions? Where can I track the API key to double check or it is logged correctly?
> > Thanks for the help!
> > Solved it by using this solution: #119
> 
> HI, please how you fix the issue? I change the file OWMclient.py with insertion of api 3 call, but still getting error
> 
> Cannot talk to OWM API, check API key.
> 
> Please help. API key is functional i use it for openweathermap integration so is working since Jan 2023 correctly.

Did you also do this last step? And subscribe for onecall 3.0 plan (free but need bank card)

**Comment by jeroenterheerdt** [comment]
please use latest version, should fix this.
