### ISSUE TITLE
[Bug] Precipitation calculation for daily art.

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#124]
Hello,
While analyzing code I noticed that for precipitation you are using daily data from OWM every hour and then calculate their average to update daily adjusted run time. Wouldn't be better to use hourly data and sum them?

**Comment by jeroenterheerdt** [comment]
version 2.0 is now in beta, please install it and confirm this issue is resolved there.

**Comment by omenek159** [comment]
Now I see that updates take place at period configured on General tab, which is good solution and resolves issue.
