### ISSUE TITLE
[Bug] Warning for self.async_update_ha_state(), without enabling force_update

### ISSUE THREAD

**Issue by jreed509** [jeroenterheerdt/HAsmartirrigation#126]
**Describe the bug**
I recently noticed the following warning in my logs after updating to HA 2023.5 (its possible this was present in an earlier version, but I just noticed it now). 

```
Entity sensor.smart_irrigation_zone_1_hourly_adjusted_run_time (<class 'custom_components.smart_irrigation.sensor.SmartIrrigationSensor'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
```

Assuming this is caused by a HA backend change, but I didn't see anything obvious when skimming the developer blog posts or release notes. 

**Installed version**
Smart Irrigation v0.0.78

**Comment by jeroenterheerdt** [comment]
fixed in [#v0.0.79](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v.0.0.79)
