### ISSUE TITLE
I seem to miss it but where do we update our ET values after initial boot?

### ISSUE THREAD

**Issue by johnneerdael** [jeroenterheerdt/HAsmartirrigation#132]
reference_evapotranspiration_1 ?

**Comment by ScratMan** [comment]
Hello, if you need to update the setup, you need use a new integration, there is no way to update it except digging in HA low level databases files (not recommended at all, as you may break everything).

**Comment by JeeDeWee** [comment]
I have a related question: for what purpose are these values used? As I understand the code, the ETO is calculated from weather parameters only.

**Comment by jeroenterheerdt** [comment]
ETO is calculated from weather and then the water budget is calculated using the reference ET values. Please read the readme and the wiki, the formulas are right there.
Unfortunately you have to manually edit files in '.storage' folder to change these values.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
