### ISSUE TITLE
[Bug]  Hi, I updated my hass (in raspi4) to 2023.6.1 and the integration doesn't works with new hass. Please fix it. Thanks.

### ISSUE THREAD

**Issue by adiraf** [jeroenterheerdt/HAsmartirrigation#134]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots of the entities and their attributes. 

**Installed version**
Which version of the component are you running? 

**Additional context**

**Comment by ScratMan** [comment]
Please have a look AT issue #130 a workaround is avail able.

**Comment by ametodi** [comment]
Hi Jeroen,
Same issue for me.
Here's the log:

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/smart_irrigation/sensor.py:124
Integration: Smart Irrigation (documentation, issues)
First occurred: June 9, 2023 at 15:47:21 (8 occurrences)
Last logged: 09:41:37

Unexpected exception importing platform custom_components.smart_irrigation.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/smart_irrigation/sensor.py", line 102, in <module>
    class SmartIrrigationSensor(SmartIrrigationEntity):
  File "/config/custom_components/smart_irrigation/sensor.py", line 124, in SmartIrrigationSensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by adiraf** [comment]
Just replace in custom_components/smart_irrigation/sensor.py:124 line
    @asyncio.coroutine 
with
    #@asyncio.coroutine


> Hi Jeroen, Same issue for me. Here's the log:
> 
> This error originated from a custom integration.
> 
> Logger: homeassistant.loader Source: custom_components/smart_irrigation/sensor.py:124 Integration: Smart Irrigation (documentation, issues) First occurred: June 9, 2023 at 15:47:21 (8 occurrences) Last logged: 09:41:37
> 
> Unexpected exception importing platform custom_components.smart_irrigation.sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform cache[full_name] = self._import_platform(platform_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1206, in _gcd_import File "", line 1178, in _find_and_load File "", line 1149, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/config/custom_components/smart_irrigation/sensor.py", line 102, in class SmartIrrigationSensor(SmartIrrigationEntity): File "/config/custom_components/smart_irrigation/sensor.py", line 124, in SmartIrrigationSensor @asyncio.coroutine ^^^^^^^^^^^^^^^^^ AttributeError: module 'asyncio' has no attribute 'coroutine'

Hi,

Just replace in custom_components/smart_irrigation/sensor.py:124 line
    @asyncio.coroutine 
with
    #@asyncio.coroutine
