### ISSUE TITLE
Cannot Find Smart Irrigation

### ISSUE THREAD

**Issue by fudu** [jeroenterheerdt/HAsmartirrigation#14]
trying to add it from configuration - > add integratrion 

![Cattura](https://user-images.githubusercontent.com/6508171/83033502-7bddcb80-a037-11ea-9e43-5f642d19a1c5.JPG)
![Cattura2](https://user-images.githubusercontent.com/6508171/83033521-80a27f80-a037-11ea-8367-b55ed53a6d57.JPG)

**Comment by jeroenterheerdt** [comment]
that is weird, I just tried and can see it just fine.

**Comment by fudu** [comment]
Sorry, I think I didn't restart HA.....
After a restart I can see it
