### ISSUE TITLE
Adjustment of number of sprinklers, flow rate and area

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#141]
**Is your feature request related to a problem? Please describe.**
Since the irrigation system changes from time to time, a new instance must be created each time. This is time-consuming and error-prone.

**Describe the solution you'd like**
I would like to adjust the number of sprinklers, flow rate and area under the configure options.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/a7eb6dc9-a709-440c-8d39-d3aa14f00a92)

**Comment by jeroenterheerdt** [comment]
version 2.0 is now in beta - please install it and try!

**Comment by gatonero** [comment]
I'm on "master". Version downloaded shows "9035648" Option shows 

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/510eaeb7-0dc0-4fea-a361-ef1478739454)

**Comment by jeroenterheerdt** [comment]
please clear your browser cache and try again.

**Comment by gatonero** [comment]
I close this issue. I'm now on v2023.8.0-beta11 and will respond in the other issue   #140
