### ISSUE TITLE
[Bug] Auto-update happens twice a day 

### ISSUE THREAD

**Issue by kfjellerup** [jeroenterheerdt/HAsmartirrigation#142]
**Describe the bug**
I have configured my integration to run the auto-refresh at 19:00, and that happens as expected. However, at 23:00 the daily adjusted time is changed again. 

**Expected behavior**
Auto-refresh seems to happen twice a day

**Screenshots**
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/36701214/18573f33-6231-41a2-8487-c55c906535ac)
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/36701214/04cd2bca-13f4-45be-a8a8-9840628fc148)
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/36701214/1a0216da-b823-4a1f-8ca6-fe93166d29b2)

**Installed version**
0.0.79

**Additional context**
No watering performed these days

**Comment by kfjellerup** [comment]
I've been monitoring the performance, at it hasn't re-occured again. Maybe it was just because it was the first day after i set up the integration?

**Comment by jeroenterheerdt** [comment]
please install the beta of the 2.0 version and see if this still happens. It shouldn't, but please try.
