### ISSUE TITLE
No possibility to create an account at  http://wcatlas.iwmi.org/

### ISSUE THREAD

**Issue by dennidoubles** [jeroenterheerdt/HAsmartirrigation#143]
Hi Jeroen,
Unfortunately I am not able to create an account on the website you're mentioning (<http://wcatlas.iwmi.org/>).
There is also no country specific evapotranspiration information available for the Netherlands at the wiki you're mentioning 
(<https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Country-specific-Evapotranspiration-info>)

Is there any way to get local evapotranspiration information available, preferably based on LONG/LAT?
Since you're Dutch, I was hoping for a solution-to-go :-)

I don't see any other possibility to get this information, which would mean I can't use your great work?
As an alternative, I could search for a  evapotranspiration-sensor for my WS-5500, if this exists?
Then I could integrate that via Ecowitt in Home Assistant, like I am doing already with my weather station.

Thanks for your input!

**Comment by jeroenterheerdt** [comment]
please see: https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Country-specific-Evapotranspiration-info#the-netherlands

**Comment by dennidoubles** [comment]
Huh. I must have missed this one specific for The Netherlands...Thanks, I'll have a look!

**Comment by dennidoubles** [comment]
If this is not the right place to ask, just let me know where I can...but I have difficulties reading the .txt file

I am want to use my own weatherstation (WS-5500) so I only need evapotranspiration data, right?

What do I need to do next, to finish the basic integration set up?

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/71798417/3aeaa509-989c-4829-b6d7-1ae6be88ebec)

**Comment by jeroenterheerdt** [comment]
Correct, supply your own sensors and enter the EV values.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeroenterheerdt** [comment]
version 2.0 (now in beta) does no longer need these reference values, so this issue will go away :)
