### ISSUE TITLE
[Bug] Gallon per minute flow values round if below 0.01

### ISSUE THREAD

**Issue by nhadler** [jeroenterheerdt/HAsmartirrigation#146]
**Describe the bug**
I wanted to use HAsmartirrigation to control water schedule for my vegetable garden, that uses 0.5 gallon per hour drippers. I entered the correct flow setting in the set up configuration, but when I check Base Schedule Index, it shows the value has been rounded up to 0.01 (~ 0.6 GPH). 

![Screenshot 2023-07-21 at 3 02 50 PM](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/3527739/d392791b-d4e3-4876-beb8-c848d21c0b9a)

**Comment by jeroenterheerdt** [comment]
hey, this is indeed a bug. I am working on version 2.0 of this component and I'd recommend waiting until that is ready, of in the mean-time I of course accept a PR to fix this.

**Comment by jeroenterheerdt** [comment]
please install the beta of the 2.0 version and see if this still happens. It shouldn't, but please confirm.
