### ISSUE TITLE
[REQ] polish value

### ISSUE THREAD

**Issue by LukaszP2** [jeroenterheerdt/HAsmartirrigation#147]
Here it is info for poland https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://journals.umcs.pl/b/article/download/14307/10395&ved=2ahUKEwjiqNDE36WAAxVJBhAIHZ0hCbYQFnoECBAQAQ&usg=AOvVaw1StPjzOK_JQfrXA1aioG9E

It should be device by 30 because it's sum for month.

**Comment by jeroenterheerdt** [comment]
thank you!
