### ISSUE TITLE
Solar Rad Unit Conversion[Bug] 

### ISSUE THREAD

**Issue by jsbowling42** [jeroenterheerdt/HAsmartirrigation#149]
maybe im looking at this wrong, but if we are supplying solar rad in W/sqrFt and your trying to convert it to W/m2. wouldn’t we multiplied by the “M2_TO_SQ_FT_FACTOR”?

Ex: 40 W/sqrFt * 10.7639 = 430.556416 W/m2

![code question](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/35424582/c802ee6a-d969-48e1-b163-41850f1b1cef)

**Comment by jeroenterheerdt** [comment]
fixed in [v0.0.18](https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.81)
