### ISSUE TITLE
[Bug] V2.0 Beta5 Not possible to configure without OWM API Key

### ISSUE THREAD

**Issue by jreed509** [jeroenterheerdt/HAsmartirrigation#152]
**Describe the bug**
I have a weather station that can provide all weather data for HAsmartirrigation so OWM is not required for my setup. The integration shows as failed to start if "Use Open Weather Map for weather data" is unchecked.

**To Reproduce**
1. Add the Smart Irrigation Integration
2. Uncheck "Use Open Weather Map for weather data"
4. Click Submit. The integration is created, but it shows as "Failed to Setup" 
6. Try to configure the Smart Irrigation integration and a window pops up to enter the OWM api key.

**Expected behavior**
Ability to create smart irrigation integration without OWM api keys required.

**Screenshots**
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/29850802/1a870992-16cd-4a0a-9f4f-17a28d4d552d)

**Installed version**
v2023.8.0-beta5

**Error log during integration creation**
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smart_irrigation/__init__.py:64
Integration: Smart Irrigation (documentation, issues)
First occurred: 11:38:43 AM (1 occurrences)
Last logged: 11:38:43 AM

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 64, in async_setup_entry
    hass.data[const.DOMAIN][const.CONF_OWM_API_KEY] = entry.data.get(const.CONF_OWM_API_KEY).strip()
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by jreed509** [comment]
Looks to be working in beta6. Thanks!

**Comment by JeeCee1** [comment]
Hi, I'd like to re-open this, since even though I disabled the checkbox "(Partially) use OWM sensors" I was required to enter the OWM API key.

**Comment by jeroenterheerdt** [comment]
Huh? I am not seeing that on my side. Can you please do a clean install and try again? Remove, reboot, install? Please use latest beta when doing this.

**Comment by JeeCee1** [comment]
Sorry, indeed with version 11 it does not occur anymore.

**Comment by jeroenterheerdt** [comment]
No worries, thanks for confirming. Closing this now, please open another issue if you find anything else.
