### ISSUE TITLE
 [Bug] v2023.8.0-beta9 Not preserving fractional gal/minute Zone values

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#154]
**Describe the bug**
If I set a gal/minute value using a decimal value it reverts to an integer after navigating away from the Zones tab.

**To Reproduce**
1) Create a new Zone
2) Set the square footage and gal/minute for the zone, using a fraction for the flow (i.e. 2.7)
3) Update the Zone
4) Navigate to another tab, such as General or Mappings
5) Navigate back to the Zones Tab

**Expected behavior**
After navigating back to the Zones tab the gal/minute should remain at the entered, fractional value (2.7).  Instead it changes the gal/minute to 2.

**Screenshots**
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/275530d0-7176-4658-b632-d799913ebd1f)
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/abcd1026-fbca-4a89-bc96-98f4ff27f567)

**Installed version**
v2023.8.0-beta9

**Additional context**
The behavior isn't consistent,  Sometimes it does preserve a decimal value for the gal/minute, other times it changes to an integer.

**Comment by jeroenterheerdt** [comment]
thanks for reporting, let me take a look!

**Comment by dlindnegm** [comment]
v2023.8.0-beta10 seems to have resolved this issue!  It's now saving fractions for the gal/min values.

**Comment by dlindnegm** [comment]
I've downloaded and installed v2023.8.0-beta11 several times now, with restarts and confirming that the folder in custom_components is removed.  Each time the displayed version in the HA side panel shows v2023.8.0-beta10.  Did a version number fail to get updated?  With v2023.8.0-beta10 it's still converting the decimals to integers.

**Comment by dlindnegm** [comment]
I noticed that this only seems to occur with the 2 default Zones.  I can use decimals in any new zones that I create and they are preserved when navigating to another tab, but those 2 defaults (renamed) revert to an integer.  I deleted those 2 and created 2 new ones and those work as expected.

**Comment by dlindnegm** [comment]
Was finally able to get v2023.8.0-beta11 installed and the issue with the 2 default zones converting decimals to integers is resolved.

**Comment by jeroenterheerdt** [comment]
Thank you for confirming!
