### ISSUE TITLE
[Bug] v2023.8.0-beta9 Unable to change Automatic weather data update

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#155]
**Describe the bug**
I was trying to change the Automatic weather data update from 24 days to 24 hours and it would not save the setting.  After I disabled the setting I'm now unable to re-enable it.

**To Reproduce**
1. Change Automatically update weather data from Yes to No
2. Attempt to change Automatically update weather data from No to Yes

**Expected behavior**
The Auto weather update should allow changing the value from days to hours and also to re-enable if it was disabled.

**Screenshots**

**Installed version**

v2023.8.0-beta9

**Additional context**
When I click on the "Yes" option to re-enable the Auto Weather Update the form flickers as it tries to show the options, but it never lets me select Yes and thus the option are not available.  I am using OWM 2.5 with a valid API key.

**Comment by dlindnegm** [comment]
Still unable to re-enable the Automatic weather data update setting once it's been disabled using v2023.8.0-beta10

**Comment by jeroenterheerdt** [comment]
should be fixed in beta11

**Comment by dlindnegm** [comment]
When I download and install v2023.8.0-beta11 it shows in the GUI as v2023.8.0-beta10,  But this issue is fix now.

**Comment by jeroenterheerdt** [comment]
> When I download and install v2023.8.0-beta11 it shows in the GUI as v2023.8.0-beta10, But this issue is fix now.

Please restart HA, that should be beta11 after restart.
