### ISSUE TITLE
[Bug] TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by JeeCee1** [jeroenterheerdt/HAsmartirrigation#158]
**Describe the bug**
File "/config/custom_components/smart_irrigation/__init__.py", line 578, in async_update_zone_config
    zone_id = int(zone_id)
              ^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**To Reproduce**
See [here](https://github.com/jeroenterheerdt/HAsmartirrigation/issues/157) for my config.
Pressing "Update all zones" results in the above error.

**Expected behavior**

**Screenshots**

**Installed version**
Beta 11

**Additional context**

**Comment by jeroenterheerdt** [comment]
should be fixed in beta12

**Comment by JeeCee1** [comment]
This error is gone now, on to the next! Tnx for the bug squashing.
