### ISSUE TITLE
ver. 2 Bugs in Zone settings

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#159]
### What happened?

1. Can't delete a single zone.
2. When changing any setting of single zone it is not updated rather creates a new one as sensor.zone or sensor.<oldname>-2. This and above leads I can't delete or rename default zone.
3.  zone sensors have no "module" and "mapping" attributes and may be this prevents to set them rather then 0 defaults.

### How to reproduce

Smart Irrigation Dashboard Zone Settings[](url)

### Which version are you running?

ver.2 beta 12

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-057d559e436f3038853d8be3ccc738fa.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12383660/config_entry-smart_irrigation-057d559e436f3038853d8be3ccc738fa.json.txt)

**Comment by jeroenterheerdt** [comment]
@andreid1303 I am unable to reproduce the first issue. I was perfectly able to delete a zone using your config.
However, I did spot a couple of issues in your config that have to do with older betas that we since have moved away from - Please remove the install, restart HA and start over. Sorry for the inconvience here.

**Comment by andreid1303** [comment]
Ok, once again I have deleted Smart Irrigation integration in HA, uninstalled it in HACS, restarted HA, installed beta 13 in HACS, added Smart Irrigation integration in HA. 
In this fresh install I have deleted all default zones and create a new without described issue but now pyETO and Static modules are not available.

**Comment by andreid1303** [comment]
I will close this bug and open a new one.
