### ISSUE TITLE
beta 13: After delete all default zones and create a new one no modules are available.

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#161]
### What happened?

 I have deleted all default zones and create a new. No pyETO and Static modules are available for choosing or creation.

### How to reproduce

I have deleted Smart Irrigation integration in HA, uninstalled it in HACS, restarted HA, installed beta 13 in HACS, added Smart Irrigation integration in HA.

### Which version are you running?

beta 13

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12385214/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json.txt)

**Comment by gatonero** [comment]
I can confirm.

```
This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:641
Integration: Smart Irrigation (documentation, issues)
First occurred: 11:13:21 (6 occurrences)
Last logged: 11:15:14

Calculate all zones failed: no data available.
```

**Comment by jeroenterheerdt** [comment]
> I can confirm. I'm also on beta-13
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.smart_irrigation
> Source: custom_components/smart_irrigation/__init__.py:641
> Integration: Smart Irrigation (documentation, issues)
> First occurred: 11:13:21 (6 occurrences)
> Last logged: 11:15:14
> 
> Calculate all zones failed: no data available.
> ```

This is not necessarily an error though. It just says that there was nothing to calculate with as the sensor data wasn't update beforehand. It might be caused by the issue with the modules though, but it's doesn't have to be. @gatonero can you generate a diagnostic file as described in the bug report template and add it here?

**Comment by gatonero** [comment]
Here is my diagnostic file.

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12386178/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by jeroenterheerdt** [comment]
should be fixed in beta 14

**Comment by DanDan800** [comment]
calculation is not working for no zone anymore after update from beta 13 to beta 14. Before primary zone calculated. 


Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:637
Integration: Smart Irrigation (documentation, issues)
First occurred: 10:28:01 (9 occurrences)
Last logged: 10:36:20

Calculate zone Rasen gesamt failed: no data available.

**Comment by gatonero** [comment]
beta 14 works much better.   One of three zone are calculated.

```
This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:642
Integration: Smart Irrigation (documentation, issues)
First occurred: 14:32:27 (2 occurrences)
Last logged: 14:32:27

Calculate all zones failed: no data available.
```

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12388165/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by gatonero** [comment]
Now is the question, how to trigger an automation?

**Comment by DanDan800** [comment]
I use the calculated value in combination with "Irrigation Unlimited".
[](https://github.com/rgc99/irrigation_unlimited#92-hasmartirrigation)

Check chapter 9.2.

**Comment by gatonero** [comment]
> I use the calculated value in combination with "Irrigation Unlimited". [irrigation Unlimited ](https://github.com/rgc99/irrigation_unlimited#92-hasmartirrigation)
> 
> Check chapter 9.2.

There isn't a sensor.smart_irrigation_daily_adjusted_run_time anymore in the new version.

**Comment by DanDan800** [comment]
Yes, That's correct. You have to change this to the new sensor name. It's state is the irrigation time in seconds.

**Comment by jeroenterheerdt** [comment]
So, let me explain (the logs say this as well, but OK). When you calculate a zone that has no data for it yet, the calculation will fail, resulting in the error in the log. This should only happen if you haven't first updated the zones weather data.
Second,if you call the service or press the button to update all zones or calculate all zones, only the automatic zones are taken into account because for disabled or manual zones no updates or calculations are necessary. I hope this helps (and it's also in the wiki but who reads those?) Please confirm that this is the behavior you are seeing. If you are seeing anything else please let me know.

**Comment by gatonero** [comment]
This time I read the wiki very closely. ;-)

Is there anny need to reset a bucket after irrigation?

**Comment by jeroenterheerdt** [comment]
> I can confirm this behaviour.
> 
> This time I read the wiki very closely. ;-)
> 
> Is there any need to reset a bucket after irrigation?

right now, yes, but if we can find a way to make actually performing an irrigation part of this component without duplicating too much of what HA provides, then I think we can also just reset the bucket to 0 after irrigation is done.

**Comment by jeroenterheerdt** [comment]
> beta 14 works much better.
> 
> When calculating all, one of three zones are calculated.
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.smart_irrigation
> Source: custom_components/smart_irrigation/__init__.py:642
> Integration: Smart Irrigation (documentation, issues)
> First occurred: 14:32:27 (2 occurrences)
> Last logged: 14:32:27
> 
> Calculate all zones failed: no data available.
> ```
> 
> [config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12388165/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)
> 
> When doing it one by one **it works**! :-)
> 
> [config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7-one-by one.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12388185/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7-one-by.one.json.txt)

found and fixed the bug where only the first zone would get calculated when you did 'calculate all'. So that should be fixed in beta 14.

**Comment by gatonero** [comment]
I'm now on beta15.

In beta 14 'smart_irrigation_start' isn't fired still.

**Comment by andreid1303** [comment]
Beta 16 has fixed this

**Comment by jeroenterheerdt** [comment]
> I'm now on beta15.
> 
> In beta 14 'smart_irrigation_start' isn't fired still.

Again, please make your own issues. One bug, one issue. It's not that hard really. If you just keep adding on to other people's bugs that are even about what you're experiencing I probably won't notice. Don't be shy, open an issue if you cannot find an issue that is exactly the same as what you're seeing and don't reuse an issue thread for a new error you're seeing. I am closing this now since the original issue is solved.
