### ISSUE TITLE
[bug] Zone 2 does not update, maybe related to warning "Calculate all zones failed: no data available"?

### ISSUE THREAD

**Issue by JeeCee1** [jeroenterheerdt/HAsmartirrigation#162]
### What happened?

When updating, zone 2 runtime does not get updated.
When pressing "Calculate all zones" (this does not happen when only calculating zone 2) the above error occurs.
[config_entry-smart_irrigation-bb2283a50b72fca97ae3d675af0c48c8.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12385399/config_entry-smart_irrigation-bb2283a50b72fca97ae3d675af0c48c8.json.txt)

### How to reproduce

Still the same config as in my other bug reports.

I have manually adjusted the "bucket" value for zone 2 to a negative value, since the bucket for zone 1 was also negative, but this did not resolve the issue.

### Relevant log output

```shell
Source: custom_components/smart_irrigation/__init__.py:641
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues))
First occurred: 10:22:15 AM (1 occurrences)
Last logged: 10:22:15 AM
Calculate all zones failed: no data available.
```

### Which version are you running?

beta12

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Some small issues, do you want (bug) reports for each?

- WIKI: `Only a single instance is allowed. Previously the component could be added multiple times to support multiple zones. Zone support is not built-in.` Should this be `**is** built in`?
- Each time when manually updating a zone the bucket and runtime increase, is this as designed? 
- FR: Can the calculated ET value be displayed, maybe in the sensor's attributes?
- `When a calculation happened, a verbose explanation is available so you can check the math and see if it makes sense.` Where can I find this? I see nothing in the logs (when filtering 'irrigation')
- For the wiki: what is the difference between `update` and `calculate`?

**Comment by jeroenterheerdt** [comment]
Great feedback thanks! No need to open a separate issue for these small things you mention at the end. I will look at your bug as well of course. Thanks for rigorous testing!

**Comment by JeeCee1** [comment]
Hmm, I verified everything again since I didn't restart after updating to beta13...
Only then I noticed that the Module and Mapping selections needed to be selected again.
After doing that, the "bug" with zone 2 disappeared, but the bug when selecting "Calculate All Zones" still exists.

Edit: that worked once, now the "modules" and "mappings" tabs are empty, even after reloading the integration...

**Comment by jeroenterheerdt** [comment]
so what you're seeing with modules and mappings is a bug, which I am fixing now. Calculate all zones does what it is supposed to do: you have not updated the weather data for the zone first (either manually or let it happen automatically) so there is nothing to calculate with, hence the error.
not sure what you mean with 'manually updating the zone the bucket and runtime increases', can you explain? if you update a zone and a positive ET value gets calculated then of course the bucket is updated and the runtime should reflect that.
the verbose explanation is under the little [i] icon with the zone after you press calculate. It's for use during set up / configuration / troubleshooting only really.
I will update the wiki with the other items and will try to get the ET value as a sensor attribute as you requested.

**Comment by jeroenterheerdt** [comment]
should be fixed in beta 14
