### ISSUE TITLE
PyETO Coastal not required

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#168]
### What happened?

"PyETO Coastal" is marked as required, but it isn't

### How to reproduce

Open tab Modules

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7b9a4770-6760-4117-8b6c-eb7f87f80eb8)

### Which version are you running?

beta 16

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12395999/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by jeroenterheerdt** [comment]
It is required. It has to be checked or not checked. It is default off, so not checked. But OK, the UI seems to indicate you need to check it, which is not true. I will make it not required. However, technically it is still required, but can be either off or on.

**Comment by gatonero** [comment]
I understand it. But UI is for users, who look at it. ;-)

**Comment by jeroenterheerdt** [comment]
fixed in beta 17, please verify and close.

**Comment by gatonero** [comment]
It disapeared.
