### ISSUE TITLE
smart_irrigation.reset_bucket doesn't reset zone id:0

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#169]
### What happened?

I wanted to reset the bucket of my zones one by one. Two of three zones were reseted, but not the one with id:0 

```
service: smart_irrigation.reset_bucket
data: {}
target:
  entity_id:
    - sensor.bewasserung_wohnzimmer
```

What works is:

```
service: smart_irrigation.reset_all_buckets
data: {}

```

### How to reproduce

Call the service: smart_irrigation.reset_bucket for zone id:0

### Relevant log output

```shell
None
```

### Which version are you running?

v2023.8.0-beta16

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12398435/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by jeroenterheerdt** [comment]
fixed in beta 17

**Comment by gatonero** [comment]
Yes, this bucket now also gets reset. :-)
