### ISSUE TITLE
smart_irrigation.calculate_all_zones doesn't calculate any zone

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#171]
### What happened?

Starting this service should update all zone. But not one was updated.

smart_irrigation.calculate_zone works

### How to reproduce

Start service smart_irrigation.calculate_all_zones

### Relevant log output

```shell
None
```

### Which version are you running?

v2023.8.0-beta17

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12399223/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by jeroenterheerdt** [comment]
should be fixed in beta 18. please confirm and close.

**Comment by gatonero** [comment]
confirm
