### ISSUE TITLE
Updating to new beta does not restore buckets.

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#176]
### What happened?

After beta update all buckets have been reset to zero.  
Durations as attributes were restored but Calculate Zone call recalculated them based on new bucket value.
I think such attributes as bucket, daily evapotranspiration, precipitation are necessary in case someone wants history records.

### How to reproduce

When zone' buckets set to some value update to new beta.

### Which version are you running?

v.2 beta 19

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-2.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12408314/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-2.txt)

**Comment by andreid1303** [comment]
Sorry, I see now that duration is sensor value, not attribute.

**Comment by jeroenterheerdt** [comment]
So is this a bug or no? I don't think I have seen this issue before.

**Comment by andreid1303** [comment]
Of course this is a bug. I lost auto calculated ETO data for previous day.

**Comment by jeroenterheerdt** [comment]
I don't understand - was the sensor data not persisted? The only thing you really care about is the sensor duration, the rest is not very interesting, I'd say. You need the sensor duration to run your irrigation.

**Comment by andreid1303** [comment]
It seems the sensor value i.e. duration calculated from the bucket each calculation call, so not persistent actually.

**Comment by jeroenterheerdt** [comment]
that is not what I am seeing at all. The durations are persisted on my side. Can you show screenshots?

**Comment by jeroenterheerdt** [comment]
not sure what you mean with the screenshot: I am seeing the bucket values here? Were they not there after your rebooted/upgraded?

**Comment by andreid1303** [comment]
I've pushed Calculate Zone after upgrade and duration recalculated as you see in the screenshot.

Should I avoid Calculate Zone? Each time it increments bucket like -5.4-5.4=-10,6 then -10,6-5,4=16,0 and so on. 
Whenever I call Update Zone nothing changes.
It is not clear what Calculate Zone does and what Update Zone does.

**Comment by andreid1303** [comment]
I checked the data after midnight automatic update and see that now bucket is 0 and duration is 1940.
![Снимок экрана 2023-08-23 в 07 07 32](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/58367592/9c2b5f03-dfcd-4292-a6fe-d7b04cda0060)

So I guess reseting bucket is a normal behaviour and it will never persist. 
And Calculate Zone is for test purpose only, it WILL OVERWRITE  actual duration.  That is why I lost previous day data.

**Comment by jeroenterheerdt** [comment]
yes, calculate will override the duration. you are expected to do:
- one or more updates (after we fix #182 you don't have to do this if you only want to collect weatherdata once)
- a calculate per zone
- _run your irrigation_, after all that's why we're doing this, right?
- reset your buckets.


This is very similar to V1.

**Comment by andreid1303** [comment]
Ok, thank you for explaining.
