### ISSUE TITLE
Just two of four zones are updated

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#189]
### What happened?

I expected that all zones were updated but just two of four are updated and the calculated values are terribly low.

### How to reproduce

`Smart Irrigation: calculate_all_zones`

### Relevant log output

```shell
None
```

### Which version are you running?

beta

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12424157/config_entry-smart_irrigation-6f22650b100cefed9d7411c48a4ba2b7.json.txt)

**Comment by gatonero** [comment]
Soory my fault.

zone id:2 bucket two little

zone id:3 in state manual

**Comment by jeroenterheerdt** [comment]
those are the best bugs... the user error bugs :)
