### ISSUE TITLE
[REQ] maximum duration (after multiplier and before lead time) 

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#191]
@**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeroenterheerdt** [comment]
hey @gatonero, beta 28 introduces two new literals in `translations/en.json` file. Please add these and the German translation to the `translations/de.json` file.

        "maximum-duration-is-applied": "Then, the maximum duration is applied. The maximum duration is",
        "duration-after-maximum-duration-is": "hence the duration is",

**Comment by gatonero** [comment]
This is just for the documentation.  #209 is still open.
