### ISSUE TITLE
[REQ]  Rename Mapping to Sensors and Sensor Groups

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#192]
I translated the language files into German. It struck me that the term mapping is very unwieldy.

It is easier for a user to understand that these are sensors or sensor groups which can subsequently be assigned to individual zones.

I would like to suggest replacing the term mapping with sensors and sensor groups.

**Comment by jeroenterheerdt** [comment]
Happy with any term that makes sense, but not sure I agree with sensor groups. That is not what this is. This is a map of where to find what value. So, a mapping. If we can come up with another short word for this, I am all for it but sensor groups it is not

**Comment by gatonero** [comment]
What's about sensors and sensor set?

[Set (abstract data type)](https://en.wikipedia.org/wiki/Set_(abstract_data_type))

**Comment by jeroenterheerdt** [comment]
Maybe. @dlindnegm care to weigh in?

**Comment by dlindnegm** [comment]
Something like this:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/ff3fe556-0722-47c3-9942-796237edab83)

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/24968305/bbfa5e71-b069-4834-81bb-eaa4d11ae88d)

**Comment by jeroenterheerdt** [comment]
How about Connections instead?

**Comment by dlindnegm** [comment]
I would consider OWM no different than my Ambient Weather Station.  Both are Integrations in HA, both report sensor data (rain, wind, etc) into HA as sensors.  Both get their data from physical sensors in the field. I can mix and match those sensors into a group, and Smart Irrigation uses that group to determine evapotranspiration rate.  And a static value would be considered a virtual sensor in HA.  So we are mapping/grouping/configuring sensors for use by a zone.

**Comment by gatonero** [comment]
I would like to sugest again. sensor set.

**Comment by jeroenterheerdt** [comment]
OK, let's go with sensor group instead of mapping. I don't like sensor set.

**Comment by gatonero** [comment]
In the english and german language files I changed mapping to sensor group(s) but no  literals.
