### ISSUE TITLE
Warning: weatherdata update time on or after calculation time! 

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#193]
### What happened?

Even update time is after calculation time there is a warning.

### How to reproduce

Fiddle with update and calculation time.

### Relevant log output

```shell
None
```

### Which version are you running?

v2023.8.0-beta23

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/eb7a86d1-4684-4d17-a55c-5d90337a26e9)

**Comment by jeroenterheerdt** [comment]
This is not a bug. This is by design to warn the user their config is wrong... They should have their update time before the calc time.... What do you want me to do here?

**Comment by jeroenterheerdt** [comment]
This is by design. Your update time is after the calc time which ir should not be. It should be before. So not sure what you think the bug is.

**Comment by gatonero** [comment]
The warning says something different.

**Comment by gatonero** [comment]
My missunderstanding of the message.
