### ISSUE TITLE
[REQ] Rename Component to Integration

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#194]
Users install an integration via HACS, not a component.  

This Integration has
1.  one device (Smart Irrigation is a virtual device.)
1.  and for each zone an entity

beside some attributes and one (exposed) service.

Think of it like a humidity sensor, for example. In this case, you can only have one, such as a Zigbee stick.

Why confronting with new expressions? This is what the users used. Everything else is developer spiritualism. ;-)

**Comment by jeroenterheerdt** [comment]
Agreed!

**Comment by gatonero** [comment]
I will Update README.md.

**Comment by jeroenterheerdt** [comment]
Please let's keep it for open so it serves as a reminder for me to do the actual work.
