### ISSUE TITLE
Change default update time

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#195]
### What happened?

After upgrade to beta 19-23  difference with default OW and my sensors calculations: 1832 s vs 216s.
Same area and flow rate.
Before the upgrade they were very close to each other.

### How to reproduce

 I have not changed settings and observed this behaviour for 3 days, reseting buckets each morning.

### Which version are you running?

beta 23

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12445591/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json.txt)

**Comment by andreid1303** [comment]
I the attached diagnostics I see that aggregated data for my sensors is not calculated correctly:
Min and max temp is the same 11.6 C while here is origin last day history:

![Снимок экрана 2023-08-26 в 18 02 05](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/58367592/6bb264c5-b102-453a-9267-8de1718d62ae)

Solrad:
![Снимок экрана 2023-08-26 в 18 03 25](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/58367592/548ff15d-b3a3-4ada-871b-c5ba236c001d)

**Comment by jeroenterheerdt** [comment]
Thanks, I will need to take a closer look as to why your OWM and sensors are so different, but you have your sensor configured to update just once a day, so of course min and max are the same.

**Comment by dlindnegm** [comment]
Suggestion to change the default for automatic update from 00:00 to 23:55, or 5 minutes before the current default for automatic calculation.

**Comment by andreid1303** [comment]
Strange but I didn't change these settings.
Following your suggestion, my new general settings: 

-  Automatic weather data updates: every 5 minutes, starting at 00:00
-  Automatic duration calculation: at 23:59

With new settings Calculate All Zones immediately gave expected results: -5.5 mm for OW and -5.6 mm for my My Sensors, like previously recorded data was used. 

Does your integration push the recording or it uses my recordings as well? 
Should I care my sensors data smooth enough if the integration weather updates take only current values? 
See my Solar Radiation sensor for example.

**Comment by jeroenterheerdt** [comment]
> Strange but I didn't change these settings. Following your suggestion, my new general settings:
> 
> * Automatic weather data updates: every 5 minutes, starting at 00:00
> * Automatic duration calculation: at 23:59
> 
> With new settings Calculate All Zones immediately gave expected results: -5.5 mm for OW and -5.6 mm for my My Sensors, like previously recorded data was used.
> 
> Does your integration push the recording or it uses my recordings as well? Should I care my sensors data smooth enough if the integration weather updates take only current values? See my Solar Radiation sensor for example.

Not sure what you mean with 'push the recording or it uses my recordings as well'?

**Comment by jeroenterheerdt** [comment]
> Suggestion to change the default for automatic update from 00:00 to 23:55, or 5 minutes before the current default for automatic calculation.

Reopening to track this.
