### ISSUE TITLE
Calculations not rounded

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#199]
### What happened?

After update to v2023.8.0-beta25 bucket and duration calculation are not rounded with local "," decimal pointer.
Decimal separator ',' is only in GUI and it is not an issue.

### How to reproduce

After update I called Calculate All Zones.

### Which version are you running?

v2023.8.0-beta25

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-2.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12461947/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-2.txt)

**Comment by jeroenterheerdt** [comment]
Did you read the notes when you installed it? Please go back and read it.
