### ISSUE TITLE
User input malformed

### ISSUE THREAD

**Issue by Sergbmw** [jeroenterheerdt/HAsmartirrigation#2]
![712d0df4b5](https://user-images.githubusercontent.com/54317682/82339874-3433c000-99f7-11ea-8b7d-2d27b6ebdc6d.jpg)

**Comment by jeroenterheerdt** [comment]
This is because it expects a decimal for flow. You can fix this by just adding '.0' to the '2'. I will look at fixing this in the code as well to allow whole numbers as well.

**Comment by Sergbmw** [comment]
![1589900049395](https://user-images.githubusercontent.com/54317682/82341996-c76df500-99f9-11ea-85fe-71fcaf9bd29a.jpg)

**Comment by jeroenterheerdt** [comment]
Read the labels. Number of sprinklers is a whole number, how can you ever have a half sprinkler? Again, I will make the code more forgiving.

**Comment by Sergbmw** [comment]
I tried all the options
![1589901022531](https://user-images.githubusercontent.com/54317682/82343897-0ef58080-99fc-11ea-95c8-8f60b5eeccf2.jpg)

**Comment by jeroenterheerdt** [comment]
That is weird. I'll check

**Comment by jeroenterheerdt** [comment]
https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.07 fixes this. please install this new version using HACS.

**Comment by jeroenterheerdt** [comment]
please confirm and close the issue if it was resolved.

**Comment by Sergbmw** [comment]
not effect

**Comment by Lee-View** [comment]
It is not working for me, either. Getting the same: “user input malformed”.

**Comment by jeroenterheerdt** [comment]
@Lee-View please share the values you are using. @Sergbmw have you restarted HA before trying again? I have used your exact values in my test and it works fine.

**Comment by Lee-View** [comment]
Restarting now and I’ll post a screenshot after.

**Comment by Sergbmw** [comment]
![1589908338612](https://user-images.githubusercontent.com/54317682/82356984-0fe2de00-9a0d-11ea-8be9-ee72e90ad742.jpg)

**Comment by jeroenterheerdt** [comment]
@Sergbmw, a different error this time. interesting. checking now.

**Comment by Lee-View** [comment]
It’s working for me now. Thanks a lot.

**Comment by jeroenterheerdt** [comment]
@Lee-View awesome thanks for confirming!

**Comment by Lee-View** [comment]
![539D53EF-0C67-4AE3-94BB-324658683CCB](https://user-images.githubusercontent.com/60480810/82359557-b4b2ea80-9a10-11ea-8c69-5e3dd50532e4.png)
Out of topic: trying to make use of what I got now.

**Comment by jeroenterheerdt** [comment]
@Lee-View -  I see there is a bug there on area. I will fix it soon. Give me some time to expand the readme to explain the values you see here.

**Comment by jeroenterheerdt** [comment]
@Lee-View - I have expanded the documentation (https://github.com/jeroenterheerdt/HAsmartirrigation). Also, there is a new version that fixes your bug.

**Comment by jeroenterheerdt** [comment]
@Sergbmw the newest version also fixes your issue.

**Comment by jeroenterheerdt** [comment]
opened up a topic on HA forum as well: https://community.home-assistant.io/t/smart-irrigation-safe-water-by-precisely-watering-your-lawn-garden/

**Comment by Sergbmw** [comment]
all works, thank
