### ISSUE TITLE
German translation not present in  v2023.8.0-beta24

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#200]
### What happened?

I changed the language to German in my profile but Smart Irrigation stayed in English.

### How to reproduce

Change language in your HA profile to German.

### Relevant log output

```shell
None
```

### Which version are you running?

 v2023.8.0-beta24

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
that is weird. Did the UI in HA reflect the change to German? Did you reboot HA?

**Comment by gatonero** [comment]
It worked when I switched to Dutch immediately but not for German. Even after a restart of HA.

**Comment by jeroenterheerdt** [comment]
Hmm, that is interesting as I don't see why that would be any different...

**Comment by jeroenterheerdt** [comment]
so @gatonero what are you seeing? Can you make screenshots? I'd like to see what you're seeing when you changed to Dutch and what happened when you switched to German. Not only the UI (smart irrigation panel) but also the attributes of the sensors that smart irrigation creates.

**Comment by gatonero** [comment]
Nederlands (immediate change)

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/b4212f16-46e0-4d1d-a359-cd7f50ff1b91)

aaand nohow :-) German

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/0e43f25d-9508-4400-90d5-6d2ef4a4a34b)

**Comment by jeroenterheerdt** [comment]
... So it works??

**Comment by gatonero** [comment]
Yes, yes, yes!!!
