### ISSUE TITLE
german files need an update

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#203]
### What happened?

@gatonero please update the german files, I added a short english utterance in `module-returned-evapotranspiration-deficiency`.
Please wait for next beta.

### How to reproduce

install beta 26

### Which version are you running?

beta26

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
I'm on beta26 and don't see any changes.

**Comment by jeroenterheerdt** [comment]
it's here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/v2.0/custom_components/smart_irrigation/translations/de.json#L65

**Comment by gatonero** [comment]
Yes I know. But what's the difference compared to before?

**Comment by jeroenterheerdt** [comment]
There are literally a couple of Engels words there that need translating... 😂

**Comment by gatonero** [comment]
Haha, i was blind.

**Comment by gatonero** [comment]
Strange this was translated in my local repository. Don't know, why it wasn't pushed. I made a small change and pushed it again.
