### ISSUE TITLE
Bucket value not saving

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#209]
### What happened?

After HA restart Bucket is set to 0, but Duration stays as it was. Looks like component doesn't reload this value from smart_irrigation.storage and instead resets it.

### How to reproduce

Set Bucket to any value. Make sure it's updated in storage file. Restart HA. Value in dashboard and in storage file will be reset.

[config_entry-smart_irrigation-43106bb5c08f0ae73bca6bc2e9ba24ea.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12483349/config_entry-smart_irrigation-43106bb5c08f0ae73bca6bc2e9ba24ea.json.txt)

### Which version are you running?

v2023.8.0-beta27

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Hmm, bucket should restore as duration. That's weird. Thanks for reporting.

**Comment by jeroenterheerdt** [comment]
should be fixed in beta 29: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.8.0-beta29. Please verify.

**Comment by omenek159** [comment]
Yes, now is fixed, but I had to manually add 'maximum_duration' to storage file because of #191. Without it, integration didn't want to start.
