### ISSUE TITLE
Label for precipitation - - > total precipitation

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#213]
### What happened?

Label for precipitation - - > total precipitation

### How to reproduce

Label for precipitation - - > total precipitation

### Which version are you running?

Beta

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
Done

**Comment by jeroenterheerdt** [comment]
You are fast!! Love it, great work!
