### ISSUE TITLE
Could not parse JSON content: /config/custom_components/smart_irrigation/translations/de.json

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#216]
### What happened?

Switch language to German, go to Settings -> Devices & Services -> Integration 'Smart Irrigation' , click 'Configure". You will get an error 
![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7d5da594-5b43-4e01-b1b9-3dc38bd2dfed)

If you click a second time you get a nearly blank window: 
![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/2aaf340b-39fe-4a12-b687-8a07eb0eeb88)

### How to reproduce

see above

### Relevant log output

```shell
Logger: homeassistant.util.json
Source: util/json.py:68
First occurred: 16:42:09 (44 occurrences)
Last logged: 19:18:23

Could not parse JSON content: /config/custom_components/smart_irrigation/translations/de.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 113 column 5 (char 5676)
```

### Which version are you running?

v2023.8.0-beta29

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
you broke the german language file apparently

**Comment by gatonero** [comment]
Yes I know. With the new push it should be fixed.

**Comment by gatonero** [comment]
The blank screen is also fixed with the last push.

**Comment by jeroenterheerdt** [comment]
rolled this into v2023.9.0-beta1
