### ISSUE TITLE
DE language file needs a quick update

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#217]
### What happened?

English and NL language file also define `duration-after-maximum-duration-is`
(here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/v2.0/custom_components/smart_irrigation/translations/en.json#L79)

Can you add it to the DE language file as well? I know it's probably the same, but split it out just to cater for the situation that these two things are not completely the same.

### How to reproduce

set language to DE and notice that part of the explanation is English.

### Which version are you running?

2023.9.0-beta2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

no diag file required.

**Comment by gatonero** [comment]
It's  there
```

    "module": {
      "calculation": {
        "explanation": {
          "module-returned-evapotranspiration-deficiency": "Beachte: diese Beschreibung nutzt '.' als Dezimaltrennzeichen. Das Modul berchnete einen Evapotranspirationsmangel von",
          "bucket-was": "Der alte Vorrat war",
          "new-bucket-values-is": "Der neue Vorrat ist",
          "old-bucket-variable": "alter_Vorrat",
          "delta": "Veränderung",
          "bucket-less-than-zero-irrigation-necessary": "Wenn der Vorrat < 0 ist, ist eine Bewässerung nötig",
          "steps-taken-to-calculate-duration": "Für eine exakte Berechnung der Dauer, wurden folgende Schritte durchgeführt",
          "precipitation-rate-defined-as": "Der Niederschlag ist",
          "duration-is-calculated-as": "Die berechnete Dauer ist",
          "bucket": "Vorrat",
          "precipitation-rate-variable": "Niederschlag",
          "multiplier-is-applied": "Der Multiplikator wird angewendet. Der Multiplikator ist",
          "duration-after-multiplier-is": "also ist die Dauer",
          "maximum-duration-is-applied": "Dann wird die maximale Bewässerungsdauer angewendet. Die maximale Bewässerungsdauer ist",
          "duration-after-maximum-duration-is": "also ist die Dauer",
          "lead-time-is-applied": "Zuletzt wird die Vorlaufzeit angewendet. Die Vorlaufzeit ist",
          "duration-after-lead-time-is": "also ist die Dauer",
          "bucket-larger-than-or-equal-to-zero-no-irrigation-necessary": "Wenn der Vorrat >= 0 ist, ist keine Bewässerung nötig und die Dauer ist gleich"
        }
      }
    },

```
But I see a mixed result.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/24ca1113-00dc-4e3b-b208-ef195694dc1e)

**Comment by jeroenterheerdt** [comment]
so your UI files are fine for german, but it looks like it cannot read the german integration language file... (the explanation is all English, which is the fallback in case it cannot find it in the language you're asking for)

**Comment by jeroenterheerdt** [comment]
more updates required, see this commit; https://github.com/jeroenterheerdt/HAsmartirrigation/commit/f6f4984f2b61f24488abd53ec3eb67291b107e1b#diff-2bf4157d0e88a2647055e2081f020e6d0698a9f621d23d61cc29152597df98f6

**Comment by jeroenterheerdt** [comment]
ok, I found a major issue. I don't know what you did maybe or the addin you are using did, but the language files are broken now. Loads of duplication everywhere. This is _not good_.

**Comment by jeroenterheerdt** [comment]
I restored the language files, please be more careful next time. Consider not using the add-on.

**Comment by gatonero** [comment]
Thanks for your tun! Sorry about my fault! Now everything looks like expected.
