### ISSUE TITLE
No option to redowmload beta

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#218]
### What happened?

I wanted to install a fresh beta version. I removed the instance, storage file was deleted, restarted HA, installed 6a2a37d because no beta option was available, restarted HA again and wanted to redownload a beta version. There is no option to choose beta. Also refreshed the cache several times and started the browser and tried it again.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/a4949f0f-8310-42e4-8ca8-799b4323da6c)

Also no panel is available. Other extensions show the beta download option.

### How to reproduce

see above

### Relevant log output

```shell
none
```

### Which version are you running?

6a2a37d

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Yeah, that was reported here as well. https://github.com/jeroenterheerdt/HAsmartirrigation/issues/186#issuecomment-1703686080

I have no idea what is causing this other than a HACS fluke because of the number of new beta versions launched. Looks like fixing HACS is the solution here.

**Comment by gatonero** [comment]
I doubt that. Other extensions show the beta option. This happened on a brand new HA and HACS instance with noting else installed.

This is what Smart Irrigation looks like:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5dbddb62-216d-489b-85d8-698656a0d070)

and this is what Better Thermostat looks like under same circumstances:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/ad7522eb-b610-4f63-8597-490ad2e03981)

**Comment by jeroenterheerdt** [comment]
There is nothing I can do. It looks good on my end. I think this is just a temporary fluke of HACS.

**Comment by gatonero** [comment]
A temporary HACS Smart Irrigation fluke ;-)
So I will wait indefinitely. Until then I'm not able to contribute.

**Comment by jeroenterheerdt** [comment]
I don't know man. I really don't know. I tried it here multiple times on multiple configurations and systems. All work fine.

**Comment by jeroenterheerdt** [comment]
I'd suggest opening an issue at HACS following these instructions: https://hacs.xyz/docs/issues/

I don't think this has anything to do with smart irrigation

**Comment by gatonero** [comment]
I followed your advice and opened [No option 'Show beta versions' when downloading an extension](https://github.com/hacs/integration/issues/3241)

**Comment by jeroenterheerdt** [comment]
Have you tried doing update information and then re-download? That's how I get the beta versions

**Comment by gatonero** [comment]
Issue was in wrong category. Now [No option 'Show beta versions' when downloading an extension](https://github.com/hacs/integration/issues/3242)

**Comment by gatonero** [comment]
Sure I did IT but IT didn't help.

**Comment by gatonero** [comment]
@jeroenterheerdt version v0.0.82  showed the beta option again! 
![proxy-image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/52431b9c-7a6e-4c5f-81fb-9a3b591287fd)

**Comment by jeroenterheerdt** [comment]
> @jeroenterheerdt version v0.0.82 showed the beta option again!
> 
> ![proxy-image](https://user-images.githubusercontent.com/8248255/265252822-52431b9c-7a6e-4c5f-81fb-9a3b591287fd.png)

That's awesome and weird. As if HACS got confused because of the number of beta versions and the lack of release versions... I don't know. Please let them know in the bug you opened there. Glad it is resolved though!

**Comment by gatonero** [comment]
@jeroenterheerdt answer from HACS:

"There was too many beta versions, so a regular version was not found, so it falled back to commit only.
You can increase the number in HACS options.

https://hacs.xyz/docs/configuration/options"

**Comment by jeroenterheerdt** [comment]
Kind of weird that they would have a setting like that. Anyway good that we know about it now in case we need it again 😂
