### ISSUE TITLE
Reset_bucket service doesn't work when started from NR

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#219]
### What happened?

Continuing after #181.

Looks like if there is only one entity in call-service node it sends it as string which doesn't take place if called directly from HA. Thats the problem because component always treat it as list. The simpliest solution I think of is to make sure it is a list and in case of being otherwise convert it.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/10829566/b48a1f3b-ee9b-45c1-81d3-23920703e762)

### How to reproduce

Call service from NR.

### Which version are you running?

beta29

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
ok, I made that change. Hopefully it helps!

**Comment by omenek159** [comment]
It's ok now.
