### ISSUE TITLE
[REQ] No translation for 'static value'

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#222]
**Is your feature request related to a problem? Please describe.**
see title

**Describe the solution you'd like**
Field for translation

**Describe alternatives you've considered**

**Additional context**
![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5bb99840-5fba-4612-906d-1cb0a0a47a96)

**Comment by jeroenterheerdt** [comment]
Oops, looks like I added it to the language file but don't as actually use it in the UI?

**Comment by jeroenterheerdt** [comment]
well, this is no bug on my side - you just need to add the following key to the `DE` language file:
`panels.mappings.cards.mapping.sources.static`. Should be around line 88. Compare with `EN` language file: `"static": "Static value"`.

What the code does is what I want: if it can't find something in a specific language, return the English value. Assiging this to you as you the master of language files :)

**Comment by jeroenterheerdt** [comment]
tagging French language owner @diyanei and Italian language owner @valerix85 so they can track this as well.

**Comment by gatonero** [comment]
I added "static_value" (line 94) and "static" (line 101) in de.json and don't see any errors in that file. But I don't see it in UI.

**Comment by jeroenterheerdt** [comment]
It takes a while (cache), restarting HA and browser normally helps. But sometimes multiple times doing that cycle is necessary to force it to update.

**Comment by gatonero** [comment]
I did it several times today.

**Comment by jeroenterheerdt** [comment]
That is weird. I will try forcing it in German and see if I can spot any issues.

**Comment by jeroenterheerdt** [comment]
I changed my UI settings to German and see this:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8188990/31e206f3-b4d6-4e30-b93f-d353aeb9653e)

So it looks good on my end, not sure what is going on on your side.

**Comment by gatonero** [comment]
Closed. See #223
