### ISSUE TITLE
[REQ] No translation for help

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#223]
**Is your feature request related to a problem? Please describe.**
see title

**Describe the solution you'd like**
Add translation

**Describe alternatives you've considered**

**Additional context**
![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7d356423-5e62-4cb4-a928-08a2fdbc2159)

**Comment by jeroenterheerdt** [comment]
What part? Hilfe is translated?

**Comment by gatonero** [comment]
But all the text below is English.

**Comment by jeroenterheerdt** [comment]
Yes, got it

**Comment by jeroenterheerdt** [comment]
Assiging to you to update `de` language file. Latest beta introduces localized strings for this (see `en` language file)

**Comment by jeroenterheerdt** [comment]
Added in https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.9.0-beta8. Please update `de` language file. Also tagging French language owner @diyanei and Italian language owner @valerix85 so they can eventually update their respective languages as well.

**Comment by gatonero** [comment]
Because of #222 I reopened

**Comment by jeroenterheerdt** [comment]
I changed my UI to German and see this:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8188990/7bd3171c-085d-4dec-8463-2df6067e3f7f)

So looks good to me, not sure what is going on on your end though.

**Comment by gatonero** [comment]
Very Weird. I have three installations.

1. A virtual machine on Proxmox. Productive system
2. A virtual machine on Proxmox, for testing purposes
3. A supervised Installation on my PC, for testing purposes

On each machine I installed v2023.9.0-beta10. I don't see this change. It's still in English when I switch to German. When I switch to the new languages Italian, French and Spanish on all machines All I see is English.

I will close #222 because it's seems to be the same reason.

**Comment by gatonero** [comment]
In /frontend/localize.ts I found following:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7edc3d6a-8267-4d4b-9052-b4a85db8c131)

The explanation is:

`Cannot find module 'intl-messageformat' or its corresponding type declarations.ts(2307)`

**Comment by gatonero** [comment]
In /frontend/localize.ts I found following:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7edc3d6a-8267-4d4b-9052-b4a85db8c131)

The explanation is:

`Cannot find module 'intl-messageformat' or its corresponding type declarations.ts(2307)`

**Comment by jeroenterheerdt** [comment]
> In /frontend/localize.ts I found following:
> 
> ![grafik](https://user-images.githubusercontent.com/8248255/265665168-7edc3d6a-8267-4d4b-9052-b4a85db8c131.png)
> 
> The explanation is:
> 
> `Cannot find module 'intl-messageformat' or its corresponding type declarations.ts(2307)`

That is normal if you just opened the file or are you in de dev container when this happens?

**Comment by jeroenterheerdt** [comment]
Yeah, so no dev container. I still think this is a browser / cache issue. Have you tried another browser? Clearing your browsers cache?

**Comment by gatonero** [comment]
Firefox, Vivaldi and Companion App. All caches deleted an restarted. Don't know what else.

**Comment by gatonero** [comment]
When I push something to the repository I'm getting following since days:
```

Integration smart_irrigation - /github/workspace/custom_components/smart_irrigation:
Error: R] [SERVICES] Service reset_bucket has no name and is not in the translations file
Error: R] [SERVICES] Service set_bucket has no name and is not in the translations file
Error: R] [SERVICES] Service set_bucket has a field value with no name and is not in the translations file
Error: R] [SERVICES] Service calculate_hourly_adjusted_run_time has no name and is not in the translations file
Error: R] [SERVICES] Service calculate_daily_adjusted_run_time has no name and is not in the translations file
Error: R] [SERVICES] Service enable_force_mode has no name and is not in the translations file
Error: R] [SERVICES] Service disable_force_mode has no name and is not in the translations file
Warning: G] [CONFIG_SCHEMA] Integrations which implement 'async_setup' or 'setup' must define either 'CONFIG_SCHEMA', 'PLATFORM_SCHEMA' or 'PLATFORM_SCHEMA_BASE'. If the integration has no configuration parameters, can only be set up from platforms or can only be set up from config entries, one of the helpers cv.empty_config_schema, cv.platform_only_config_schema or cv.config_entry_only_config_schema can be used.

Error: Process completed with exit code 1.
```

**Comment by jeroenterheerdt** [comment]
> Firefox, Vivaldi and Companion App. All caches deleted an restarted. Don't know what else. Also I don't see the new languages, it's all English for them.

neither do I.

**Comment by jeroenterheerdt** [comment]
> When I push something to the repository I'm getting following since days:
> 
> ```
> Integration smart_irrigation - /github/workspace/custom_components/smart_irrigation:
> Error: R] [SERVICES] Service reset_bucket has no name and is not in the translations file
> Error: R] [SERVICES] Service set_bucket has no name and is not in the translations file
> Error: R] [SERVICES] Service set_bucket has a field value with no name and is not in the translations file
> Error: R] [SERVICES] Service calculate_hourly_adjusted_run_time has no name and is not in the translations file
> Error: R] [SERVICES] Service calculate_daily_adjusted_run_time has no name and is not in the translations file
> Error: R] [SERVICES] Service enable_force_mode has no name and is not in the translations file
> Error: R] [SERVICES] Service disable_force_mode has no name and is not in the translations file
> Warning: G] [CONFIG_SCHEMA] Integrations which implement 'async_setup' or 'setup' must define either 'CONFIG_SCHEMA', 'PLATFORM_SCHEMA' or 'PLATFORM_SCHEMA_BASE'. If the integration has no configuration parameters, can only be set up from platforms or can only be set up from config entries, one of the helpers cv.empty_config_schema, cv.platform_only_config_schema or cv.config_entry_only_config_schema can be used.
> 
> Error: Process completed with exit code 1.
> ```
> 
> see #238

not sure what this even is. I have never seen this before. Is this the result of a git command? What is your workflow? What tools do you use? What commands do you run?

**Comment by gatonero** [comment]
Thanks god! 

Nonetheless for the record

1. Commit & Push
2. workfow? vscode,vscode-json, github, GitHub Pull Requests and Issues and some minor others like ssh, sftp, docker.
3. Tools see above
4. hardly at all cli git
5. aha, understand
6. Happy to ignore. 

Maybe last words before holiday (just with a small mobile).  :-)

**Comment by jeroenterheerdt** [comment]
enjoy your holiday!

**Comment by gatonero** [comment]
Thank you!

This morning I saw everything translated! 😋

**Comment by jeroenterheerdt** [comment]
Weird but glad it worked!
