### ISSUE TITLE
Update sensor data issue

### ISSUE THREAD

**Issue by apocaliss92** [jeroenterheerdt/HAsmartirrigation#224]
### What happened?

Hey, during the update weather data job the following happened

custom_components/smart_irrigation/__init__.py:322 
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues)) 
First occurred: 13:00:00 (1 occurrences) 
Last logged: 13:00:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 277, in _async_track_update_time
    await self._async_update_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 322, in _async_update_all
    weatherdata = await self.merge_weatherdata_and_sensor_values(weatherdata,sensor_values)
                                                                 ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'weatherdata' where it is not associated with a value

### How to reproduce

I made a new configuration from scratch right after the update and set the "first update" time at 13:00

### Which version are you running?

9beta7

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Thanks, I will take a look.

**Comment by gatonero** [comment]
![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/bba87bf5-01b1-4705-bc5e-a823b8e486e2)

**Comment by jeroenterheerdt** [comment]
> ![grafik](https://user-images.githubusercontent.com/8248255/265273454-bba87bf5-01b1-4705-bc5e-a823b8e486e2.png)

Are you seeing the same things in the log? If you are seeing something else please open a separate issue

**Comment by gatonero** [comment]
Yes I sae the same.

**Comment by jeroenterheerdt** [comment]
Should be fixed in https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.9.0-beta8

**Comment by gatonero** [comment]
No more issue here.
