### ISSUE TITLE
Adding a zone overwrites the last added zone 

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#226]
### What happened?

When adding a zone to existing zones it doesn't get added but overwrites the last added one. This doesn't happen if you start from zero.

### How to reproduce

Add a zone to existing zones. The log output is what I see in the logs in this case.

### Relevant log output

```shell
2023-09-03 20:58:18.208 INFO (MainThread) [custom_components.smart_irrigation] Start irrigation event smart_irrigation_start_irrigation_all_zones will fire at 2023-09-04 04:51:08.770331+00:00
```

### Which version are you running?

 v2023.9.0-beta7

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
I can't reproduce this behavior, but it might have been fixed as a side effect of other bug fixes I did already. Please try with the latest beta (that I will ship soon)

**Comment by jeroenterheerdt** [comment]
Please try: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2023.9.0-beta8 and let me know if the issue is still there.

**Comment by gatonero** [comment]
No more issue here.

**Comment by mauritsivs** [comment]
I'm on beta18, this bug is here still/again.
Can only add two zones maximum, after that it gets replaced by newly added

**Comment by jeroenterheerdt** [comment]
@mauritsivs please open an issue and provide a diagnostic file as instructed in the issue template so we can investigate
