### ISSUE TITLE
[REQ] reset buckets UI

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#228]
**Is your feature request related to a problem? Please describe.**
When testing changes on multiple  zones you need to go to the Developer Tools in HA to call the reset_all_buckets service, or manually change each bucket field to a zero. 

**Describe the solution you'd like**
It would be nice to have a Reset All Buckets button on the Zones page, as well as an icon to reset the bucket for any individual bucket alongside the update and calculate icons.

**Comment by jeroenterheerdt** [comment]
Great idea!

**Comment by dlindnegm** [comment]
Is there any way to refresh that tab immediately after a bucket reset without forcing a HA logoff?  I find I have to change to the General, Modules, or Sensor Groups tab & come back to the Zones tab to see that the buckets have been reset to zero.  I can see people complaining that it doesn't work otherwise!

**Comment by jeroenterheerdt** [comment]
> Is there any way to refresh that tab immediately after a bucket reset without forcing a HA logoff? I find I have to change to the General, Modules, or Sensor Groups tab & come back to the Zones tab to see that the buckets have been reset to zero. I can see people complaining that it doesn't work otherwise!

not sure I understand what you mean. Updates to buckets through UI or through service are visible immediately for me. Can you share screenshots of what you're seeing?

**Comment by jeroenterheerdt** [comment]
added in beta9 - please let me know what you think!

**Comment by dlindnegm** [comment]
I usually have a second instance of HA open, either on a second tab or in a second browser instance.  When I call the service Smart Irrigation: reset_all_buckets in Developer Tools and come back to other tab/browser, none of the buckets appear to be reset, so I have to select a different tab or page in HA and go back to see the changed values.  Now that you've added the option directly on the Zones page it updates immediately.  Thanks!!!

**Comment by jeroenterheerdt** [comment]
@gatonero this one is another to update in the DE file.

**Comment by dlindnegm** [comment]
This is working well, so closing this....
