### ISSUE TITLE
Calculate for zone failed: no data available

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#235]
### What happened?

All Zones Calculation failed with warning "no data available" if I call it after Reset All Buckets.

But if I call a sequence Reset All Buckets -> Update All Zones -> Calculate All Zones  I get the calculation.
Calculated bucket values for OW: -2,9 mm vs for OW vs -35,0 mm for own sensors.  Do not understand why such a difference.

### How to reproduce

I observe this issue for two days after upgrade from v2023.9.0-beta7 to v2023.9.0-beta9.

### Which version are you running?

v2023.9.0-beta9

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-5.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12520280/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-5.txt)

**Comment by gatonero** [comment]
I did the same with v2023.9.0-beta10 and the values are nearly identical. Try **v2023.9.0-beta10**.

**Comment by andreid1303** [comment]
For there were identical in v2023.9.0-beta7 and earlier. As described in beta 10 it does not have any fixes. 
It seems OW bucket is increasing while My sensors's is decreasing over time of the day. Strange.
![Снимок экрана 2023-09-05 в 16 34 45](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/58367592/664890cf-a79e-4705-96f1-2fee284fcd9d)

**Comment by jeroenterheerdt** [comment]
Of course if you don't call update before calling calculate you get an error.

**Comment by andreid1303** [comment]
But it wasn't so before! I see now this behaviour is described in the end of Wiki.   But, If calculation always require updating why just call it automatically in backend?

I tested calculation recently and got this:
![Снимок экрана 2023-09-05 в 19 42 19](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/58367592/7f7220c0-557d-4b52-93d3-9c724b9d2258)

**Comment by jeroenterheerdt** [comment]
A manual update should not be required. However, all collected weatherdata on a sensor group is removed once you calculate a zone that uses that sensor group. So if you do a first calculate that will work but will wipe all collected weatherdata. So second calculate fails unless enough time has expired for an auto update to come in or you called update manually.

**Comment by jeroenterheerdt** [comment]
both statements above are correct. bucket is not reset unless you change the value yourself or irrigate. And each calculation only takes into account weather data collected since previous calculation _for that sensor group_.

**Comment by andreid1303** [comment]
Wonderfull. That way, for my sensors group,  I can call update just before irrigation, no autoupdate is necessary, and reset bucket after as usual.
It just did not work as it should in previous betas.

**Comment by jeroenterheerdt** [comment]
> Wonderfull. That way, for my sensors group, I can call update just before irrigation, no autoupdate is necessary, and reset bucket after as usual. It just did not work as it should in previous betas.

not sure I follow this. If you calculate without ever doing an update (either manual or auto) the calculate _will_ fail as there is nothing to calculate with. You should call update at least once (manually or automatically) before each calculate.
