### ISSUE TITLE
Output not updating

### ISSUE THREAD

**Issue by jlrosssc** [jeroenterheerdt/HAsmartirrigation#241]
I installed the original version recently and was getting familiar with how it worked before creating automations with the sensor.  Then I saw the V2 beta with the awesome feature of multiple zones.  I installed it using the same input sensors I had on the original version.  These primarily come from my home weather station with a few sensors like barometric pressure coming from other sources.  I'm not clear that this is working, however.  I have 2 zones set up but show no apparent changes after 2 days of hot, dry weather when monitoring sensor.default_zone_1 and _2.  Is this where the output should show?  When I select the i icon for each zone, it says none, which I'm interpreting as no calculations have been made.  Am I looking the in the wrong place for the output?

_Originally posted by @jlrosssc in https://github.com/jeroenterheerdt/HAsmartirrigation/discussions/239_

**Comment by jlrosssc** [comment]
<img width="657" alt="Screenshot 2023-09-05 at 9 19 50 PM" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/132500156/78597b37-49c1-40c3-84b1-af4e0d025701">
<img width="728" alt="Screenshot 2023-09-05 at 9 20 15 PM" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/132500156/88220f01-277d-42d1-95a4-2b80d4ae6838">

<img width="692" alt="Screenshot 2023-09-05 at 9 20 44 PM" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/132500156/1838877b-be7b-46ca-b6d6-37d5c786d0a7">

**Comment by jeroenterheerdt** [comment]
see my response in the discussion, although it should really belong here.

**Comment by jeroenterheerdt** [comment]
Open an issue using the template. Be sure to add a diagnostics file
