### ISSUE TITLE
Failed to set up error.

### ISSUE THREAD

**Issue by jlrosssc** [jeroenterheerdt/HAsmartirrigation#244]
### What happened?

I was using the 0.8x version using my home weather station with no issues.  I installed to 2.0 Beta with home sensors and could not get it to calculate although it appeared to install correctly and had the Smart Irrigation side panel.  I deleted that and installed using Open Weather.  It accepts the API and then shows an error.  I upgraded HA to 2023.9.0 and it made no differenceThe logs are below.  There is no diagnostic file.

<img width="758" alt="Screenshot 2023-09-06 at 7 00 35 PM" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/132500156/aaddcc65-892f-4aaf-9771-a9aab0fc1fd9">

### How to reproduce

With each install attempt.

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/smart_irrigation/store.py:534 
Integration: Smart Irrigation (documentation, issues) 
First occurred: 6:20:03 PM (1 occurrences) 
Last logged: 6:20:03 PM

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 62, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 534, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
voluptuous.error.MultipleInvalid: expected int for dictionary value @ data['forecast_days']
```

### Which version are you running?

HA 2023.9.0.  Smart Irrigation 2.0 Beta

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
thanks, this is weird. you should have that diagnostic file option there. without I cannot be of much help.

**Comment by dlindnegm** [comment]
Pretty sure I saw this at some point when performing multiple uninstall/reinstalls.  I think these are the steps I took to resolve it:
1) Uninstall the Integration from the HA - Devices - Integrations if it's there.
2) Remove the Integration from HACS if that's how you installed it.
3) Restart HA and close your browser while it's restarting.
4) Launch a new browser instance and log back into HA after the restart.
5) Manually delete the file smart_irrigation.storage from the \config\.storage folder
6) Restart HA again
7) Confirm that the smart_irrigation.storage file does not exist.
8) Download and install Smart Irrigation again from HACS.
9) Restart HA and close the browser while it's restarting.
10) Launch a new browser and log back into HA.
11) Install the Smart Integration from HA - Devices - Integrations.

I don't think this is necessarily an issue with the Smart Irrigation integration.  It seems that HA caches a lot of stuff that sometimes requires closing the browser and re-launching.  And more than a few times after I uninstalled and re-installed everything I found that all of my Smart Irrigation sensors showed up again even without setting them up.  So I believe that HA has cached copies of the smart_irrigation.storage file that sometimes get restored, but I don't know where they reside.

**Comment by jeroenterheerdt** [comment]
Thanks, please try this procedure first. If that does not help I'd need to see the storage file.

**Comment by jlrosssc** [comment]
I actually just completed the recommended steps prior to seeing the reply and it did work. I think some cached info in .storage was the issue. It’s installed and working now!Sent from my iPhoneOn Sep 7, 2023, at 9:40 AM, Jeroen ter Heerdt ***@***.***> wrote:﻿
Thanks, please try this procedure first. If that does not help I'd need to see the storage file.

**Comment by jeroenterheerdt** [comment]
Great, happy to hear that!
