### ISSUE TITLE
Calculations are not correct? by design?

### ISSUE THREAD

**Issue by andreid1303** [jeroenterheerdt/HAsmartirrigation#245]
### What happened?

At 18:00 I called Update All Zones, Calculate All Zones and got buckets -5,0 mm for OW zone and -5,1 mm for MySensors. Then "Irrigate" 5 mm and Reset All Buckets.

Now I've wish "Irrigate" again but only ETO past two hours, did same Update, Calculate and got - 2,7 mm for OW and 5,0 mm for MySensors. First, evidently this is not past 2 hours ETO, and second why such difference between OW and MySensors this time?

### How to reproduce

See above.

### Which version are you running?

v2023.9.0-beta10

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-6.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12552584/config_entry-smart_irrigation-6e18a9ad38f8ac00ef4285672ad17839.json-6.txt)

**Comment by jeroenterheerdt** [comment]
how are we doing with this @andreid1303 ? any feedback?

**Comment by andreid1303** [comment]
Sorry, I lost.
