### ISSUE TITLE
Zones tab not showing zones

### ISSUE THREAD

**Issue by jonathanjmakela** [jeroenterheerdt/HAsmartirrigation#253]
### What happened?

Upon initial set up, when adding a new zone via "Add zone" on the "Zones" tab, any new zones do not show up on this tab. Going to the "Smart Irrigation" integration page (under "Settings") shows the new zones added as new entities. When I then return to the "Zones" tab, no zones are shown (not even the initial 2 "Default Zones").

Also, cannot delete zones from the entities listing.

### How to reproduce

Fresh install of v2023.9.0-beta14. Add a new zone and click "add zone".

Same behavior in v2023.9.0-beta13

### Which version are you running?

v2023.9.0-beta14

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-f6f8384f8edf7dddf4b0745666ef5244.json-2.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12568337/config_entry-smart_irrigation-f6f8384f8edf7dddf4b0745666ef5244.json-2.txt)

**Comment by jonathanjmakela** [comment]
Interestingly, they show up in the mobile companion app for Home Assistant, but still not in the web interface.

**Comment by jeroenterheerdt** [comment]
Likely a browser cache problem. Clear cache or use a different browser

**Comment by jonathanjmakela** [comment]
Yup. That solved the problem. Thank you!

**Comment by jonathanjmakela** [comment]
Closed
