### ISSUE TITLE
[REQ] Beta14 - Global Prefix for Group Entities

### ISSUE THREAD

**Issue by Detmud** [jeroenterheerdt/HAsmartirrigation#258]
I sort my Entities by name

eg.: sensor.garden_smart_irrigation_zone_1

Therefore a Global Prefix like: garden_smart_irrigation in Global Options would be highly appriciated.

**Comment by jeroenterheerdt** [comment]
That makes sense. Would just `smart_irrigation` work or would you need to be able to configure it?

**Comment by Detmud** [comment]
I think smart_irrigation is good enough. But make it optional then. Otherwise people can't adopt it to their needs.

**Comment by jeroenterheerdt** [comment]
added in beta16. Please confirm.

**Comment by Detmud** [comment]
Works like a charm. Thank you very much.
