### ISSUE TITLE
Clarify pressure is absolute pressure

### ISSUE THREAD

**Issue by Detmud** [jeroenterheerdt/HAsmartirrigation#259]
Under Sensor the Sensor Pressure is misleading.

Is this Absolute Pressure or Relative Pressure ?
https://ambientweather.com/faqs/question/view/id/1591/#:~:text=Absolute%20pressure%20is%20the%20measured,relative%20to%20sea-level).

Would be great to Clearify this.

**Comment by jeroenterheerdt** [comment]
I believe it's absolute, I have never heard of relative pressure.

**Comment by jeroenterheerdt** [comment]
yeah, it looks like PyETO (the library the integration uses) corrects for this: https://pyeto.readthedocs.io/en/latest/api.html#atmospheric-pressure

**Comment by Detmud** [comment]
Ähh so it's relativ pressure, makes sense

**Comment by jeroenterheerdt** [comment]
> Ähh so it's relativ pressure, makes sense
If so say so.

**Comment by jeroenterheerdt** [comment]
@gatonero something to document

**Comment by Detmud** [comment]
Hello,

so am going deep into this to clearify it. In pyeto the Formular is referenz as Equation 7 page 62 in allen et al 1998.  
It is Page 31 but whatever. 

`The atmospheric pressure, P, is the pressure exerted by the weight of the earth's atmosphere. 
Evaporation at high altitudes is promoted due to low atmospheric pressure as expressed in the 
psychrometric constant. The effect is, however, small and in the calculation procedures, the 
average value for a location is sufficient.`

So in this case we are talking about Atmospheric pressure (P) which is 1013,25 hpa at sealevel and gets less with altitute. If your *relative* pressure is above that its considert high pressure,  below that is low pressure. 

But it is the *Absolute Pressure* or *Barometric Pressure* or "Atmospheric Pressure" the formulare needs. So no adjustment to sealevel.

**Comment by jeroenterheerdt** [comment]
> Hello,
> 
> so am going deep into this to clearify it. In pyeto the Formular is referenz as Equation 7 page 62 in allen et al 1998. It is Page 31 but whatever.
> 
> `The atmospheric pressure, P, is the pressure exerted by the weight of the earth's atmosphere. Evaporation at high altitudes is promoted due to low atmospheric pressure as expressed in the psychrometric constant. The effect is, however, small and in the calculation procedures, the average value for a location is sufficient.`
> 
> So in this case we are talking about Atmospheric pressure (P) which is 1013,25 hpa at sealevel and gets less with altitute.
> 
> If your _relative_ pressure is above that its considert high pressure, below that is low pressure.
> 
> But it is the _Absolute Pressure_ or _Barometric Pressure_ or "Atmospheric Pressure" the formulare needs. So no adjustment to sealevel.

So.. It needs abs pressure but it looks like it corrects it. I am not sure but I believe weatherstations provide relative normally?

**Comment by Detmud** [comment]
Well because relative needs your height above sea level it's needs to be calculated you can't measure it. Absolute is measured.

**Comment by jeroenterheerdt** [comment]
> Well because relative needs your height above sea level it's needs to be calculated you can't measure it. Absolute is measured.

ok, well, the integrations' code does not do any conversion explicitly, so I am not sure it happens inside the pyeto module itself. If relative cannot be measured then I'd assume weather stations provide absolute?

The code passes in the pressure you provide here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/dcffcb1ba72f9194a1e2e9bdb200412cc214d3fc/custom_components/smart_irrigation/calcmodules/pyeto/__init__.py#L136. It's not use anywhere else. The function it is passed into is here in the PyETO library: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/dcffcb1ba72f9194a1e2e9bdb200412cc214d3fc/custom_components/smart_irrigation/calcmodules/pyeto/pyeto/fao.py#L502, but that doesn't tell me if its expecting absolute or relative pressure. It does however, mention that you can calculate pressure using https://github.com/jeroenterheerdt/HAsmartirrigation/blob/dcffcb1ba72f9194a1e2e9bdb200412cc214d3fc/custom_components/smart_irrigation/calcmodules/pyeto/pyeto/fao.py#L29 which takes altitude as a parameter so that leads me to believe we need to convert the absolute pressure into relative pressure?

Loads of guessing going on here. What do you think?

**Comment by Detmud** [comment]
HEy,

sooo you are thinking the same way, i looked at it also came to the same question 
    def atm_pressure(altitude): 

>which takes altitude as a parameter so that leads me to believe we need to convert the absolute pressure into relative pressure?

so that what i thought first too. But check
https://pyeto.readthedocs.io/en/latest/_modules/pyeto/fao.html#atm_pressure

    Calculated using a simplification of the ideal gas law, assuming 20 degrees
    Celsius for a standard atmosphere. Based on equation 7, page 62 in Allen
    et al (1998).


So i went over to Researchgate and went directly to the source.
https://www.researchgate.net/publication/290988983_Crop_evapotranspiration_guidelines_for_computing_crop_requirements_FAO_Irrig_Drain_Report_modeling_and_application

(see my quote above directly from the paper, the page in the documentation is wrong. its 31 not 62 if you want to look yourself.

If you want to understand what the formulare

    tmp = (293.0 - (0.0065 * altitude)) / 293.0
    return math.pow(tmp, 5.26) * 101.3`

is doing have a look at page 213 of the paper, you will see a table that gives you forevery 50m of hight above sealevel the Athmosperic (absolute) pressure. 

So i first thought they adjusting to sealevel, nope. They are jusing the normal absolute Pressure a Barometer gives you or a normal weather station gives you. 

As I said my comment with "Ähh so it's relativ pressure, makes sense" was totally wrong its absolute Pressure you were right.

But nevertheless, as an idea, if you can geht the height above sealevel from Home Assistant somehow you can just calculate that value and no one need to prove that. so a sensor is optinal if you know the height above sealevel.

**Comment by jeroenterheerdt** [comment]
so we already get teh height above sealevel from HA. We need it for other parts of the calc.
I don't understand how us having that would remove the need to have a sensor input for pressure?
I don't like all this estimation and would rather provide the actual value, hence you need to specify pressure (or let us read it from OWM if you don't have the sensor).

All of this leads me to believe this is the right thing to do, but we should clarify that this is an absolute pressure we're expecting.

**Comment by Detmud** [comment]
Agree, totally.

Maybe I was unclear, in ways of Preferation

1.) Your own local sensor
2.) OWM
3.) Estimate from the height above sealevel. 

But a as statet in opening the ticket, just "pressure" is confusing for people who have a weatherstation that give booth, absolute and relative.

**Comment by jeroenterheerdt** [comment]
so, let's clarify in documentation that we expect absolute pressure.

**Comment by gatonero** [comment]
Where does the absolute pressure from OWM comes from?

**Comment by jeroenterheerdt** [comment]
That's a good question. Let's check what the one all api provides.

**Comment by jeroenterheerdt** [comment]
so the[ onecall api ](https://openweathermap.org/api/one-call-api) provides: ` Atmospheric pressure on the sea level, hPa` - now whether that is relative or absolute pressure, that's another question. @Detmud as you seem to have a better handle on this, what do you think that that means?

**Comment by gatonero** [comment]
The atmospheric pressure on the sea level is the relative pressure. What you measure at your place is the absolute pressure. It depends at what level you get the measurement. To make it comparable to other stations it's calculated to the sea level.

The mean sea-level pressure (MSLP) is the atmospheric pressure at mean sea level. This is the atmospheric pressure normally given in weather reports on radio, television, and newspapers or on the Internet. https://en.wikipedia.org/wiki/Atmospheric_pressure

**Comment by jeroenterheerdt** [comment]
ok... but in our discussion so far it looked like what pyeto wanted was the absolute pressure. so are we saying when you have a sensor we measure absolute pressure so we don't need to convert it but when we're getting it from OWM we're getting relative so need to convert it into absolute?

**Comment by gatonero** [comment]
As I understand PyET0 uses absolute pressure and altitude to calculate atmospheric pressure, which is relative pressure. 

see https://github.com/woodcrafty/PyETo/blob/master/pyeto/fao.py#L29

```

def atm_pressure(altitude):
    """
    Estimate atmospheric pressure from altitude.

    Calculated using a simplification of the ideal gas law, assuming 20 degrees
    Celsius for a standard atmosphere. Based on equation 7, page 62 in Allen
    et al (1998).

    :param altitude: Elevation/altitude above sea level [m]
    :return: atmospheric pressure [kPa]
    :rtype: float
    """
    tmp = (293.0 - (0.0065 * altitude)) / 293.0
    return math.pow(tmp, 5.26) * 101.3
``` 

If that's true OWM pressure first must be converted to an absolute value. What a pain! 
The more complicated formula is 

Air pressure at target altitude = Air pressure at current altitude * (1-temperature gradient*altitude difference/temperature at current altitude in Kelvin)^(0.03416/temperature gradient)

see https://rechneronline.de/barometer/hoehe.php

A less precise but simpler calculation can be made using the international height formula. 

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/db1ec55d-4d25-4463-9fd5-d4be395cd065)

See https://de.wikipedia.org/wiki/Barometrische_H%C3%B6henformel#Internationale_H%C3%B6henformel and https://rechneronline.de/physik/luftdruck-hoehe.php

In both cases the altitude is needed

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/a412e2bb-6c8f-4d4d-aa30-7cb1cfd78410)

**Comment by jeroenterheerdt** [comment]
> As I understand PyET0 uses absolute pressure and altitude to calculate atmospheric pressure, which is relative pressure.
> 
> see https://github.com/woodcrafty/PyETo/blob/master/pyeto/fao.py#L29
> 
> ```
> 
> def atm_pressure(altitude):
>     """
>     Estimate atmospheric pressure from altitude.
> 
>     Calculated using a simplification of the ideal gas law, assuming 20 degrees
>     Celsius for a standard atmosphere. Based on equation 7, page 62 in Allen
>     et al (1998).
> 
>     :param altitude: Elevation/altitude above sea level [m]
>     :return: atmospheric pressure [kPa]
>     :rtype: float
>     """
>     tmp = (293.0 - (0.0065 * altitude)) / 293.0
>     return math.pow(tmp, 5.26) * 101.3
> ```
> 
> If that's true OWM pressure first must be converted to an absolute value. What a pain! The more complicated formula is
> 
> Air pressure at target altitude = Air pressure at current altitude * (1-temperature gradient*altitude difference/temperature at current altitude in Kelvin)^(0.03416/temperature gradient)
> 
> see https://rechneronline.de/barometer/hoehe.php
> 
> A less precise but simpler calculation can be made using the international height formula.
> 
> ![image](https://user-images.githubusercontent.com/8248255/268103181-db1ec55d-4d25-4463-9fd5-d4be395cd065.png)
> 
> See https://de.wikipedia.org/wiki/Barometrische_H%C3%B6henformel#Internationale_H%C3%B6henformel and https://rechneronline.de/physik/luftdruck-hoehe.php
> 
> In both cases the altitude is needed
> 
> ![image](https://user-images.githubusercontent.com/8248255/268104857-a412e2bb-6c8f-4d4d-aa30-7cb1cfd78410.png)

we already have the height, so we can convert the OWM pressure to absolute, but I'd like to use the most precise one that is good enough. This one seems doable:
`Air pressure at target altitude = Air pressure at current altitude * (1-temperature gradient*altitude difference/temperature at current altitude in Kelvin)^(0.03416/temperature gradient)`

but what is a temperature gradient?

**Comment by gatonero** [comment]
That seems completely plausible to me. 

The temperature gradient indicates how quickly the temperature falls with altitude. A good estimate in normal weather is 0.0065°C/meter.
Temperature gradient = (temperature at current altitude - temperature at target altitude) / altitude difference

But because nobody normally knows what's the temperature at current temperature (in this case at sea level)  we have to use the more simple international height formula.

So every time we have OWM we have to convert. If there is an own sensor used we need an option wether it's absolute or relative.

Remember it's <sup>5,255<sup> 

Luftdruck = 1013,25 hPa * [ 1 − 6,5 * Höhe / (288150 m) ]<sup>5,255</sup>

**Comment by jeroenterheerdt** [comment]
OK, thanks, I will try to add that in today

**Comment by jeroenterheerdt** [comment]
this is not working... what am I doing wrong here? 
`1013.25 * math.pow(1-6.5 * self.hass.config.as_dict().get(CONF_ELEVATION) / (288150.0),5225.0)`

this returns `1013.25` for evelation = 0, but for elevation 51 it returns `2.4` (it should return `1007.14`).

**Comment by jeroenterheerdt** [comment]
so let's test beta19 and if it works as expected, please update the docs again to say that people can choose in their sensor group if their sensor returns relative or absolute pressure @gatonero

**Comment by gatonero** [comment]
I see the option. With both settings I'm getting identical results. So I guess it works. Great job! I will update the documentation.
