### ISSUE TITLE
[REQ] Split required watering time into smaller times

### ISSUE THREAD

**Issue by jlrosssc** [jeroenterheerdt/HAsmartirrigation#261]
Feature request to allow required watering time to be broken up into smaller times with a soak time in between. For example, if 60 minutes of watering time is required, allow it to be in groups <= 15 minutes (user-defined max time per segment) with a 15 minute (user-defined soak time if more than 1 segment) in between rather than 1 long 60 minute run time causing runoff.

**Comment by jeroenterheerdt** [comment]
> Feature request to allow required watering time to be broken up into smaller times with a soak time in between. For example, if 60 minutes of watering time is required, allow it to be in groups <= 15 minutes (user-defined max time per segment) with a 15 minute (user-defined soak time if more than 1 segment) in between rather than 1 long 60 minute run time causing runoff.

Interesting. But not sure if that is in scope for this integration. You can solve this in an automation or using irrigation unlimited I think.
