### ISSUE TITLE
Do sensor entities get renamed? 

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#262]
### What happened?

See title 

### How to reproduce

See title

### Which version are you running?

Beta

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
no, but won't fix

**Comment by gatonero** [comment]
@jeroenterheerdt please mention me if it changes. I updated README from sensor.[zone_name] to sensor.smart_irrigation_[zone_name] today.
