### ISSUE TITLE
Decouple Clearing of Weather Date When Calculating 

### ISSUE THREAD

**Issue by dlindnegm** [jeroenterheerdt/HAsmartirrigation#267]
Does it make sense to eliminate the clearing of all weather data points when a calculation is performed?  You now have button options and services to update and calculate all zones, and to reset all buckets and clear all weather data.  The issue is that if I click the button to calculate a single zone it also clears all weather data.  The buttons for update and calculate on each zone imply that you're performing that action on just that zone, when in fact an update applies to all zones, and a calculate clears the weather data for all zones.  What I'm missing is the ability to test the effect of different multipliers or different sensor groups on the resulting runtimes.  Once I perform a calculate I've just lost all weather data up to that point, so you really need to set it and forget it for a full day which doesn't allow any testing through the day.

**Comment by jeroenterheerdt** [comment]
well, not really. You lose the weather data for the sensor group that the zone that you calculated uses. I think it's the right behavior when you are not debugging the set up. Yes, it's a bit annoying during debugging, but once it runs I think this is the right behavior. If we decoupled it there is another step people will have to do manually or in an automation and we already have two which is very complicated to folks: calculate and reset bucket. Adding another step to this (clearing weatherdata) is not helping.

**Comment by dlindnegm** [comment]
"You lose the weather data for the sensor group that the zone that you calculated uses."

Makes sense.  I can change the sensor group for the zones I don't want to drop their data.  And create multiple sensor groups as needed.
