### ISSUE TITLE
Are we ready to release V2?

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#269]
### What happened?

As a valued and active member of the users of Smart Irrigation, please vote (see below) on whether you think we're ready to release V2 to the general public.

### How to reproduce

Leave your vote using the reactions

### Which version are you running?

v2023.9.0-beta18

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
@gatonero @detmud @andreid1303, @diyanei @dlindnegm, @apocaliss92: please vote! Voting expires in 1 week from now.

**Comment by jeroenterheerdt** [comment]
@gatonero are you back? We need to work on the docs before releasing 😊

**Comment by gatonero** [comment]
I know. I just started.

**Comment by jeroenterheerdt** [comment]
You are amazing!

**Comment by gatonero** [comment]
We should define a bug list on which it depends whether v2.0 should be released.

**Comment by jeroenterheerdt** [comment]
well yeah, you're right. I will add tags to v2 bugs that are blocking.

**Comment by jeroenterheerdt** [comment]
Take a look here at the open issue for V2:
https://github.com/jeroenterheerdt/HAsmartirrigation/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v2.0-beta+%282023.X.X-beta%29%22

Also, here's the "list" of 1 items that is release blocking:
https://github.com/jeroenterheerdt/HAsmartirrigation/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v2.0-beta+%282023.X.X-beta%29%22+label%3Arelease-blocker

**Comment by jeroenterheerdt** [comment]
So it looks like we can release v2!! I will make the pr and release it. We should also update the wiki to move stuff around so v1 stuff gets moved to an archive and people get the v2 stuff by default

**Comment by gatonero** [comment]
Let's do it!
