### ISSUE TITLE
Auto calculation doesn't update event trigger time

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#271]
### What happened?

When auto calculation is enabled it should update event trigger time but it doesn't call async_update_zone_config or register_start_event anywhere.

### How to reproduce

Watch logs while auto calc in enabled.

[config_entry-smart_irrigation-43106bb5c08f0ae73bca6bc2e9ba24ea.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12616007/config_entry-smart_irrigation-43106bb5c08f0ae73bca6bc2e9ba24ea.json.txt)

### Which version are you running?

beta18

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
I believe it does: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/178159c7576d659e08d164a4f298c07b67ffaea5/custom_components/smart_irrigation/__init__.py#L870

**Comment by omenek159** [comment]
Yes, async_update_config calls register_start_event, but _async_calculate_all doesn't. AFAIK this function is called at time specified in config. Try to set auto calc time in one minute and then watch logs. 
It shows `2023-09-15 07:32:00.257 INFO (MainThread) [custom_components.smart_irrigation] Calculating all automatic zones`, but nothing about creating new event.

**Comment by jeroenterheerdt** [comment]
> Yes, async_update_config calls register_start_event, but _async_calculate_all doesn't. AFAIK this function is called at time specified in config. Try to set auto calc time in one minute and then watch logs. It shows `2023-09-15 07:32:00.257 INFO (MainThread) [custom_components.smart_irrigation] Calculating all automatic zones`, but nothing about creating new event.

yeah, you're right. I have added that in a new beta that I am about to wrap up. Please install and try/confirm.

**Comment by omenek159** [comment]
Well, unfortunately I can't install beta19, because on Hass OS it crashes while installing pvlib's dependencies. I manually added line 531 and report back tomorow.

**Comment by jeroenterheerdt** [comment]
> Well, unfortunately I can't install beta19, because on Hass OS it crashes while installing pvlib's dependencies. I manually added line 531 and report back tomorow.

yeah, I noticed. I am fixing that issue.

**Comment by jeroenterheerdt** [comment]
Looks like the new beta 19 fixes this issue

**Comment by omenek159** [comment]
Working now.

**Comment by jeroenterheerdt** [comment]
So what works? Installation? Or did the event trigger normally? Which version are you on?

**Comment by omenek159** [comment]
Haha I forgot about pvlib. Yeah, it installed successfully and event is recalculating.
There was also problem with multiple events fired, but it's discussed in another thread.
