### ISSUE TITLE
Newly added zones overwrite existing zones.

### ISSUE THREAD

**Issue by mauritsivs** [jeroenterheerdt/HAsmartirrigation#273]
### What happened?

Whenever i try to add a zone, it overwrites the existing (top displayed) zone (with Id=2).

i started with using version 0.8.something, replaced with 2.0.beta.something.

After installing via HACS and then via integrations, sidebar appears with 2 pre-defined zones. 
Deleted the pre-defined zones and tried to add multiple new zones. now only two can be added, first one is there, second zone gets replaced every time i add a next one.

[config_entry-smart_irrigation-e4ed53837bb8aafecd925b57b01db47d.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12673422/config_entry-smart_irrigation-e4ed53837bb8aafecd925b57b01db47d.json.txt)

### How to reproduce

Smart irrigation side menu -> zones -> add zones, fill in values, click add zone. -> existing zone overwritten.

### Relevant log output

```shell
cant find any
```

### Which version are you running?

beta21

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

i started with using version 0.8.something, replaced with 2.0.beta.something.

After installing via HACS and then via integrations, sidebar appears with 2 pre-defined zones. 
Deleted the pre-defined zones and tried to add multiple new zones. now only two can be added, first one is there, second zone gets replaced every time i add a next one.

deleted entire integration and redownloaded newest beta in HACS, but old zone setup reappears after reinstalling integration

**Comment by jeroenterheerdt** [comment]
thanks, it looks like you're hitting a bug with older versions of 2.0. Please uninstall the integration, manually remove the `smart_irrigation.storage` file from the `.storage` folder, reboot HA and install. Please let me know if this resolves the issue. Sorry for the lengthly workaround.

**Comment by mauritsivs** [comment]
i have completely reinstalled using beta21, looks like it works now. must have been some leftovers from previous installs that were interfering
