### ISSUE TITLE
Update IT translations for 2.0 release

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#274]
### What happened?
@valerix85
Translation for `/custom_components/smart_irrigation/frontend/localize/languages` forr "Automatic weather data pruning". There also some descriptions for the other fields which need translation.

### How to reproduce

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/18aa10fb-6cbf-45a8-8b03-9ebb85ce628c)

### Which version are you running?

 v2023.9.0-beta22

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
@valerix85 Please update language files in `translations\` and `frontend\localize\languages\` and make sure it includes all the elements from the EN language file.

**Comment by valerix85** [comment]
Sure, I will do this evening.

**Comment by gatonero** [comment]
There are also some missing translations additionaly.

Line 101

```
            "pressure_types": {
            "absolute": "absolute",
            "relative": "relative"
          },
          "pressure-type": "Pressure is",

```

Line 174

`        "clear-all-weatherdata": "Clear all weatherdata"
`
Line 197

```
        "last_calculated": "Last calculated",
        "data-last-updated": "Data last updated",
        "data-number-of-data-points": "Number of data points"
```

**Comment by valerix85** [comment]
I noticed that the original files have changed, I will update the translation

**Comment by valerix85** [comment]
made the commit

**Comment by jeroenterheerdt** [comment]
> made the commit

great, can you make a PR then?

**Comment by valerix85** [comment]
Sure! PR done 😁
