### ISSUE TITLE
Update FR translations for 2.0 release

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#276]
### What happened?

 @diyanei
Translation for /custom_components/smart_irrigation/frontend/localize/languages forr "Automatic weather data pruning". There also some descriptions for the other fields which need translation.

### How to reproduce

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/e0ea05d4-6f72-4435-94b3-f5f9f43575fd)

### Which version are you running?

v2023.9.0-beta22

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
@diyanei Please update language files in `translations\` and `frontend\localize\languages\` and make sure it includes all the elements from the EN language file.

**Comment by gatonero** [comment]
There are also some missing translations additionaly.

Line 101

```
            "pressure_types": {
            "absolute": "absolute",
            "relative": "relative"
          },
          "pressure-type": "Pressure is",

```

Line 174

`        "clear-all-weatherdata": "Clear all weatherdata"
`
Line 197

```
        "last_calculated": "Last calculated",
        "data-last-updated": "Data last updated",
        "data-number-of-data-points": "Number of data points"
```

**Comment by diyanei** [comment]
Got it, I will complete it on monday.
