### ISSUE TITLE
Update ES translations for 2.0 release

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#277]
### What happened?

@arivelli
Translation for /custom_components/smart_irrigation/frontend/localize/languages forr "Automatic weather data pruning". There also some descriptions for the other fields which need translation.

### How to reproduce

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/b82b07a1-2856-465f-a11f-417cd206674e)

### Which version are you running?

 v2023.9.0-beta22

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Please update language files in `translations\` and `frontend\localize\languages\` and make sure it includes all the elements from the EN language file.

**Comment by gatonero** [comment]
There are also some missing translations additionaly.

Line 101

```
            "pressure_types": {
            "absolute": "absolute",
            "relative": "relative"
          },
          "pressure-type": "Pressure is",

```

Line 174

`        "clear-all-weatherdata": "Clear all weatherdata"
`
Line 197

```
        "last_calculated": "Last calculated",
        "data-last-updated": "Data last updated",
        "data-number-of-data-points": "Number of data points"
```
