### ISSUE TITLE
Wrong language file in  v2023.9.0-beta23

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#279]
### What happened?

I expected the new german translations for i.e "automatic clear" in `/frontend/localize/languages/de.json` but I didn't find it. Also all translated descripitions are missing. This file is ten lines shorter than the translation I made.

[de.tar.gz](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12703858/de.tar.gz)

### How to reproduce

Compare the files.

### Which version are you running?

 v2023.9.0-beta23

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
huh?

**Comment by jeroenterheerdt** [comment]
so with this last commit is the language file correct now?

**Comment by gatonero** [comment]
I just pushed the new translation again. At line 41 there should be 

```
        "automatic-clear": {
          "header": "Automatisches Löschen der Wetterdaten",
          "description": "Gesammelte Wetterdaten zu einem bestimmten Zeitpunkt automatisch entfernen. Damit wird sicher gestellt, dass keine Wetterdaten von vergangenen Tagen übrig bleiben. Entferne die Wetterdaten nicht vor der Berechnung und verwende diese Option nur, wenn Sie erwarten, dass das automatische Update Wetterdaten erfasst hat, nachdem der Tag berechnet wurde. Idealerweise sollte dieser Schnitt so spät wie möglich Tag durchgeführt werden.",
          "labels": {
            "automatic-clear-enabled": "Automatisches Löschen der Wetterdaten",
            "automatic-clear-time": "Löschen der Wetterdaten um"
          }
        }

```

**Comment by jeroenterheerdt** [comment]
updated the release, please re-update / reinstlal

**Comment by gatonero** [comment]
Now is the correct file in that version.

But like some weeks ago, I don't see the changes also I restarted HA, rebooted the system, refreshed the browser cache, tried a different browser (Firefox, Vivaldi, Android) . This might be special for my system. Have a look at your system.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5a113782-05a0-451e-bf45-18c4a8dbceae)

**Comment by jeroenterheerdt** [comment]
but you are seeing the latest version of the code (you need to click on the [i] icon to see the description of the options on general). I guess the translation file is just cached somewhere. Time will fix this (it did the last time)

**Comment by gatonero** [comment]
Hope so!

**Comment by gatonero** [comment]
I just saw that there are some additional translations missing. I will add those in the corresponding update translation bugs

Line 101
```
            "pressure_types": {
            "absolute": "absolute",
            "relative": "relative"
          },
          "pressure-type": "Pressure is",

```

Line 174
`        "clear-all-weatherdata": "Clear all weatherdata"
`
Line 197
```
        "last_calculated": "Last calculated",
        "data-last-updated": "Data last updated",
        "data-number-of-data-points": "Number of data points"


```

**Comment by gatonero** [comment]
@jeroenterheerdt 
When pushing translations I get errors from hassfest. It seems to me that these errors are not originated by my translations but somewhere else. https://github.com/jeroenterheerdt/HAsmartirrigation/actions/runs/6279217410

Maybe that's the reason I don't see new translations?

**Comment by jeroenterheerdt** [comment]
> @jeroenterheerdt When pushing translations I get errors from hassfest. It seems to me that these errors are not originated by my translations but somewhere else.
> 
> 1. https://github.com/jeroenterheerdt/HAsmartirrigation/actions/runs/6279217410
> 2. https://github.com/jeroenterheerdt/HAsmartirrigation/actions/runs/6279217408/job/17054489755#step:5:37
> 
> Maybe that's the reason I don't see new translations?

No, these as just broken tests that only work for v1.

**Comment by gatonero** [comment]
It happened again! Updating to v2023.9.1 brought all the new translations. :-)
