### ISSUE TITLE
Missing labels in Configuration Setup

### ISSUE THREAD

**Issue by freddyf** [jeroenterheerdt/HAsmartirrigation#28]
After selecting Smart Irrigation from Home Assistant Integration list the windows do not have labels

- Home Assistant->Configratin->Integrations->Setup new integration
- Choosing Smart Irrigation

The Configuration Windows hasn't any labels
1) first window misses Name, API Key for Open Weather Map
![immagine](https://user-images.githubusercontent.com/1830630/83337329-a095a580-a2ba-11ea-89f4-8e4ef47a0bc3.png)
2)
![immagine](https://user-images.githubusercontent.com/1830630/83337352-f4a08a00-a2ba-11ea-8ca3-d26cc7acb01a.png)
3)
![immagine](https://user-images.githubusercontent.com/1830630/83337406-46491480-a2bb-11ea-993e-e89d6b1dd77e.png)

-----
Home Assistant on a Docker (OpenMediaVault Nas)
Home Assistant 0.108.6

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.19.0-0.bpo.8-amd64
python_version | 3.7.7
timezone | Europe/Rome
version | 0.108.6
virtualenv | false

**Comment by jeroenterheerdt** [comment]
That is strange. What language do you run HA in?

**Comment by freddyf** [comment]
English, but i have the same issue if i switch to Italian

**Comment by jeroenterheerdt** [comment]
Weird. I run it in English as well, no issues here. Have you tried removing, rebooting, reinstalling?

**Comment by posixx** [comment]
this is due the translations folder change. older versions use ".translations" as foldername, this was change recently to "translations". Maybe possible to add a symlink?

**Comment by jeroenterheerdt** [comment]
@freddyf can you confirm this can be closed?
