### ISSUE TITLE
All internal links of README.md point to /hacs/entry

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#284]
### What happened?

Clicking a link in README.md in the installation open /hacs/entry

### How to reproduce

Click an internal link in README.md

### Which version are you running?

v2023.9.1

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
Now the links are screwed upI have to fiddle around with it.

**Comment by gatonero** [comment]
The links arn't screwed up, there is still on older version of README.md active. Internal Links should look like [See the example automation](https://github.com/jeroenterheerdt/HAsmartirrigation#operation-modes) but they are still like  [Example automation](#step-4-creating-automations)
I will update this file, there was an other issue, hopefully links get fixe by that.

**Comment by jeroenterheerdt** [comment]
I noticed that you made updates against the v2.0 branch which wasn't part of the release. Please make future updates against the master branch. I think the links should work now?

**Comment by gatonero** [comment]
The links work with v2023.9.3-alpha-3.

**Comment by gatonero** [comment]
Nice to see you back again! 😃
