### ISSUE TITLE
Passthrough doesn't need required fields

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#287]
### What happened?

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/d125d0cc-6b71-4981-b068-276ccc8f4a4f)

Remove that literal.

### How to reproduce

Add "Passthrough"

### Which version are you running?

v2023.9.1

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
BTW: How "Passthrough" and sensor "Evapotranspiration" correlate?

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/c096a341-44f8-479b-9c06-d798a26fa3e7)

**Comment by jeroenterheerdt** [comment]
As you would expect. Pass through takes your evapotranspiration sensor and returns its value. It bypasses all calculation that way.

**Comment by jeroenterheerdt** [comment]
I'd say we either update the description in the UI to make this more clear or we document it - what do you think?

**Comment by jeroenterheerdt** [comment]
also, notice how there are two dots here... that's a small bug in the German file, it specifies an extra dot :)

**Comment by gatonero** [comment]
> I'd say we either update the description in the UI to make this more clear or we document it - what do you think?

I guess we should do both.

**Comment by jeroenterheerdt** [comment]
@gatonero please update the readme as per the comment I left and then assign this to me to update the EN and NL files.
