### ISSUE TITLE
During  "calculate_zone" service call, data is not a dict

### ISSUE THREAD

**Issue by GiorgioUghini** [jeroenterheerdt/HAsmartirrigation#288]
### What happened?

It is impossible to calculate a specific zone, service throws an error because of invocation of .get() on a list and not on a dict.

### How to reproduce

Set forecast days > 0, i.e. set it to 1, and call the calculate_zone service referencing that zone.

### Relevant log output

```shell
Error from logs:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 1028, in handle_calculate_zone
    await self.async_update_zone_config(zone_id=zone_id,data=data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 775, in async_update_zone_config
    self._OWMClient.override_cache = data.get(const.ATTR_OVERRIDE_CACHE, False)
                                     ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'`
```

### Which version are you running?

latest

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
Did you follow the warnings?



WARNING Are you upgrading from v0.0.X (aka V1) to V2023.X.X (aka V2)?
--
Stop what you're doing and capture your V1 configuration before  installing V2. V2 is a complete overhaul of this integration and there  is no upgrade path. This means that effectively you will have to start  over. See the Wiki for instructions. We will not be able to recover your V1 configuration if you don't capture it before installing V2.

https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Migrating-from-version-1-(v0.0.X)-to-version-2-(202X.X.X)

**Comment by jeroenterheerdt** [comment]
Not sure if this is an upgrade problem, but it would help to know if you were using v1 before.

**Comment by GiorgioUghini** [comment]
I used v1 before but decided to start from scratch with v2 so I removed the specific integration linked to my zones and afterwards I completely removed the integration from HACS. Then I installed it from scratch.

**Comment by GiorgioUghini** [comment]
Anyway if you see, the service call instantiate data as a List (https://github.com/jeroenterheerdt/HAsmartirrigation/blob/1eaa1ae6975aed5c8ef69646f827a2b8a43ff34e/custom_components/smart_irrigation/__init__.py#L1028) but then the function uses it as a dict (https://github.com/jeroenterheerdt/HAsmartirrigation/blob/1eaa1ae6975aed5c8ef69646f827a2b8a43ff34e/custom_components/smart_irrigation/__init__.py#L1028).
