### ISSUE TITLE
Can't remove zone entities

### ISSUE THREAD

**Issue by ScratMan** [jeroenterheerdt/HAsmartirrigation#290]
### What happened?

When migrating from 0.0.82 to v2023.9.2 the integration created two default zones, I created a new zone, made some mistakes, changed entity name, removed it and created the final zone to get everything OK; but the old entities are still shown in the Smart Irrigation integration's entities panel 

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/971926/f293a150-6739-4863-a78f-85b9fcae717c)

I only have the last zone in the side panel

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/971926/8a497a5e-2117-46ea-b649-63f4c285f059)

How to remove the unwanted zone entities ?
Thanks

### How to reproduce

Create some zones, remove them, and look in the [Smart Irrigation integration panel](https://my.home-assistant.io/redirect/integration/?domain=smart_irrigation) the number of entities is increasing.

### Which version are you running?

v2023.9.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-f66836a537e28cd21f10fdb23a0238d5.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12718973/config_entry-smart_irrigation-f66836a537e28cd21f10fdb23a0238d5.json.txt)

**Comment by jeroenterheerdt** [comment]
I am not sure if this is caused by the integration or by HA. Can you try removing the entities you don't need any more using the remove entities option in the same screen as you shared?

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8188990/06175937-4a2b-408b-b632-79e0316c0400)

**Comment by ScratMan** [comment]
Hi, HA says I can't delete the selected entities because the integration is still providing them.

**Comment by jeroenterheerdt** [comment]
huh. that's weird, because they are not any more, right? do they disappear after a reboot?

**Comment by ScratMan** [comment]
I tried rebooting yesterday but it didn't help. That's why I disabled the entities. I tried again, enabled the entities, they became unavailable, then rebooted HA and then I had the message saying integration doesn't provide the entity anymore; and the remove entity button appeared.
So it's fixed, but not really straight forward.

**Comment by jeroenterheerdt** [comment]
yeah, that's what I meant. Sometimes HA gets confused.
