### ISSUE TITLE
OWM precipitation from daily is not consistent with assumptions

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#293]
### What happened?

[OWM precipitation from daily](https://openweathermap.org/api/one-call-api) is not consistent with our assumptions / requirements for when people use a sensor. We expected it to be a daily forecast but it varies wildly during the day. Precipitation in our integration is defined as: daily["rain"] + daily["snow"]. I'd expect it to either stay 0 or increase when the day progresses, but it doesn't:
```
"data": [
          {
            "Windspeed": 0.0,
            "Pressure": 996.2924284049999,
            "Humidity": 100.0,
            "Temperature": 12.527777777777775,
            "Dewpoint": 10.82,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T00:34:39.708540"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 996.2924284049999,
            "Humidity": 100.0,
            "Temperature": 12.449999999999998,
            "Dewpoint": 11.35,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T01:34:40.198560"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 996.2924284049999,
            "Humidity": 100.0,
            "Temperature": 12.42222222222222,
            "Dewpoint": 11.22,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T02:34:40.211957"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 996.2924284049999,
            "Humidity": 100.0,
            "Temperature": 12.111111111111109,
            "Dewpoint": 10.65,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T03:34:40.203154"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 996.981904134,
            "Humidity": 100.0,
            "Temperature": 11.922222222222222,
            "Dewpoint": 10.37,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T04:34:40.604191"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 996.981904134,
            "Humidity": 100.0,
            "Temperature": 11.61111111111111,
            "Dewpoint": 9.76,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T05:34:40.331183"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 997.671379863,
            "Humidity": 100.0,
            "Temperature": 11.261111111111113,
            "Dewpoint": 9.51,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T06:34:40.212081"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 997.671379863,
            "Humidity": 100.0,
            "Temperature": 11.172222222222222,
            "Dewpoint": 9.55,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T07:34:40.229681"
          },
          {
            "Windspeed": 0.0,
            "Pressure": 999.73980705,
            "Humidity": 100.0,
            "Temperature": 12.177777777777779,
            "Dewpoint": 9.74,
            "Precipitation": 0.0,
            "retrieved": "2023-09-26T08:34:40.255309"
          },
          {
            "Windspeed": 0.6656764568994703,
            "Pressure": 1014.0000058602027,
            "Humidity": 90,
            "Temperature": 11.83,
            "Dewpoint": 10.24,
            "Precipitation": 6.44,
            "retrieved": "2023-09-26T09:10:40.109577"
          },
          {
            "Windspeed": 0.6656764568994703,
            "Pressure": 1014.0000058602027,
            "Humidity": 88,
            "Temperature": 13.56,
            "Dewpoint": 11.61,
            "Precipitation": 6.33,
            "retrieved": "2023-09-26T10:10:40.002459"
          },
          {
            "Windspeed": 1.002254440725045,
            "Pressure": 1014.0000058602027,
            "Humidity": 82,
            "Temperature": 14.79,
            "Dewpoint": 11.75,
            "Precipitation": 8.1,
            "retrieved": "2023-09-26T11:10:39.907213"
          },
          {
            "Windspeed": 1.002254440725045,
            "Pressure": 1015.000005865982,
            "Humidity": 82,
            "Temperature": 14.91,
            "Dewpoint": 11.87,
            "Precipitation": 8.33,
            "retrieved": "2023-09-26T12:10:40.013252"
          },
          {
            "Windspeed": 1.675410408376195,
            "Pressure": 1015.000005865982,
            "Humidity": 77,
            "Temperature": 14.83,
            "Dewpoint": 10.84,
            "Precipitation": 9.94,
            "retrieved": "2023-09-26T13:10:39.946402"
          },
          {
            "Windspeed": 1.675410408376195,
            "Pressure": 1016.0000058717612,
            "Humidity": 85,
            "Temperature": 12.11,
            "Dewpoint": 9.67,
            "Precipitation": 12.62,
            "retrieved": "2023-09-26T14:10:39.921761"
          },
          {
            "Windspeed": 1.2939553600405433,
            "Pressure": 1015.000005865982,
            "Humidity": 81,
            "Temperature": 12.62,
            "Dewpoint": 9.45,
            "Precipitation": 7.54,
            "retrieved": "2023-09-26T15:10:39.889807"
          },
          {
            "Windspeed": 1.002254440725045,
            "Pressure": 1016.0000058717612,
            "Humidity": 87,
            "Temperature": 12.81,
            "Dewpoint": 10.7,
            "Precipitation": 6.46,
            "retrieved": "2023-09-26T16:10:39.834069"
          }
```

The OWM API does not seem to provide anything else, although there is a hourly precipitation (`hourly.rain.1h` and `hourly.snow.1h` in the API. That could work but only if the user would update every hour, which we don't really control.
Default aggregation for precipitation in our integration is "last", which would work if the assumption was true, which it clearly isn't. Average is maybe a better alternative but if you look at the above I am concerned the number of 0s drag it down too much.

Thoughts @gatonero?

**Comment by gatonero** [comment]
There are accumulated parameters in OWM https://openweathermap.org/api/accumulated-parameters#precip. Does this help?

**Comment by gatonero** [comment]
A call like this is possible https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=50.75&lon=6.08&date=2023-09-2&appid={appid} and gives daily aggregations. See daily aggregations under https://openweathermap.org/api/one-call-3#history

**Comment by jeroenterheerdt** [comment]
> A call like this is possible [https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=50.75&lon=6.08&date=2023-09-2&appid={appid}](https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=50.75&lon=6.08&date=2023-09-2&appid=%7Bappid%7D) and gives daily aggregations. See daily aggregations under https://openweathermap.org/api/one-call-3#history

I believe that is only after the day finished, while we are calling OWM during the day

**Comment by jeroenterheerdt** [comment]
> There are accumulated parameters in OWM https://openweathermap.org/api/accumulated-parameters#precip. Does this help?
> 
> Just now I saw that this is a feature of professional collections.
> 
> Will look for an other solution.

Yes, I noticed that as well.

**Comment by jeroenterheerdt** [comment]
> > A call like this is possible [https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=50.75&lon=6.08&date=2023-09-2&appid={appid}](https://api.openweathermap.org/data/3.0/onecall/day_summary?lat=50.75&lon=6.08&date=2023-09-2&appid=%7Bappid%7D) and gives daily aggregations. See daily aggregations under https://openweathermap.org/api/one-call-3#history
> 
> I believe that is only after the day finished, while we are calling OWM during the day

ok, I have just tried this and this looks promising:

`
{
    "lat": 47.7423218,
    "lon": -121.9856781,
    "tz": "-07:00",
    "date": "2023-09-27",
    "units": "metric",
    "cloud_cover": {
        "afternoon": 100.0
    },
    "humidity": {
        "afternoon": 95.74
    },
    "precipitation": {
        "total": 75.47
    },
    "temperature": {
        "min": 10.97,
        "max": 13.52,
        "afternoon": 11.48,
        "night": 12.02,
        "evening": 12.09,
        "morning": 11.28
    },
    "pressure": {
        "afternoon": 1012.7
    },
    "wind": {
        "max": {
            "speed": 3.57,
            "direction": 89.43
        }
    }
}
`
It would require people to have the OneCall 3.0 API subscription (and would force everyone using 2.5 to switch to that), but that's something we can do.

**Comment by jeroenterheerdt** [comment]
well, that sucks. The precipitation did not meet what actually happened. In fact, it went down from 75.47 in the morning to 29.24. The actual number is over 153 (all in mm). So yeah, this is not going to work either. I will check the diffference between my pure OWM config and sensor config to see if our current approach works better than this. Otherwise it's back to the drawing board...

**Comment by gatonero** [comment]
There's also a field `sensor.openweathermap_forecast_precipitation_probability` which varies a lot during the day. Maybe we should have a look at it also.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/311a2e26-4e32-4674-b3d5-5ebb6bfda649)

**Comment by jeroenterheerdt** [comment]
But that's just the chance of rain, not the actual rain amount

**Comment by gatonero** [comment]
Yes but it comes together with the amount. So it could be a hint, when to calculate with the amount. But all together it seems to be very vague.

Maybe the precipitation should only taken into account, when the probability is above 80%. Here are some graphs which show how these values might correlate. All from 2023-09-22 / 00:00 to 2023-09-23 / 23:55

1. Forecast Precipitation probability

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5cce6405-28dd-4525-9ed6-60068ab070ef)


2. Forecast Precipitation

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5a102d8e-56f2-40e2-bb27-6882dab187a4)


3. Real measurement

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/85a6679f-b7e6-44d4-a1c3-ac8b4af0c0ae)

**Comment by gatonero** [comment]
Another example over a week:

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/5692745a-ca7c-40cf-880a-d99d26eee0a0)

**Comment by gatonero** [comment]
Here another correlation between rein rate and forecast condition.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/c1b3d429-573f-46a3-b9b2-62820c100fdd)

**Comment by jeroenterheerdt** [comment]
interesting.. but would that mean that we take a simple sum of the rain amount? Or are you saying you would only take the rain amount if probability > some threshold (80%?) and then apply an aggregate on it (max/sum/last ??)

**Comment by gatonero** [comment]
This doesn't seem particularly reliable to me. We should only consider OWM forecasts when the chance of rain is over at least 80% and/or the forecast condition = rainy. It seems to me that the maximum value is always lower than the actual precipitation. But this has to be observed.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7086fa68-feea-403c-a292-a42e6bf1540a)

**Comment by jeroenterheerdt** [comment]
OK, I can try and change the logic just for OWM to see what effects it has.

**Comment by jeroenterheerdt** [comment]
hey @gatonero are you still monitoring this? does it still look like only taking the daily rain forecast into account when a certain precip chance % has been passed is the right thing to do?

**Comment by gatonero** [comment]
I'm still observing it but we didn't have rain for three weeks now. I will notify about my surveillance.

**Comment by gatonero** [comment]
@jeroenterheerdt 

New insights. Calculating with OWM forecast is like playing roulette!

1. The day before yesterday at calculating time forecast probability was about 40% but it rained yesterday -> irrigation started (not ok)
2. Yesterday at calculation time forecast probability was about 60% it rained (a lot) today -> no irrigation, which is ok but I guess it's caused by a bucket > 0

Conclusion: OWM isn`t reliable. The only workaround could be, to have a look at current rain rate and/or forecast again at irrigation time???

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/6ae58960-3199-486c-99a7-e396e525a764)

**Comment by jeroenterheerdt** [comment]
Crap. I guess this goes to show that you should really only use your own sensors and not rely on OWM. We should update our readme for this.

**Comment by gatonero** [comment]
No, OWM is not too bad. Just the forecast values are more or less  screwed up for our due. This is the nature of weather forecasts especially if they are for small local regions. This is what OWM explains for predictions [OWM, accuracy and quality](https://openweathermap.org/accuracy-and-quality)

`However, we should keep in mind that the actual difference between the nowcast and the real situation at a specific place and time could be bigger than these average errors. `

The actual weather data are quite good as shown in the following graphs. The only big difference is in wind speed for which I will have to proof my station and settings.

![Dewpoint](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/7104536e-2109-4a4a-b2c6-c38040af0bbc)

![Humidity](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/2777246b-6231-40dc-827d-f1cddf705fad)

![Rain](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/12e6a647-5f4d-498b-8ef1-3541ccccd4db)

![Preesure](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/f5d901a3-8d4b-43c4-83a4-9bee0be9c427)

![Temperature](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/13abdb06-4a8c-4325-9a88-b3996df055d3)

![Windspeed](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/0abd108a-952f-4062-8dc4-9267af188725)
