### ISSUE TITLE
Event smart_irrigation_start_irrigation_all_zones doesn't get fired

### ISSUE THREAD

**Issue by gatonero** [jeroenterheerdt/HAsmartirrigation#298]
### What happened?

In two installations for all zones the duration was > 0 but no event was fired.

### How to reproduce

Set an automation trigger to 

```
trigger:
  - platform: event
    event_type: smart_irrigation_start_irrigation_all_zones

```

### Relevant log output

```shell
none
```

### Which version are you running?

v2023.9.2 + v2023.9.3-alpha-4

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-2ba0f2582e7dc5b3148b910438fccdbe.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12747678/config_entry-smart_irrigation-2ba0f2582e7dc5b3148b910438fccdbe.json.txt)

**Comment by jeroenterheerdt** [comment]
A crap. This again??

**Comment by Nebukad93** [comment]
Hello,

Same thing for me. Worked well yesterday and not this morning. I had to fire the event myself from the dev tools panel.
[config_entry-smart_irrigation-053274251150d7cc5a0dc7fe86f7575e.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12780207/config_entry-smart_irrigation-053274251150d7cc5a0dc7fe86f7575e.json.txt)

**Comment by gatonero** [comment]
Today all worked fine without changing anything. Also #297 didn't appear.

**Comment by Nebukad93** [comment]
Hello, I have the error this morning. I was fine yesterday. 

‘’’
Logger: homeassistant
Source: helpers/event.py:1578
First occurred: 3 octobre 2023 à 23:00:00 (1 occurrences)
Last logged: 3 octobre 2023 à 23:00:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 541, in _async_calculate_all
    self.register_start_event()
  File "/config/custom_components/smart_irrigation/__init__.py", line 920, in register_start_event
    self._track_sunrise_event_unsub()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1578, in async_detach
    assert self._unsub_sun is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
‘’’
