### ISSUE TITLE
[REQ] Attributes from V1

### ISSUE THREAD

**Issue by elenril2** [jeroenterheerdt/HAsmartirrigation#299]
**Is your feature request related to a problem? Please describe.**
Missing attributes in V2.

**Describe the solution you'd like**
Is there a way to get some of the attributes available in version 1? I used daily run times and a bucket for each of my zones to manually run the sprinklers for specific times. For example, if rain was coming, I substracted this value from zone's bucket - and new runtime calculations were performed automatically when I run set bucket service.
I see that daily run time is in the zone entity, but what about of bucket? In v1 I took this by using a HA template from attribute provided in daily run time.

**Describe alternatives you've considered**
Back to V1, if it is still possible...

**Additional context**
I've had complex node-red flows and want to keep them.

**Comment by jeroenterheerdt** [comment]
V2 has a forecast feature so you don't need to do this :) I can look into this but HA wants us to reduce the number of attributes on sensor entities, so we need to be very specific about what we're adding.

**Comment by elenril2** [comment]
Thanks for answer. For me, the bucket sensor was very useful. It allowed for accurate tracking of lawn hydration, but also for forecasting rain. I don't know exactly how your forecast feature works, but my Node-Red flow checked the forecast just before I started watering - if the rain didn't fill the entire bucket needed, I compensated it during watering (I added the forecast rainfall to the bucket, reducing its value). And most importantly - at the end of watering I did not reset the bucket, but left the difference, i.e. the forecast rainfall. If the forecast did not come true or was in fact different, this was correctly recalculated in the integration thanks to the rainfall sensor from my weather station.
I also made sure that the bucket did not exceed the set value, but I see that you provided for this in the V2 as standard.
I would like such functionality, so if it's not a problem, I would ask you to add the bucket attribute.

By the way, many thanks for creating this integration. In my HA environment it is one of the best and most effectively used :)

**Comment by jeroenterheerdt** [comment]
Thanks for sharing. I can try to add the bucket as a property as a short term fix but I'd like to see if I cannot add the way you work with the forecast as you described. The forecast I mentioned is on pyeto and basically says: look at x days forecast and take the mean of de deltas calculated using it. So it takes into account more than just the rain, also temp, wind speed, etc. It can also look at days ahead. So it might more accurate than what you're doing now, but I think looking at the forecast just before irrigating would be a nice addition.

**Comment by JamesDilan** [comment]
Good day, 
Would also appreciate for bucket attribute to be added. there is some static attribute available in sensor, but dynamic one like bucket, ETO, etc are missed. 
Thanks in advance.

**Comment by jeroenterheerdt** [comment]
> Good day, Would also appreciate for bucket attribute to be added. there is some static attribute available in sensor, but dynamic one like bucket, ETO, etc are missed. Thanks in advance.

What would be your use case?

**Comment by elenril2** [comment]
> Thanks for sharing. I can try to add the bucket as a property as a short term fix but I'd like to see if I cannot add the way you work with the forecast as you described. The forecast I mentioned is on pyeto and basically says: look at x days forecast and take the mean of de deltas calculated using it. So it takes into account more than just the rain, also temp, wind speed, etc. It can also look at days ahead. So it might more accurate than what you're doing now, but I think looking at the forecast just before irrigating would be a nice addition.

Unfortunately, in my case, for the place where I live, OWM often does not have the correct forecast. That's why I prepared Node-Red flows, which take into account the rain forecast, but leave it in the bucket, which allows me to adjust the irrigation later to the actual rainfall.

**Comment by JamesDilan** [comment]
Sorry for time not reply. My use case is very simple - double confirmation that every thing is working as required. Auto watering system is very dangerous system, in case if something is goes wrong. For hardware i setup regular maintenance, but for Home assistant, i need to keep on it yes every month. And bucket calculation is the one that required to have attention on debagging level. Also as juacas mentioned bucket is also on my main dashboard. I have PWS setup, so that ETO and daily rain is calculated by itself. Before you integration i just had several sensors to calculate all required, but i really like v1 of you integration and want to use v2 as well. Any way thanks for your support, Really appreciate time you spend on this project.
