### ISSUE TITLE
Possible to add zones? [REQ] 

### ISSUE THREAD

**Issue by MYeager1967** [jeroenterheerdt/HAsmartirrigation#30]
Many sprinkler systems incorporate zones. These areas are often fitted with different numbers of sprinklers with different flow rates and watering times would be different for them. Any possibility of expanding this to offer the option for multiple zones? If I'm looking at this incorrectly, please let me know. I love the idea, just not sure how it fits my system.

**Comment by jeroenterheerdt** [comment]
Zone support is already there, just add the component multiple times. I will document this further

**Comment by posixx** [comment]
You can add the integration multiple times; one for each zone you have. That is how I use it.

**Comment by ciechompl** [comment]
or you can have a look at my config: https://github.com/ciechompl/HA-yamls/tree/master/Smart%20Irrigation 
I also have several zones (currently 8) and to fully control how much water each zone should get :) I added several input_number sliders where I can tune irrigation time  (% wise) calculated by this component. The main thing is that first you have to calculate average water flow for entire system and doesn't matter whether you define 1 big sprinkler or e.g. 8 sprinklers in the component where each will represent one string of sprinklers. component will calculate irrigation time for entire garden and later you cna use it in automation to run one string after another .... At least for me it is perfectly ok so maybe you will also get inspired how to implement component in your system :)

**Comment by MYeager1967** [comment]
I had actually just thought about trying to do this. Was coming back to let you know I figured it out. :-)

**Comment by jeroenterheerdt** [comment]
Awesome, let us know how you get on!

**Comment by MYeager1967** [comment]
Just need to figure out how to use it with what I already have. I'm sure I'll have to rewrite a bit, but that's how it usually goes.

**Comment by MYeager1967** [comment]
I'm not sure I understand how this thing is supposed to work. Right now it's got my daily adjusted run time for one zone at over half a day. It's been raining on and off for the past two days....

**Comment by jeroenterheerdt** [comment]
Can you share screenshots of sensors and attributes as well as if you have HA configured in metric or imperial system?

**Comment by MYeager1967** [comment]
![image](https://user-images.githubusercontent.com/4985590/83760068-6aea1700-a642-11ea-8743-59e0caf3ca6f.png)
I am in the US and everything should be imperial. Hopefully the pictures come through. The first is the sensors overall. 
![image](https://user-images.githubusercontent.com/4985590/83760204-9d940f80-a642-11ea-8fa3-8b6b1377bfb4.png)
![image](https://user-images.githubusercontent.com/4985590/83760241-abe22b80-a642-11ea-9ba9-d7b41ca72b22.png)
![image](https://user-images.githubusercontent.com/4985590/83760289-bb617480-a642-11ea-92a8-c61e7c78082b.png)
Unless I'm reading into how this is supposed to work, It's telling me I need to run that zone for nearly 4 hours. I know I probably need to adjust the parameters on the zone a little, but it's pretty close I believe. Was just running it along side my routine to see how it worked before I integrated it. After all, it's modeled after a very successful watering models. I hope I'm just looking at something wrong and didn't find a big bug...

**Comment by jeroenterheerdt** [comment]
right, this doesn't look good. somehow your bucket is way off: -3.7 inch, while it should have been .3 inch assuming this is the first 24 hour you run this. Can you call the `reset_bucket` service and monitor again what it does at 11PM tonight?

**Comment by MYeager1967** [comment]
Sure. I had reset the buckets yesterday just to be sure I knew how to do it. I'll do it again right now, but it's still drizzling so I don't know how that's going to play into things. I'll post zone 1 before and after reset...
![image](https://user-images.githubusercontent.com/4985590/83802535-eff02300-a678-11ea-8021-0027d5706342.png)
![image](https://user-images.githubusercontent.com/4985590/83802553-fa122180-a678-11ea-948b-7de067413a23.png)
After reset...
![image](https://user-images.githubusercontent.com/4985590/83802657-20d05800-a679-11ea-91a3-f78e31d4063d.png)
![image](https://user-images.githubusercontent.com/4985590/83802669-2a59c000-a679-11ea-85e2-9e2679b58739.png)

Resetting it returned everything to zero as expected. Will let you know what I have tomorrow...

**Comment by jeroenterheerdt** [comment]
Yeah, just bear in mind that the change percentage behavior has changed so if you get massive percentage reported in the attributes of daily ART go to options and click OK. That should set it to 100 or to whatever you want it to. Given what I see now we should expect the bucket to be set to approx 0.17 inch at 11pm. It is set to the average of the collected netto precipitation. So if it is way off from that something is off.

**Comment by MYeager1967** [comment]
No problem. I went back and read how to use it several times and figured something had to be wrong somewhere. There's no way it should be telling me to water anything. We've got standing water in the yard now...

**Comment by jeroenterheerdt** [comment]
right, the `netto precipitation>0`, so that means more moisture is added than removed, so no need for irrigation. at 11 PM you should see your bucket being updated from `0` to whatever the average `netto precipitation` is (let's assuming `0.17` for now). Given that `bucket>=0`, your daily ART is going to `0`, which means, no need for irrigation. Your `bucket` will _not_ be reset however.
If the next day your `netto precipitation` is still > 0, the same will happen, but of course the bucket is not `0`, but `0.17` to begin with. Let's say the `netto precipitation` is `0.13`. The `bucket` should end up at `0.30` then. Now, imagine the day after that there is no rain and a lot of sunshine. Your `netto precipitation` might be `-0.35`. You should see your `bucket` dropping to `0.30-0.35=-0.05`. That would bring your daily ART to something above `0`, which should prompt you to irrigate and most importantly, sequentially reset the `bucket` to `0`. (you have to set up an automation yourself). I hope this clarifies a bit on how it is supposed to work. Now let's monitor and see if there are any bugs. Your set up looks good now, so don't touch anything but keep an eye on the values and see if you see the same pattern as I explained above happening.
In the mean time, I will think about adding some visual explanation of this to the documentation.

**Comment by jeroenterheerdt** [comment]
@MYeager1967 - I created this page in the Wiki - hope this helps: https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Example-behavior-in-a-week

**Comment by MYeager1967** [comment]
I was pretty certain that I understood how it was supposed to work. I had even ready the Rainbird pages on it. That's why I couldn't understand why it was suddenly wanting me to water for HOURS, not even just minutes. Was the bump in version to correct something that was causing the issue? I'll let you know tomorrow if the numbers look good. Once this is all sorted out, can I change the time for the daily update? I generally water about 8pm. Otherwise I'd be watering about 8:30am and the sun is already up...

**Comment by MYeager1967** [comment]
Ok. Here's what I have now for the same two sensors I zero'd yesterday.
![image](https://user-images.githubusercontent.com/4985590/83878998-faf39380-a70a-11ea-86dd-a9efd7eaa6a8.png)
![image](https://user-images.githubusercontent.com/4985590/83879032-0777ec00-a70b-11ea-8c99-c4d4e8be2346.png)
At this point, it appears to me as though the precipitation total for the day isn't getting updated. It looks as though it's getting replaced by the new value instead. I also can't figure out where the evapotranspiration number came from. At .21, I would figure that to be a hot, possibly windy day here (the data input was something like .17 or so for June) and it was overcast and rainy. If it would help to look at the data provided, I'm using all OWM data and my zip code is 34743.

**Comment by jeroenterheerdt** [comment]
Your change percentage is way off. Go into options and make sure it says a 100 there and save the options. Change percentage should turn to 100 in the attributes of daily ART as well.

**Comment by WizShip** [comment]
Is there a way to go back and change settings without a remove and reinstall? I am using my own weather station and believe I chose the wrong sensor for rain logging

**Comment by MYeager1967** [comment]
It was already 100 but I saved it anyhow and now it reads 100 in the sensor. in about 20 minutes, I'll get the next hourly update and we'll see what changes then. Rolling back to v0.0.29....

**Comment by jeroenterheerdt** [comment]
@MYeager1967 thanks, keep me posted.
@WizShip no, unfortunately. Also, please do not hijack threads. Open a new issue.

**Comment by posixx** [comment]
I don't see any problems with daily runtime. However it's raining all day here so it will be about 0 today:-)

![image](https://user-images.githubusercontent.com/2280400/83894459-9f002d80-a751-11ea-81f4-f29fb648f988.png)

**Comment by MYeager1967** [comment]
Of course now that I've rolled the version back, the sun has peeped out. Not going to be very helpful to tracking down and issue with the bucket, is it?

**Comment by WizShip** [comment]
Apologies :-( But to be fair the thread is about adding zones and not about buckets either :-) Regardless...not worries

**Comment by jeroenterheerdt** [comment]
@MYeager1967 should be fine regardless. just take note of the current bucket value and the netto precipitation during the day. We should see the bucket being updated with the average of the netto precipitation.

**Comment by MYeager1967** [comment]
If it rains any more today... What made you suspect an error in the way it was being updated?

**Comment by jeroenterheerdt** [comment]
@MYeager1967 on the community forum (community.home-assistant.io) people have been complaining about the latest release as well, that's why :)

**Comment by MYeager1967** [comment]
![image](https://user-images.githubusercontent.com/4985590/83932555-417bd900-a771-11ea-8fa6-16a8510c5f0a.png)
Is the precipitation supposed to keep a running total or change up and down every hour? There has to be a running total for the day somewhere???

**Comment by jeroenterheerdt** [comment]
No worries, the running total is kept by the system. When it calculates daily values you will see in logs that it takes the average of the the hourly values.

**Comment by MYeager1967** [comment]
This is what I have this morning
![image](https://user-images.githubusercontent.com/4985590/83944074-d2cd6880-a7ce-11ea-8ff3-54d3122dabdc.png)
Looks much better but I still don't understand why the hourly updates jump all over the place. Doesn't matter I suppose as that's not what controls things. You say the running total is kept by the system. Will it survive a reboot? As you know, HA gets updated frequently at this point. Good for us as it's generally new features as well as a few bug fixes, bad for data if it's not retained during reboot. Any luck chasing down the issue with the new version yet?

**Comment by posixx** [comment]
If you restart HA hourly runtime will "jump all over the place" as it will be 0 after restart. The daily runtime will persist. So if you don't restart HA hourly runtime will be smooth:-) Hourly is not persisted but updated after 300 seconds when HA started.

**Comment by MYeager1967** [comment]
Ok. I have been working on it quite a bit lately so that may account for why is does what it does. At the end of the day, the hourly adjusted run time isn't what controls the show, so it really doesn't matter. I just like to understand how things work, not always possible though. :-) Now it's time to settle back and watch it work for a while. I see it updated the bucket. We got a ton of rain yesterday....

**Comment by jeroenterheerdt** [comment]
Happy to see that it works the way it's supposed to now. I am seriously considering pulling every release since the one you are running now since somewhere along the way of introducing new features it broke. I have a - 0.11 bucket and my ART is over 3000 minutes with the latest release. Also getting reports of the same through other forums. Hope to get some time soon to investigate.

**Comment by MYeager1967** [comment]
Yeah, that's what I saw on the later release as well. It was going absolutely nuts...
I'm looking forward to putting this to use after I see how it runs alongside my current system.

**Comment by jeroenterheerdt** [comment]
ok, v0.0.40 is out - change percentage is disabled since it caused so many bugs (sorry @ciechompl ...). Initial update delay is still there since it does not seem related. Also, all bug fixes since v0.0.29 are included as well. Please update and test :) Thanks for bearing with me!

**Comment by MYeager1967** [comment]
I'm not sure the percentage of change was important anyhow, was it? It likely just caused confusion....

**Comment by jeroenterheerdt** [comment]
well, it certainly confused me ;)

**Comment by MYeager1967** [comment]
Does the evapotranspiration figure change frequently depending on the OW data or should that stay fairly constant?

**Comment by posixx** [comment]
IMHO, percentage shouldn't be part of this plugin; it's purpose is calculating daily runtime. If someone want's to alter the calculated values he can do so in various ways within HA.

**Comment by MYeager1967** [comment]
Only alteration I'd likely make is a maximum runtime in case something got screwed up. The whole reason for this is to provide a proper watering time...

**Comment by jeroenterheerdt** [comment]
@posixx I tend to agree that percentage does not need to be part of this component.
@MYeager1967 evapotranspiration is calculated every hour and can change, depending on sun hours or wind speed for example. Many factors impact it. Also, maximum runtime is already implemented and available in the options screen.

**Comment by MYeager1967** [comment]
Yes it is... That would prevent these 15000 second run times in case of an error. So long as something realistic is in there, it should limit it to the max run time.

**Comment by jeroenterheerdt** [comment]
@MYeager1967 - right, so by default if you go into the options screen you will see the max duration set to -1, which means there is no maximum. Personally I have it set to 1800 seconds (30 minutes)

**Comment by MYeager1967** [comment]
I haven't dug into it yet, but I see there's a manual (forced) mode as well... Your automation even force stops the irrigation for something, I haven't dug into it to see why you did it. Mine is simply going to run if the system is enabled.

**Comment by jeroenterheerdt** [comment]
Force mode forces the daily ART to be set to the force mode duration. See the readme. This way you can override whatever the calculations say you should do. You could also force it to not run by setting duration to 0.

**Comment by MYeager1967** [comment]
I'm redoing my sprinkler routine as we speak. I don't do automations in HA, I do them in Appdaemon instead where I have full use of python. Not sure I have a need of forcing the sprinklers to run, but I'll keep it in mind and have something clear the forced flag after each run. That way, a simple switch can be set to set all zones to run manually and once they run, it can be cleared automatically. Is that the basic idea behind it?

**Comment by jeroenterheerdt** [comment]
Yes sir. Please share whatever you create, so I can include it in the examples!

**Comment by MYeager1967** [comment]
![image](https://user-images.githubusercontent.com/4985590/83959329-9f7bef80-a849-11ea-9b6c-7d1523c7046d.png)
May still have a problem. Pretty certain I didn't go from 1 inch to this in a day....

**Comment by jeroenterheerdt** [comment]
That is weird. Did you reset the bucket at all? What was the value before? And what is your netto precipitation for today?

**Comment by MYeager1967** [comment]
![image](https://user-images.githubusercontent.com/4985590/83959377-5b3d1f00-a84a-11ea-801e-ad53d02ca5f8.png)
Hasn't updated yet this hour...

**Comment by posixx** [comment]
Running v0.0.41 here my daily runtime also was 0 last night:

![image](https://user-images.githubusercontent.com/2280400/83963959-dc77ce80-a8a9-11ea-95e3-b4d6cb6ba596.png)

Although hourly runtime seems good:

![image](https://user-images.githubusercontent.com/2280400/83963997-092be600-a8aa-11ea-8e1c-336dfa2ed949.png)

**Comment by MYeager1967** [comment]
Went to roll back to 0.29 this morning, but it wasn't in the list of options. :-)

**Comment by jeroenterheerdt** [comment]
@posixx the bucket is > 0 so no Daily ART is expected to be 0. Did your bucket decrease with 3.9 (netto precipitation)?

**Comment by posixx** [comment]
Sorry jeroen i don't know. Didn't look at these values at all. In fact, i don't know what the bucket value stands for..

**Comment by MYeager1967** [comment]
I've got one zone that I zero'd the bucket on last night to see what the result was today compared to the other two zones that gained 30 inches in the bucket yesterday. Needless to say, we didn't get 30 inches of rain yesterday or I'd be sending this from a boat...

**Comment by jeroenterheerdt** [comment]
@posixx right, so that seems OK. you are running version 0.0.41 right? Just think of `bucket` as an actual bucket - when there's water in the bucket (`bucket>0`) you do not need to irrigate. When the amount of water in the bucket becomes negative (this is where the bucket analogy breaks) you should really add water to the bucket so it is exactly 0 (bucket is empty, no water inside, but also no water 'mising'). That is what you do by irrigating for exactly the daily ART amount of time. Afterwards you tell the bucket to reset to 0 since you added enough moisture. Hope that helps.

@MYeager1967 - please let me know which version you are running on right now. are you still having problems with the zone that you zero'd or does it look OK now? If so, please update to the latest version if not already on that and reset both the buckets for the other zones.

**Comment by MYeager1967** [comment]
As far as I know, I'm running the latest (0.41). I zero'd the bucket for zone 3 and am waiting to see what the day does to it when it updates tonight. I'm also curious to see how much the other two zones change but 3 is the real test as it started at 0. At the moment, all three zones are in line with each other for the hourly adjusted figures. Doesn't mean much for the daily though...

**Comment by MYeager1967** [comment]
Wow. My bucket for zone 1 went from 30 inches yesterday morning to 769 this morning. Now, that zone was already screwed from whatever the error was the other day.

Zone 3, which I had zero'd as noted in an earlier post here, now shows .08 which I'm not sure is correct as we had quite a bit of rain yesterday, but at least it didn't go up astronomically. Still not certain how these numbers are figured as, in the picture below, you can see the ET number.
![image](https://user-images.githubusercontent.com/4985590/84035181-6044c000-a969-11ea-848b-1cf7062498b5.png)
That is way higher than I would expect it to be with the cloud cover that we have today. I'm assuming, however, that this number is achieved from data obtained by OW and the fixed ET data entered at startup. I know it changes throughout the day. I'm also assuming that the +/- net rainfall is tracked throughout the day as that should be the value that goes into the bucket.
I do enough programming to appreciate the time that you've got in this and how easily a small error one place can screw everything down the line. I can only imagine the amount of time you have invested in this and the research that's gone into putting this together.
Thank you once gain for your effort!

**Comment by jeroenterheerdt** [comment]
So the bucket looks fine to me now. Evapotranspiration is based on OWM data, and calculated using the `pyeto` library. The documentation for `pyeto` is limited. The code that calculates evapotranspiration is here: https://github.com/jeroenterheerdt/HAsmartirrigation/blob/master/custom_components/smart_irrigation/sensor.py#L613, feel free to check it. I did, but there might be issues in it.

**Comment by MYeager1967** [comment]
Is there any value in the hourly update that's guaranteed to change every hour? I'm guessing the ET value, but it's only a guess. I'm setting up a monitor to observe this process for a few days. External error checking as well as a better understanding of what is going on.

**Comment by jeroenterheerdt** [comment]
there is no guarantee, but you would probably see netto precipitation change and as a result the hourly adjusted run time itself since it is based on it. You would probably also see precipitation and ET change during the day, unless you have very static weather patterns.

**Comment by MYeager1967** [comment]
Would it be possible to lock the hourly updates to a certain time window or record the previous update time to ensure that it only updates once an hour? If someone is working on their HA installation and reboots several times, it's very likely that it screws the calculations for the day.

**Comment by jeroenterheerdt** [comment]
I don't think that would be an issue as I am taking an average of the measurements when calculating the daily value... so it does not matter if you take measurements every 5 minutes (other than it being way too much ;)).

**Comment by jeroenterheerdt** [comment]
@MYeager1967 just passing this along since you are in the US just like me - I have installed the Smart Weather custom component, they had two stations very close to me. I am now running a full Open Weather Map based version and a Smart Weather sensors based version side by side (with min/max temperature still from Open Weather Map). So far, things look way better. This should do fine for me until I built my own weather station.

**Comment by MYeager1967** [comment]
I'll look into that. May have my own thing going but I haven't dug into what sensors Smart Irrigation needs yet. I'm looking into Climacell and so far, it's almost dead on with DarkSky. Has a lot of extra data if you want it as well. I'll look into Smart Weather to see what they have in my area.

**Comment by MYeager1967** [comment]
If I wanted to control the time that the daily update occurs for zone 1, I'd use the smart_irrigation.zone_1_calculate_daily_adjusted_run_time service, correct? I'm assuming that this is the only one that's deactivated by turning off the automatic update and that the hourly still runs roughly every hour?

**Comment by stephenmetzger** [comment]
Hey  jeroenterheerdt, thanks for putting this together. If you use the "work days" condition approach, and only want to irrigate, say, 4 days a week, will the adjusted run times continue to build up and irrigate for an appropriate amount of time when it does trigger a cycle? I'm trying to wrap my head around this. I've plugged in all my data and my BSI minutes is showing 31.17 minutes. I assume this means at peak ET, i should be watering for 31 minutes each day. If i irrigate every other day, would my sprinkler run for ~ 60 minutes (assuming 2 days of peak ET in a row)?

**Comment by stephenmetzger** [comment]
Also, are the calculations dialed in for turf irrigation only? Would using this integration on zones with shrubs/flowers/etc be overkill and potentially lead to overwatering?

**Comment by MYeager1967** [comment]
I haven't full;y figured out the program yet, but the adjusted daily run time would likely build up to whatever the maximum run time that you set. I have been playing with this for a week and am just now confident enough with my weather information to go live with it (this morning would have been the first run). As for the shrubs, they usually require more water than just grass, but if they're on a zone of their own, you can set a maximum watering time and adjust that as you feel the need (or keep playing with the zone information until you get it where you want it).

**Comment by MYeager1967** [comment]
Ok, possible issue. I pointed the rain sensor at a value that tracks accumulated rain for the day. It appears as though the program looked at it every hour and added it all up to give me a 3.59 inch bucket this morning. Shouldn't the accumulated rain for the day only be looked at once (probably at the daily adjustment time)?

**Comment by jeroenterheerdt** [comment]
@MYeager1967 yeah, I noticed that behavior as well. I am working through the details now.

**Comment by jeroenterheerdt** [comment]
@stephenmetzger I am no botanist at all, but this component just calculates the amount of moisture lost and how long the system needs to run to make up for the lost moisture. if that's how you want to water your shrubs or whatever then it is all good. there are no specific optimizations for lawns.

**Comment by MYeager1967** [comment]
Just so you know, My weather source seems to start out with an estimate early in the day and winds it down as rainfall accumulates. Today, I have had zero in it all day, as it's not even supposed to rain. It updates every hour (or at least that's when I update it).

**Comment by stephenmetzger** [comment]
Thanks @jeroenterheerdt and @MYeager1967. Does manually calling the "calculate daily" service mess up the integrations running calculations? My hourly adjusted times seem to be updating nicely, but my daily adjusted time has been at 0 since 5PM yesterday. I've been trying my best not to touch anything and just check in on how it changes throughout the day, but it's a slow way to tinker around and figure out how it all works.

**Comment by MYeager1967** [comment]
You can always reset the bucket(s) after you're done playing. What time is your daily adjusted supposed to run? It only runs once a day and I believe it's set by default to 11pm. If you really want to figure out how it works, read the wiki and then do a little more research on your own. Watching it work will confuse you...

**Comment by jeroenterheerdt** [comment]
as @MYeager1967 said above, by default `daily adjusted run time` is only updated at 23:00 local time, once a day. so it being zero makes total sense until that moment comes. as you can see in the wiki / readme, the value stay zero even after the update happened in case the bucket >=0.

**Comment by stephenmetzger** [comment]
Yeah, ive read and re-read through the wiki, super good information, just trying to ground-truth it all. 
I expected an update at 11PM last night, but didnt see anything update.

**Comment by stephenmetzger** [comment]
I was guestimating on my sprinkler flow rates on first setup, and was using the BSI minutes to confirm things looked about right. I think I made my last change (re-install) at around 5 yesterday, and let it run (not connected to any actual sprinklers) without touching it. Checked a little after 11:00 and didnt see any changes to the daily adjusted. I'll continue to let it run all day today (high heat and no rain) and see what happens tonight at 11.

**Comment by stephenmetzger** [comment]
Also, bucket reset resets the bucket for all iterations of the integration, right? So, you can re-set the bucked for individual zones?

**Comment by jeroenterheerdt** [comment]
@stephenmetzger if you have multiple instances of the component enabled then you will see multiple reset_bucket services. that's your answer: everything happens in context of the instance so yes, you can reset the bucket for individual zones

**Comment by stephenmetzger** [comment]
Ahh, I see it now. Hadn't checked back in the services tab since I resintalled and added second zone. Thanks!

**Comment by MYeager1967** [comment]
Watch your hourly adjusted run times and it'll freak you out, but you'll know that something is happening. The daily tonight should reflect it.

**Comment by MYeager1967** [comment]
I'm going to take it that the update yesterday was to address the exponential growth in the bucket? I went from a 3.59 bucket yesterday to an 84 today with zero on the rain counter until 3pm. It was .0025 until 9pm then went to .0197 until 3am, long after the daily run. 

Now at 3am, it went to .1389 which I believe to be an estimate of rain expected. It did rain some overnight, but the rain accumulation has dropped to .1009  (at 6am) and remains there now. I suspect it will adjust sometime today to meet up with whatever rainfall we do get. It's supposed to rain.

I reset all my buckets about 8am, so here's to hoping things look better tomorrow....

**Comment by jeroenterheerdt** [comment]
@MYeager1967 no, I did not do anything to fix the weird spike in the bucket, but I did add a lot of logging to hope and be able to track it down. Please monitor your logs and share anything that looks like an explanation.

**Comment by MYeager1967** [comment]
I don't see anything in my logs. Would you like me to log something specific? If so, guide me along and I'll do what I can.

**Comment by jeroenterheerdt** [comment]
in your `configuration.yaml` set this:
```logger:
  default: error
  logs:
    custom_components.smart_irrigation: info
```

**Comment by MYeager1967** [comment]
Wow, what a mess... That's a LOT of logging. That said, I'm showing an hourly adjusted bucket of -5+ inches and I reset the buckets to 0 this morning. Is the program expecting an hourly rain total or a daily rain total? Should the bucket be touched any time other than the daily update? I can see where the ET value needs to be figured hourly, as the temperature and everything affects it, but adjusting the bucket value hourly seems as though it's going to require a fairly accurate, hourly rainfall total. Also, would it be possible (or useful) to lock the hourly updates to a given time like the daily is? I'm not sure if I'm reading what I think I'm reading, but "Bucket value was: -5.918656797890241" after 9 hours or so can't be right and "just updated hourly_bucket_list: [0.0, 0.0, -5.918656797890241, -5.918656797890241, -5.918656797890241]" is a bit puzzling. I had to do a couple of restarts, so I'm attributing the multiple entries to that. Even at that, it's horribly wrong.

**Comment by jeroenterheerdt** [comment]
- if you use sensors (as you are, I think) it expects a daily rain total (additive sensor), when the daily is updated it will take the most recent value.
- daily bucket should not be touched for anything other than the daily updated. The hourly adjusted run time is of course updated every hour.

Please reset your bucket once more. Also confirm if you are running in imperial system or in metric?

**Comment by MYeager1967** [comment]
I am all sensors and on imperial units. I've learned not to pay much attention to the hourly as it does some crazy things during the day. Just zero'd all the buckets and I see the events triggered by that in the logs. I'll check back either later, or most likely tomorrow sometime, but I suspect the bucket is going to be horribly off again. :-)

**Comment by jeroenterheerdt** [comment]
I hope it is not :) just make sure you are on the latest version (v0.0.49)

**Comment by MYeager1967** [comment]
Updating the component was one of the reasons for the reboots...

**Comment by jeroenterheerdt** [comment]
I have been running this version for two days now (v0.0.49) and it seems much better. No guarantees we're out of the woods though. I am running this on imperial as well. I also have a version running on metric, but the bug never appeared there.

**Comment by MYeager1967** [comment]
As long as it isn't reading the rain total every hour and adding it together. I can't understand how I keep getting these huge buckets though. Just out of curiosity, why did you make three different entities instead of one with all the attributes under it?

**Comment by jeroenterheerdt** [comment]
ehh, why? Because there are multiple different calculations going on and I was losing track of all of it. You're right, we do not need to surface the base schedule index nor the hourly entity, but it has proven very useful in debugging with others - now I can just get some screenshots and help right away. In retrospect it could all have been one gigantic entity with lots and lots of attributes but I would feel that would be even more confusing.

**Comment by MYeager1967** [comment]
That makes sense. Fewer things per entity probably does make things a little easier to track. The "sensor" I am using is a weather service API (ClimaCell) and it seems quite accurate for this area. Problem is, it runs 6am to 6am UTC (2am-2am local currently). It's close enough. Anyhow, it seems to give an estimate for the day, and then adjusts it as the day goes on to somewhat match what actually occurs. It has actually lowered on the days that we didn't get the rain forecasted. It should work out depending on when it actually uses the rain values. I might have to figure out another source of rainfall data if I can't get this one to seem reliable with the component. Once it's all running the way it should be, I'll be hiding everything but the daily run time. Those will show on the sprinkler panel.

**Comment by MYeager1967** [comment]
Well, so far things are looking quite a bit better. Watching the logs is an exercise in WTF though. I still have all kinds of rain amounts I can't figure out but they appear to be figures from the hourly updates, which I already know will drive me crazy trying to understand them. Today is supposed to be a bit wet later in the day, so we shall see. I came out of yesterday with a .04 bucket, which is probably about right with the rain we had yesterday. It's going to be fun to try to manually get this going after a few days of allowing the extra moisture to dry up. I should probably have a bigger bucket, but I'm sure after some extended tweaking, all will be good. A few more days will be telling...

**Comment by jeroenterheerdt** [comment]
thanks for letting me know. I am curious to what things you see in the hourly numbers that drive you crazy. this is what I am seeing: 
![image](https://user-images.githubusercontent.com/8188990/85050294-b45e5a00-b14a-11ea-9321-fe2d4285e07b.png) and it is pretty consistent (ok, couple of spikes yesterday, but to be fair, I was doing reboots at that time). but other than that it seems to follow a pretty nice pattern.

**Comment by MYeager1967** [comment]
It's just the fact that it changes every hour and doesn't seem to reflect on the daily change. The logs are where the numbers really get interesting but since I don't know how they're generated and used, the end result is what I'm looking at. The hourly adjusted run time sensor is predictable though. Mine follows the same pattern as yours. I've seen it at certain times of the day showing nearly double the base schedule numbers but by the end of the day, things are normal. That's the part that would drive me nuts trying to figure out. I'm guessing that with the hourly weather conditions, it's computing the run time needed if you ran the system right then. It appears to work as it should though, the end of day result looks close to what I expected for yesterday.

**Comment by stephenmetzger** [comment]
Wanted to provide an update. At the first 11 pm update things looked good, the daily adjusted time was at about 30 minutes which seems about right. But, at the second 11pm update, with no bucket reset, my daily adjusted spiked to ~21,000 minutes. 

I help off on updating, but will do so not and continue to monitor.

**Comment by jeroenterheerdt** [comment]
Let me know if you still have issues after updating!

**Comment by stephenmetzger** [comment]
Sorry, used the term "updating" multiple times to refer to two different processes. The "11pm updates" im referring to are the daily sensor update to the daily adjusted run time that happen at 11:00 by default. 

I just updated to the latest version of the integration, and my daily adjusted run time has gone down to 845 minutes. Still not great, but better than 21,000 minutes. Should I do a bucket reset?

**Comment by jeroenterheerdt** [comment]
in case you're interested, I created a Daily Sensor component (https://github.com/jeroenterheerdt/HADailySensor) that can help build a minimum and maximum temperature sensor so you can remove all ties with open weather map or other services if you are using them just to get minimum and maximum temperatures.

**Comment by jeroenterheerdt** [comment]
@stephenmetzger you should do a bucket reset yes, otherwise this will keep carrying the faulty calculations.

**Comment by MYeager1967** [comment]
I'm actually looking pretty good on the bucket issue this morning. 
I'm getting my minimum and maximum temps for the day the old fashion way, with math. :-) Is that all the new component is doing is tracking the high and low from the actual temps?

**Comment by jeroenterheerdt** [comment]
Yeah, it is essentially just a statistics sensor with the major difference being it will reset to 0 at 00:00 local time. If you already solved this differently no need to use the component. I was surprised it was not as easy as this so I built the component.

**Comment by MYeager1967** [comment]
It's a bit surprising that most of the weather providers don't provide the high/low for the day. I'm using AppDaemon for all of my automation and I just put together a quick program to grab the information from ClimaCell. It doesn't give you the high/low either so I just compare the temp to the recorded high/low and go from there. At midnight, I simply set both equal to the current temperature. I want to look into writing it as a custom component, but I know nothing about doing them. Gotta look at others examples and see what I learn.

**Comment by MYeager1967** [comment]
Why is there a beta version in the HACS registry? I wouldn't think you'd want a beta out for general consumption....

**Comment by jeroenterheerdt** [comment]
Where does it say beta? I used a and b before as I did minute increments

**Comment by MYeager1967** [comment]
Oh, Ok. I'm used to seeing a and b used for alpha and beta releases. Sorry.... :-)

**Comment by jeroenterheerdt** [comment]
I think it is time to close this thread.
