### ISSUE TITLE
 Error calculating zone Rear. You have configured forecasting but but there is no OWM API configured.

### ISSUE THREAD

**Issue by scubieman** [jeroenterheerdt/HAsmartirrigation#301]
### What happened?

I setup everything and tried setting up OWM API. I show the integration is setup and reporting  information back to Home assistant but still get this error.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:509
Integration: Smart Irrigation ([documentation](https://github.com/jeroenterheerdt/HASmartIrrigation), [issues](https://github.com/jeroenterheerdt/HASmartIrrigation/issues))
First occurred: September 29, 2023 at 11:00:00 PM (2 occurrences)
Last logged: September 30, 2023 at 11:00:00 PM

Error calculating zone Rear. You have configured forecasting but but there is no OWM API configured. Either configure the OWM API or stop using forcasting on the PyETO module.

Added Image of the subscription to OWM API.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/42748871/b57ff52a-6edf-4316-a025-93df88ae4181)

### How to reproduce

Set up smart irrigation with a area, try to set up a module and calculate areas

### Relevant log output

```shell
I posted above
```

### Which version are you running?

V2023.9.2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by gatonero** [comment]
Did you create an API key in OWM?

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/d8724506-43fc-401f-b687-5dab52ac9cbf)

**Comment by gatonero** [comment]
You don't need another integration. Smart Integration integrates OWM by it's own. Just copy your one of your existing API key into Smart integration.

![grafik](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/8248255/1a18a1e1-6c24-4499-9c36-1ca1ee83ae21)

**Comment by scubieman** [comment]
The issue was I was putting the open weather map API into Open weather Map integration... Once I put the API key into Smart irrigation it works great now. Thank you! Sorry for confusion.
