### ISSUE TITLE
Entity's attributes should not be translated to system locale

### ISSUE THREAD

**Issue by juacas** [jeroenterheerdt/HAsmartirrigation#303]
### What happened?

In a system with Spanish language configured the attributes of the entities are created in spanish. 
<img width="408" alt="image" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1656180/2f5f3767-da00-45e2-9c42-95811f8f3468">
That is, the attribute "Throughput " is named "Rendimiento", "Size" is named "Tamaño" and so on.

It is not that the user interface translates them but that the registed identifiers are translated.

If language is changed and a new zone is created, then the attributes of the new zone are named in the configured locale:

<img width="419" alt="image" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1656180/e026f37e-c3ac-4846-aca3-a402f4346e64">
The attributes should be in english and  have predictible names.

[config_entry-smart_irrigation-22c9669138bc8113970248f8d2f1ba18.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12834672/config_entry-smart_irrigation-22c9669138bc8113970248f8d2f1ba18.json.txt)

### How to reproduce

Change language and create a new zone.
Inspect the schema of the new zone..

### Which version are you running?

2023.9.2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Why not? This is by design.

**Comment by juacas** [comment]
Hi
I can think of some arguments:
- HA developer's guide seems recommend to define key-hardcoded  schema for the entities and to provide translations as i18n strings https://developers.home-assistant.io/docs/internationalization/core#entities
- a known-stable schema allows the community to contribute with better automations, i.e. blueprints.
- current implementation allows different zones to have different attribute names for the same value type in the same environment.
- I can see no reason why the keys of a technical data structure should depend on the casual locale configured at one moment.
- it is always better to let them frontend to translate things to the user. One never knows what language is going to use a use in the future. Why freeze the attribute names?
- this is the only integration that I've seen to do this way. It is not usual. That's why I through it was a bug.

However, this is only a suggestion to improve your, otherwise, super useful component.

**Comment by jeroenterheerdt** [comment]
that makes sense, I can try to implement the translation according to the link you shared. thanks.
