### ISSUE TITLE
Incorrect calculation including rain

### ISSUE THREAD

**Issue by elenril2** [jeroenterheerdt/HAsmartirrigation#304]
### What happened?

It appears that the bucket calculation incorrectly took into account rainfall. Over the last few days with no rain, the bucket has shrunk by about 2mm. Last day, my weather station recorded 9.
9mm of rainfall, and the bucket count was still 0.2mm off.

### How to reproduce

Submit a rainfall that exceed standard bucket.

### Relevant log output

```shell
Nothing unexpected in log.
Diagnostic file:
[config_entry-smart_irrigation-f2f59f4233cca0fb6e63c993212765fb.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12839181/config_entry-smart_irrigation-f2f59f4233cca0fb6e63c993212765fb.json.txt)

```

### Which version are you running?

v2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

I use a cumulative rain sensor from my weather station. In sensors groups I use the default, last of sensor values to calculate duration.
Evapotranspiration source is none, and in the modules section I choose PyETO not to estimate, so if I read the documentation correctly, it should use my solar radiation sensor.

Info from calculation:
```
Note: this explanation uses '.' as decimal separator and shows rounded values. Module returned Evapotranspiration deficiency of -0.2. Bucket was -4.1.
maximum bucket size is 20.0.New bucket value is [old_bucket]+[delta]=-4.1+-0.2=-4.3.
Since bucket < 0, irrigation is necessary.
To calculate the exact duration, the following steps were taken:
The precipitation rate is defined as [throughput]*60/[size]=18.0*60/106.0=10.2
The duration is calculated as abs([bucket])/[precipitation_rate]*3600=4.3/10.2*3600=1526
Now, the multiplier is applied. The multiplier is 1.0, hence the duration is 1526
Then, the maximum duration is applied. The maximum duration is 3600.0,
Finally, the lead time is applied. The lead time is 0.0, hence the final duration is 1526```

**Comment by RobinI30N** [comment]
The problem may be due to the fact that the integration works in UTC time. If you are in a different time zone, calculations may be made when the weather station resets the daily rainfall.
This is an integration error - it should be possible to set TZ to synchronize the activities of the weather station and integration.
I have the same problem.

**Comment by jeroenterheerdt** [comment]
@RobinI30N where you do see that we're tracking UTC time? We track intervals, which has nothing to do with timezones and sunrise, which should be automatically converted by HA to your timezone. Unless I am missing something I don't think this issue is related to UTC time.

**Comment by jeroenterheerdt** [comment]
@elenril2 rainfall does not equate bucket negative increase. Loads of other factors go in, including wind speed, temperature, etc. I can't spot any issue with the data in the diag file. So you had X mm rainfall, but maybe it was not windy? was it very sunny? warm?

**Comment by RobinI30N** [comment]
![Iryg1](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/72595369/af2119f9-b465-4975-abd3-ced57ff9cd90)
![iryg2](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/72595369/9352f90e-b400-424b-9477-5a05b27d0aef)
![inryg3](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/72595369/4a98c455-8d2d-4a39-a7df-dd7e49428166)
I took the screenshot a moment after manually performing the calculations.
The automatic calculation set for 23:00 will be performed the next day at 1:00. My WS resets the daily rainfall at 0:00.
You may need Maximum rainfall measurement.
I set the automatic calculation time to 9:00 p.m. which should perform the calculations at 11:00 p.m.
Maybe I'm wrong, I need time to check it thoroughly.

**Comment by jeroenterheerdt** [comment]
> In my case the calculation time is correct, I am currently UTC+2. I set this time to 23:55 so that it occurs just before the sensor data resets. In the case of RobinI30N, however, it may be a different error, because I think he is also in my time zone, and has a greater offset relative to UTC. ![image](https://user-images.githubusercontent.com/55240074/273594326-f694b743-3f3e-424c-874e-6f7f3aadea11.png) ![image](https://user-images.githubusercontent.com/55240074/273594259-7f64eda6-7d63-44b2-893b-0dd1c87da2c7.png)
> 
> I realize that irrigation time also takes into account factors other than rainfall, but I know from experience and daily tracking of calculations in V1 that in my case it is impossible to compensate for 10mm of rain. In summer, the highest readings per day were 4-5 mm subtracted from the bucket. In the last few days it was about 2mm. For reference, here is the debbug log from yesterday, made after the last data update before the calculation itself. [config_entry-smart_irrigation-f2f59f4233cca0fb6e63c993212765fb.json (5).txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/12846439/config_entry-smart_irrigation-f2f59f4233cca0fb6e63c993212765fb.json.5.txt) The results are a bit disturbed by multiple calculations just after midnight - this was probably caused by the changes I made in the automatic weather data update section (by the way, it is possible that these duplicate entries in the log from this period are also an error, as I understand it, because the dynamic script loaded each my value entry in this section). My delta yesterday was 0.015, which I also suspect may be wrong - it was a very damp and cold day, albeit with quite a lot of sun, but I don't think the bucket without rain would have decreased by more than 2-3mm (and there was over 4mm of rain - therefore the bucket should increase by approximately 2mm). Is there any simple way to check these calculations? Could you remind me of the calculation formula? As I understand it, Evapotranspiration from the module is first calculated and then compensated with potential precipitation?

There is no simple way to check unless you want to read the scientific papers... Quickest way is set up pyeto library in a test script and run the data from your diagnostic file through it after applying aggregates. That's what I do. Now we have a weird issue with precip when using OWM, so maybe that caused it?

**Comment by RobinI30N** [comment]
![iryg](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/72595369/e20f25ce-73e0-49b3-8ede-6bcbabe26d7d)

I have TZ set correctly in HA.
The installation is on Docker and UTC is actually set there.
It has always worked properly and all HA schedules execute correctly. There were also no problems with irrigation of the V1.

**Comment by jeroenterheerdt** [comment]
> ![iryg](https://user-images.githubusercontent.com/72595369/273669688-e20f25ce-73e0-49b3-8ede-6bcbabe26d7d.PNG)
> 
> I have TZ set correctly in HA. The installation is on Docker and UTC is actually set there. It has always worked properly and all HA schedules execute correctly. There were also no problems with irrigation of the V1.
> 
> Thank you

Which version of the v2 are you running?

**Comment by RobinI30N** [comment]
Yes,, last v2

**Comment by jeroenterheerdt** [comment]
> Yes,, last v2

For me to be able to change this down I need to get a diag file from you or at minimum the actual version number. Not 'last'.

**Comment by RobinI30N** [comment]
Sorry, the calculations are performed at the correct local time.
Only the information from the zone tab is displayed incorrectly. This has no effect on operation. This confused me. 
I have v2023.9.2 - I will monitor its operation

**Comment by jeroenterheerdt** [comment]
> Sorry, the calculations are performed at the correct local time. Only the information from the zone tab is displayed incorrectly. This has no effect on operation. This confused me. I have v2023.9.2 - I will monitor its operation

thanks

**Comment by jeroenterheerdt** [comment]
Please open another bug instead of tagging on something else.

**Comment by jeroenterheerdt** [comment]
please open a new issue regardless as I need a new diag file and version info
