### ISSUE TITLE
API Key - paid or not?

### ISSUE THREAD

**Issue by sanderlv** [jeroenterheerdt/HAsmartirrigation#306]
Hi, according to the documentation I have created an open weather account and I have an API key created (it was auto created). I have not paid (yet) for it.

I searched in open issue and could only find 1 reference to my question.

The question is if If would really need to pay or I can also (test) with the initially created API key?

It is now more than 10 hours ago created but I have no luck in setting up the integration:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/16528916/034a26ef-3840-417f-a27e-07f79e2f460c)

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/16528916/bbae5ac1-8ef1-47b8-b08e-ecc8253b2811)

**Comment by gatonero** [comment]
Choose One Call API 3.0. You have 1,000 API calls per day for free For every call above you have to pay  0.0014 EUR per API call over the daily limit. That limit you will exceed with this integration if you call the weather update nearly every minute. That's not realistic and necessary.

**Comment by sanderlv** [comment]
Thanks, I have subscribed but still no avial.

I have:
ec46bf0c138e12aeddaa6db2f23341f5

But still no success in adding to HA.

I do need to use the (same) base API key right?

**Comment by sanderlv** [comment]
Got it going! just took time...

**Comment by jeroenterheerdt** [comment]
Yes, OWM takes a while to activate new keys. I think they say to wait four hours before trying your new key...
