### ISSUE TITLE
[Bug] v0.0.31: daily adjusted runtime type

### ISSUE THREAD

**Issue by posixx** [jeroenterheerdt/HAsmartirrigation#31]
When upgrading to v0.0.31 suddenly the daily runtime was multiplied by 100. As you changed percentage i opened integration options, saw 100 as percentage and did a save. After that the daily runtime was restored. I rebooted HA again to make sure it is not a startup bug but it wasn't: after restart daily runtime values was OK. 

But my irrigation automation is not running anymore. It fails with error:

2020-06-04 03:00:00 ERROR (MainThread) [homeassistant.components.automation] Automatische beregening: Error rendering Automatische beregening delay template: expected int for dictionary value @ data['seconds']

Here you see the multiply bug happened after upgrade to v0.0.31 and the current values which look good:

![image](https://user-images.githubusercontent.com/2280400/83726505-e5676680-a643-11ea-8278-d9541f4bf42b.png)

Code for delay which worked without issues until now:

- delay:
      seconds: '{{states("sensor.voortuin_daily_adjusted_run_time")}}'

**Comment by jeroenterheerdt** [comment]
interesting. what happens if you change `{{states("sensor.voortuin_daily_adjusted_run_time")}}` to `{{states("sensor.voortuin_daily_adjusted_run_time")|float}} ? Or was the error just temporarily?

**Comment by posixx** [comment]
nope doesn't work. Stanga as my used condition:

 condition:
  - above: '0'
    condition: numeric_state
    entity_id: sensor.voortuin_daily_adjusted_run_time

Is working...

**Comment by posixx** [comment]
Ok, change it to:

seconds: "{{states.sensor.voortuin_daily_adjusted_run_time.state|int}}"

Now it works again.

**Comment by jeroenterheerdt** [comment]
ok, thanks.
