### ISSUE TITLE
No Data points being collected

### ISSUE THREAD

**Issue by Schmee323** [jeroenterheerdt/HAsmartirrigation#315]
### What happened?

I have set up as per the wiki instructions and have attached OWM and my local weather sensors. I have 4 zones now and everything else configured but after 2 days am getting no change to time value, buckets and the number of data points is still 0.

### How to reproduce

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/74479013/8e2f77ad-b5bc-4b81-93dd-11b15bd50178)

[config_entry-smart_irrigation-b83e76ac3a928647a43a781715ce43c5.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/13295478/config_entry-smart_irrigation-b83e76ac3a928647a43a781715ce43c5.json.txt)

### Which version are you running?

v2023.9.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
oh, can you maybe disable/enable auto update and the related settings on the general settings page to force it to update the config?

**Comment by Schmee323** [comment]
I disabled and re-enabled auto update and it retreived 2 data points immediately. I will leave it run for a few hours and see if the data points increase. WIll let you know.
