### ISSUE TITLE
SolarRadiation error

### ISSUE THREAD

**Issue by foobar270** [jeroenterheerdt/HAsmartirrigation#317]
### What happened?

I get the following error in the logs.
In the sensor setup, I have used an ecowitt sensor for solar radiation.
<img width="418" alt="image" src="https://github.com/jeroenterheerdt/HAsmartirrigation/assets/13853653/edfb9e0b-776a-4765-be87-578ef5eb1769">

Logger: homeassistant
Source: custom_components/smart_irrigation/__init__.py:413
Integration: Smart Irrigation (documentation, issues)
First occurred: 28. November 2023 um 09:16:23 (175 occurrences)
Last logged: 15:16:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 381, in _async_update_all
    weatherdata = await self.merge_weatherdata_and_sensor_values(weatherdata,sensor_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 413, in merge_weatherdata_and_sensor_values
    _LOGGER.debug("merge_weatherdata_and_sensor_values, overriding {} value {} from OWM with {} from sensors".format(key,retval[key],val))
                                                                                                                         ~~~~~~^^^^^
KeyError: 'Solar Radiation'

What is wrong here?

[config_entry-smart_irrigation-560e84781dad61d65029898067e754ad.json.txt](https://github.com/jeroenterheerdt/HAsmartirrigation/files/13561659/config_entry-smart_irrigation-560e84781dad61d65029898067e754ad.json.txt)


### How to reproduce

happens every day/hour

### Relevant log output

```shell
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 381, in _async_update_all
    weatherdata = await self.merge_weatherdata_and_sensor_values(weatherdata,sensor_values)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 413, in merge_weatherdata_and_sensor_values
    _LOGGER.debug("merge_weatherdata_and_sensor_values, overriding {} value {} from OWM with {} from sensors".format(key,retval[key],val))
                                                                                                                         ~~~~~~^^^^^
KeyError: 'Solar Radiation'
```


### Which version are you running?

 v2023.11.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

_No response_

**Comment by jeroenterheerdt** [comment]
thanks for reporting this - this is a bug in the debug logging. It should not impact the function of the integration. Regardless, I will fix it in 2023.12.0
