### ISSUE TITLE
No Calculation possible

### ISSUE THREAD

**Issue by mikburnz** [jeroenterheerdt/HAsmartirrigation#329]
### What happened?

I filled all needed information  for zones and sensors. I want to use the PyETO Module. For my sensors i tried with sensors out of open weather. After this i added a new sensor group with manuell (fixed) values - only for test. then i want to calculate . nothing happens.

Did i missed something?

### How to reproduce

.

### Relevant log output

```shell
.
```

### Which version are you running?

V2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by mikburnz** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.74-haos",
    "supervisor": "2024.01.1",
    "host_os": "Home Assistant OS 11.5",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "smart_irrigation": {
      "version": "v2024.1.0",
      "requirements": []
    },
    "thermal_comfort": {
      "version": "2.2.2",
      "requirements": []
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "govee_lan": {
      "version": "1.0.0",
      "requirements": [
        "govee-led-wez>=0.0.15"
      ]
    },
    "mbapi2020": {
      "version": "0.9.9",
      "requirements": [
        "protobuf>=3.19.1"
      ]
    },
    "daily": {
      "version": "0.4.0",
      "requirements": []
    },
    "alarmo": {
      "version": "v1.9.14",
      "requirements": []
    },
    "iq_notify": {
      "version": "1.0.0",
      "requirements": []
    },
    "xiaomi_miot": {
      "version": "0.7.15",
      "requirements": [
        "construct>=2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "miele": {
      "version": "2024.1.0",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.7"
      ]
    },
    "aarlo": {
      "version": "0.8.1a10",
      "requirements": [
        "unidecode",
        "pyaarlo>=0.8.0.2"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.9.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "temperature_feels_like": {
      "version": "0.3.8",
      "requirements": [
        "colorlog==6.7.0",
        "ruff==0.1.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "smart_irrigation",
    "name": "Smart Irrigation",
    "codeowners": [
      "@jeroenterheerdt"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "panel_custom"
    ],
    "documentation": "https://github.com/jeroenterheerdt/HASmartIrrigation",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/jeroenterheerdt/HASmartIrrigation/issues",
    "requirements": [],
    "version": "v2024.1.0",
    "is_built_in": false
  },
  "data": {
    "config": {
      "entry_id": "12c14e23ea19137cd78f37e52d1aec31",
      "version": 1,
      "minor_version": 1,
      "domain": "smart_irrigation",
      "title": "Smart Irrigation",
      "data": {
        "name": "Smart Irrigation",
        "use_owm": false
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "Smart Irrigation",
      "disabled_by": null
    },
    "storage": {
      "config": {
        "calctime": "23:00",
        "units": "metric",
        "use_owm": false,
        "autocalcenabled": true,
        "autoupdateenabled": true,
        "autoupdateschedule": "hours",
        "autoupdatedelay": "0",
        "autoupdateinterval": "1",
        "autoclearenabled": true,
        "cleardatatime": "23:59",
        "starteventfiredtoday": false
      },
      "zones": [
        {
          "id": 0,
          "name": "Vorn",
          "size": 50.5,
          "throughput": 10.1,
          "state": "automatic",
          "bucket": 0,
          "old_bucket": 0,
          "delta": 0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 3600.0,
          "maximum_bucket": 50,
          "last_calculated": null
        },
        {
          "id": 1,
          "name": "Mitte",
          "size": 100.1,
          "throughput": 20.2,
          "state": "automatic",
          "bucket": 0,
          "old_bucket": 0,
          "delta": 0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 3600.0,
          "maximum_bucket": 50,
          "last_calculated": null
        },
        {
          "id": 2,
          "name": "Hinten",
          "size": 70.0,
          "throughput": 18.0,
          "state": "automatic",
          "bucket": 0,
          "old_bucket": 0,
          "delta": 0,
          "duration": 0,
          "module": 0,
          "multiplier": 1.0,
          "explanation": null,
          "mapping": 0,
          "lead_time": 0.0,
          "maximum_duration": 3600.0,
          "maximum_bucket": 50,
          "last_calculated": null
        }
      ],
      "modules": [
        {
          "id": 0,
          "name": "PyETO",
          "description": "Die Berechnung der Verunstungsrate basiert auf der FAO56-Formel aus der PyETO-Bibliothek.",
          "config": {
            "forecast_days": "1",
            "coastal": true
          },
          "schema": [
            {
              "type": "boolean",
              "name": "coastal",
              "optional": true,
              "default": false
            },
            {
              "type": "select",
              "options": [
                [
                  "1",
                  "EstimateFromTemp"
                ],
                [
                  "2",
                  "EstimateFromSunHours"
                ],
                [
                  "3",
                  "DontEstimate"
                ]
              ],
              "name": "solrad_behavior",
              "required": true,
              "default": "1"
            },
            {
              "type": "integer",
              "name": "forecast_days",
              "required": true,
              "default": 0
            }
          ]
        },
        {
          "id": 1,
          "name": "Static",
          "description": "Modul mit einer statisch konfigurierbaren Verdunstungsrate..",
          "config": null,
          "schema": [
            {
              "type": "float",
              "name": "delta",
              "required": true,
              "default": 0.0
            }
          ]
        }
      ],
      "mappings": [
        {
          "id": 0,
          "name": "Standard Sensorgruppe",
          "mappings": {
            "Dewpoint": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "13"
            },
            "Evapotranspiration": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "20"
            },
            "Humidity": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "50"
            },
            "Precipitation": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "0"
            },
            "Pressure": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "1000"
            },
            "Solar Radiation": {
              "source": "static",
              "sensorentity": "",
              "unit": "W/m2",
              "static_value": "1,15"
            },
            "Temperature": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "25"
            },
            "Windspeed": {
              "source": "static",
              "sensorentity": "",
              "unit": "",
              "static_value": "10"
            }
          },
          "data": [
            "[",
            "]"
          ],
          "data_last_updated": null
        }
      ]
    }
  }
}

**Comment by jeroenterheerdt** [comment]
You need to collect weather data to calculate with. The diag file shows no data. Did you collect it before calculating?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mikburnz** [comment]
yes i did. maybe bc i (re)installed it new. How long i have to collect the data? Minimum 24 hours?

**Comment by jeroenterheerdt** [comment]
Any. One data point should be enough. Try collecting and then generating a diag file to confirm it was collected.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
