### ISSUE TITLE
Change to minutes does not affect (unit_of_measurement)

### ISSUE THREAD

**Issue by mikburnz** [jeroenterheerdt/HAsmartirrigation#332]
### What happened?

If i change from seconds to minutes for the sensor (unit_of_measurement) then the value stays the same. 
How can i let me show the irrigation time in minutes instead of seconds?

### How to reproduce

.

### Relevant log output

```shell
.
```

### Which version are you running?

.

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

.

**Comment by DaTwo** [comment]
I do it with a helper template. I find keeping things in seconds form all the way till display is much easier to manage as no time formatting conversions need to take place till you want to display it.  I just use a helper template and use this to convert the seconds into "hours:minutes:seconds". Hope this helps. 

`{{ timedelta(seconds=states('sensor.your_sensor') | int(0)) }}`

**Comment by jeroenterheerdt** [comment]
See comment above. Closing as won't fix.
