### ISSUE TITLE
[REQ] soil moisture sensor

### ISSUE THREAD

**Issue by wokkieman** [jeroenterheerdt/HAsmartirrigation#335]
**Is your feature request related to a problem? Please describe.**
To my understanding the script calculates how much moisture should still be in the soil and doesn't use soil moisture sensors. Since the script could use evap sensors, why not use soil moisture sensors and skip the necessary calculation?

**Describe the solution you'd like**
Read soil moisture sensor, add weather forecast data to predict rain and evaporation. Suggest watering time based on flow rate.

**Comment by jeroenterheerdt** [comment]
soil moisture sensors are not reliable AFAIK, but we can definitely try to add those in.

**Comment by jeroenterheerdt** [comment]
The issue here is that soil moisture sensors give a percentage of how moist the soil is, so without a complete overhaul of this system we can't integrate them as there is way to map that to durations through mm or inches added.
