### ISSUE TITLE
Only 4 Zones possible

### ISSUE THREAD

**Issue by mikburnz** [jeroenterheerdt/HAsmartirrigation#342]
### What happened?

Want to integrate a 5th zone. Overwrite the last zone. Not more than 4 zone possible.

### How to reproduce

Try to add a 5th zone

### Which version are you running?

v2024.1.0

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Please do a clean install, removing the integration and confirming the storage file is gone. Then install the latest version. If still a bug please reopen and actually add the storage file (you checked the box but didn't add it).

I myself am using this integration with 6 zones so it's not a limitation.
