### ISSUE TITLE
[REQ] : question

### ISSUE THREAD

**Issue by fudu** [jeroenterheerdt/HAsmartirrigation#36]
Not feature request only 2 clarification questions:
1) rain: is considered precipitation happened or forecast value ?
2) for min and max temperature sensors: can I use same sensor used in temperature sensor and integration keeps max and min value or shoud I use two dedicated sensors one remembering min and other max value ?
Thanks

**Comment by jeroenterheerdt** [comment]
1. Either, but if you use a sensor it would make most sense to put actuals in, otherwise why use a sensor. OWM provides the forecast already as an alternative.
2. No, you need to specify those. Again, OWM provides these.

**Comment by fudu** [comment]
Yes, I'm trying with OWM but it's not so "realistic" in my area .... So:

1) If I get value from a pluviometer I can use it obviously as rain fallen ... but in this case forecast is from OWM ?
2) Ok

Thank you

**Comment by jeroenterheerdt** [comment]
If you have a rain sensor just connect that, no need to look at OWM to provide anything for precipitation. Personally I use smart weather custom component which has a station near my house.
