### ISSUE TITLE
Duplicate entities and events

### ISSUE THREAD

**Issue by vermut** [jeroenterheerdt/HAsmartirrigation#364]
### What happened?

I got 2 zones, but I see that there are 4 sensors created, active, with identical values inside. Also `smart_irrigation_start_irrigation_all_zones` is firing twice, at ~4:45 and ~5:10. 

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/779376/d90fa314-dd8f-451a-b5df-fe578b2e6d37)

Is this normal or some misconfig happened?

### How to reproduce

No idea, it just happened.

[config_entry-smart_irrigation-108b2f60c103360745b661304249d9dd.json](https://github.com/jeroenterheerdt/HAsmartirrigation/files/15282282/config_entry-smart_irrigation-108b2f60c103360745b661304249d9dd.json)

### Which version are you running?

v2024.4.5

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
did you change the name of the zones at all? I don't think this is an issue with the integration (there are only two zones in the diag file) and it does what is needs to do, so I am wondering if Home Assistant is not liking the names of the zones using the characters you used?

**Comment by vermut** [comment]
HomeAssistant is usually liberal with unicode names. But updating name to pure latin changed the picture:
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/779376/9ab846e3-c2d5-49e0-92a3-cd21d22ada51)

**Comment by vermut** [comment]
And after cleaning then up and renaming back the issue is gone.

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/779376/d4d91402-dab9-4fbb-b610-bbeb5caaf67e)

**Comment by jeroenterheerdt** [comment]
Insert-shrug-emoji here. No idea what caused this then. Can you confirm it works now?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
