### ISSUE TITLE
bug or feature?  Fixed precipitation not working

### ISSUE THREAD

**Issue by lucode** [jeroenterheerdt/HAsmartirrigation#365]
### What happened?

I use two zones and two sensor groups. Both sensor groups are almost the same, except one is having a fixed precipitation value of 0. This group I use for the covered Terrasse zone because there is no rain. I expected that the bucket will stay in the minus that way, because the only way the pots there get water is by irrigation. But in fact the buckets reacts similarly as the zone with precipitation from openweather.

[config_entry-smart_irrigation-715ac9d63547edeeecfbc0d03005dc33.json](https://github.com/jeroenterheerdt/HAsmartirrigation/files/15282940/config_entry-smart_irrigation-715ac9d63547edeeecfbc0d03005dc33.json)

### How to reproduce

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/2928740/3a3e1287-2c10-46ea-ae9c-8bae252c1eec)
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/2928740/f6b34b2e-5a96-4849-a7ae-0c87afbc8a90)

### Which version are you running?

 v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
the key word in what you wrote is "similarly". Precipitation is just one of the many parameters to the calculation. Just changing it to 0 has an impact, but not a huge impact on the bucket. As you have said yourself, the behavior is very similar to OWM, which makes sense as you just changed on of the 15 parameter

**Comment by lucode** [comment]
But what I'm supposed to do if I have a covered area or a greenhouse to avoid that the bucket is filling up. Just limit the bucket to zero? Doesn't have this a negative impact on the calculations.

**Comment by jeroenterheerdt** [comment]
Use the right sensors and trust the rest. I have a greenhouse myself and put sensors in it to get accurate readings. I also set precipitation and windspeed to zero for the greenhouse. That's it, it works.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
