### ISSUE TITLE
Cannot start the integration to HomeAssistant 2024.5.#

### ISSUE THREAD

**Issue by MrOrange1996** [jeroenterheerdt/HAsmartirrigation#366]
### What happened?

I have installed the Integration via HACS, without issues, latest Version v2024.4.3 
When I try to start the inetrgation using OpenWhetherMap checkbox activated, and entering my API key, it always gives me an error saying OPen Weather API Key or version wrong. I dont think it is an issue with the key because I use the OpenWeather integreation already, The key was created multiple days in the past, I even tried with another, very new account, waited 24h but still the key is not accespted. 

### How to reproduce

Add the Integration via HA, activate the checkbox to use OpenWeatherMap and enter any valid key or version. 

### Relevant log output

```shell
Log from HomeAssistant

Logger: custom_components.smart_irrigation.OWMClient
Quelle: custom_components/smart_irrigation/OWMClient.py:258
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 17:13:58 (4 Vorkommnisse)
Zuletzt protokolliert: 17:22:22

Cannot talk to OWM API, check API key.
```

### Which version are you running?

v2024.4.3 

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

I cannot create a diagnotic file because I cannot even start the Integration. Here a screenshot. 
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/123245795/c7a21881-fd05-4f17-af46-e1cfdcb73881)

**Comment by jeroenterheerdt** [comment]
I'd first check your OWM API key is actually enabled for the OneCall. Many are not (especially older ones). Just create a new one to be on the safe side, wait a few hours and try again.

**Comment by lsilberbauer** [comment]
I have the same problem, signed up for One Call API 3.0 Base Plan, but even newly generated keys are not accepted - pls let me know how I can help debugging this

**Comment by jeroenterheerdt** [comment]
Wait a few hours. It can take multiple hours for the key to be activated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeromio** [comment]
You can't use the simple, totally free version of OpenWeatherMaps. This works with the plain old OpenWeatherMaps integration, but not with Smart Irrigation. You have to actually subscribe and enter CC info etc. And all of the "wait a certain amount of time" caveats also apply.

**Comment by jeroenterheerdt** [comment]
Yes, as our readme clearly states. If only people actually read the info we put out there for once.. https://github.com/jeroenterheerdt/HAsmartirrigation?tab=readme-ov-file#getting-open-weather-map-api-key

**Comment by MrOrange1996** [comment]
Upgrading to "One Call API 3.0" license worked for me. It was not 100% clear for at the first place that this was really required since it worked plain OpenWeatherMaps integraion. 
Thanks

**Comment by lsilberbauer** [comment]
sorry for me it works as well as of this morning - it was just a matter of waiting
