### ISSUE TITLE
Adding zone overwrites existing one

### ISSUE THREAD

**Issue by laszlojakab** [jeroenterheerdt/HAsmartirrigation#369]
### What happened?

I'm experiencing with the integration and not using in "production" yet. I have added and deleted multiple zones. After some time I could not add new zone becaue when I added a new zone it overwrote an existing one.

Finally I have opened the storage file and I saw the ID of my zones was `3`, `4`, `5`, etc.. I changed them to `0`, `1`, `2` and restarted Home assistant. After that I was able to add new zone.

### How to reproduce

See above.

### Which version are you running?

v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
was this a fresh install or did you already have a previous version installed?

**Comment by fisiomacao** [comment]
Solved. Found the storage file, added zones in it and they appeared in my instance.

**Comment by jeroenterheerdt** [comment]
closing - there is no diag file.
