### ISSUE TITLE
zone entities are duplicated on integration reload

### ISSUE THREAD

**Issue by bulburDE** [jeroenterheerdt/HAsmartirrigation#372]
### What happened?

I've had the same behaviour as in #364. Each zone had two sensor entities.
e.g. my zone "Vorgarten" had the entities `sensor.smart_irrigation_vorgarten` and `sensor.smart_irrigation_vorgarten_2`. 

I tried to reproduce it and noticed that they duplicate when I click on "Reload" in the integration. Interestingly, after each reload there is on more entity added than before.
I clicked on reload and the number of entities for one zone increased from 17 to 23. The next time I reloaded the integration it went from 24 to 30.

After a restart all entities other than the main one are unavailable with the message `This entity is no longer being provided by the smart_irrigation integration. If the entity is no longer in use, delete it in settings.`

![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/6855903/4df10768-0b33-4b1d-8525-9d9f5784d547)

I assume that it is not only triggered by manually reloading the integration because I don't recall doing this before I first noticed that I had each entity twice.

The zones are only once in the smart_irrigation storage.
[config_entry-smart_irrigation-55a83ca033886c56dae74c7dfafdb914.json](https://github.com/jeroenterheerdt/HAsmartirrigation/files/15368090/config_entry-smart_irrigation-55a83ca033886c56dae74c7dfafdb914.json)

### How to reproduce

Settings->Devices & Services -> Integrations -> Smart irrigation -> Three dots -> Reload

### Which version are you running?

v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by bulburDE** [comment]
I deleted the "Smart Irrigation" entry in the Integrations view and after readding only one entity per zone is there. When I reload the integration it still duplicates them but at least this is a workaround to get rid of them without manually deleting them.

**Comment by bulburDE** [comment]
> I deleted the "Smart Irrigation" entry in the Integrations view and after readding only one entity per zone is there. When I reload the integration it still duplicates them but at least this is a workaround to get rid of them without manually deleting them.

This may only work when home assistant was not restarted after deleting the integration. Probably because the configuration/storage is still in cache. When deleting the integration, restarting home assistant and then readding the integration there were no entities at all. Configuration is empty like when I first installed it.

**Comment by mauritsivs** [comment]
i have the same, since 3 days my original zone entities have disapeared, and i have multiple new copies of them now, eg "sensor.smart_irrigation_trees_zone_2" and "sensor.smart_irrigation_trees_zone_3"

i have done nothing with the integration or settings of it for weeks...

**Comment by mistergyle** [comment]
Same here after updating to 2024.7.4

**Comment by jeroenterheerdt** [comment]
Please post your config

**Comment by mistergyle** [comment]
> Please post your config

https://drive.google.com/file/d/1fUxyn56uVcHVF7PCad3sQY1pVOplYSvh/view?usp=share_link

**Comment by adradr** [comment]
same here after upgrading to latest `v2024.7.5`

**Comment by jeroenterheerdt** [comment]
> same here after upgrading to latest `v2024.7.5`

Please open your own issue, this does not help at all.
