### ISSUE TITLE
Can't create more then 2 zones

### ISSUE THREAD

**Issue by lucode** [jeroenterheerdt/HAsmartirrigation#379]
### What happened?

When I try to add a new zone to 2 existing ones, it won't be created. What happens is that one of the old ones get renamed to the new name which I added for the new one. But it will reset all the parameters.
After trying several time, even with reloads in between, I ended up now having for smart.irrigation entities, but 2 of them are just doubles.    

```
Irrigation Fenceside
sensor.smart_irrigation_irrigation_fenceside
Smart Irrigation
Outdoor
—
Irrigation Fenceside
sensor.smart_irrigation_irrigation_fenceside_2
Smart Irrigation
Outdoor
—
Terrasse
sensor.smart_irrigation_terrasse
Smart Irrigation
Outdoor
—
Terrasse
sensor.smart_irrigation_terrasse_2
Smart Irrigation
Outdoor 
```
[config_entry-smart_irrigation-24-05-22.json](https://github.com/jeroenterheerdt/HAsmartirrigation/files/15404418/config_entry-smart_irrigation-24-05-22.json)

### How to reproduce

As described I can try several times to add new zones, but the result is the same. 

### Which version are you running?

 v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by mikburnz** [comment]
had the same problem. only solution was to delete and install new.

**Comment by lucode** [comment]
> had the same problem. only solution was to delete and install new.

And could you create more than 2 after that? Did you have a very long zone name. In my case I had used long names. And the one with the long name is the one that has been overridden.

**Comment by jeroenterheerdt** [comment]
should be fixed in latest beta
