### ISSUE TITLE
Error Handling Request

### ISSUE THREAD

**Issue by w1Ngx** [jeroenterheerdt/HAsmartirrigation#388]
### What happened?

I updated to 2024.6.0 and this error occurs when trying to update (didn’t update since May 25):

logger:%20aiohttp.server%0ASource%3A%20/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421%0AFirst%20occurred:%208:05:40%20AM%20(1%20occurrences)%0ALast%20logged:%208:05:40%20AM%0A%0AError%20handling%20request%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py%22,%20line%20452,%20in%20_handle_request%0A%20%20%20%20resp%20=%20await%20request_handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py%22,%20line%20543,%20in%20_handle%0A%20%20%20%20resp%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py%22,%20line%20114,%20in%20impl%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/security_filter.py%22,%20line%2092,%20in%20security_filter_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/forwarded.py%22,%20line%20210,%20in%20forwarded_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/request_context.py%22,%20line%2026,%20in%20request_context_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/ban.py%22,%20line%2088,%20in%20ban_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py%22,%20line%20199,%20in%20factory%0A%20%20%20%20response%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/auth.py%22,%20line%20295,%20in%20auth_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/headers.py%22,%20line%2032,%20in%20headers_middleware%0A%20%20%20%20response%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/helpers/http.py%22,%20line%2073,%20in%20handle%0A%20%20%20%20result%20=%20await%20handler(request,%20**request.match_info)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/data_validator.py%22,%20line%2073,%20in%20wrapper%0A%20%20%20%20return%20await%20method(view,%20request,%20data,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/smart_irrigation/websockets.py%22,%20line%20197,%20in%20post%0A%20%20%20%20await%20coordinator.async_update_zone_config(zone,%20data)%0A%20%20File%20%22/config/custom_components/smart_irrigation/__init__.py%22,%20line%201224,%20in%20async_update_zone_config%0A%20%20%20%20await%20self._async_calculate_all()%0A%20%20File%20%22/config/custom_components/smart_irrigation/__init__.py%22,%20line%20688,%20in%20_async_calculate_all%0A%20%20%20%20self.store.async_update_zone(zone.get(const.ZONE_ID),%20data)%0A%20%20File%20%22/config/custom_components/smart_irrigation/store.py%22,%20line%20505,%20in%20async_update_zone%0A%20%20%20%20if%20ATTR_NEW_MULTIPLIER_VALUE%20in%20changes:%0A%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0ATypeError:%20argument%20of%20type%20'coroutine'%20is%20not%20iterable%0A

### How to reproduce

click on calculate

### Relevant log output

```shell
logger:%20aiohttp.server%0ASource%3A%20/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421%0AFirst%20occurred:%208:05:40%20AM%20(1%20occurrences)%0ALast%20logged:%208:05:40%20AM%0A%0AError%20handling%20request%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py%22,%20line%20452,%20in%20_handle_request%0A%20%20%20%20resp%20=%20await%20request_handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py%22,%20line%20543,%20in%20_handle%0A%20%20%20%20resp%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py%22,%20line%20114,%20in%20impl%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/security_filter.py%22,%20line%2092,%20in%20security_filter_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/forwarded.py%22,%20line%20210,%20in%20forwarded_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/request_context.py%22,%20line%2026,%20in%20request_context_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/ban.py%22,%20line%2088,%20in%20ban_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py%22,%20line%20199,%20in%20factory%0A%20%20%20%20response%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/auth.py%22,%20line%20295,%20in%20auth_middleware%0A%20%20%20%20return%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/headers.py%22,%20line%2032,%20in%20headers_middleware%0A%20%20%20%20response%20=%20await%20handler(request)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/helpers/http.py%22,%20line%2073,%20in%20handle%0A%20%20%20%20result%20=%20await%20handler(request,%20**request.match_info)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/components/http/data_validator.py%22,%20line%2073,%20in%20wrapper%0A%20%20%20%20return%20await%20method(view,%20request,%20data,%20*args,%20**kwargs)%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/smart_irrigation/websockets.py%22,%20line%20197,%20in%20post%0A%20%20%20%20await%20coordinator.async_update_zone_config(zone,%20data)%0A%20%20File%20%22/config/custom_components/smart_irrigation/__init__.py%22,%20line%201224,%20in%20async_update_zone_config%0A%20%20%20%20await%20self._async_calculate_all()%0A%20%20File%20%22/config/custom_components/smart_irrigation/__init__.py%22,%20line%20688,%20in%20_async_calculate_all%0A%20%20%20%20self.store.async_update_zone(zone.get(const.ZONE_ID),%20data)%0A%20%20File%20%22/config/custom_components/smart_irrigation/store.py%22,%20line%20505,%20in%20async_update_zone%0A%20%20%20%20if%20ATTR_NEW_MULTIPLIER_VALUE%20in%20changes:%0A%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0ATypeError:%20argument%20of%20type%20'coroutine'%20is%20not%20iterable%0A
```

### Which version are you running?

2024.6.0

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by omenek159** [comment]
@jeroenterheerdt in _init_.py:684 calculate_module must be awaited. That solves this problem.

**Comment by w1Ngx** [comment]
Maybe better to read:


Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py", line 199, in factory
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 295, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/websockets.py", line 197, in post
    await coordinator.async_update_zone_config(zone, data)
  File "/config/custom_components/smart_irrigation/__init__.py", line 1224, in async_update_zone_config
    await self._async_calculate_all()
  File "/config/custom_components/smart_irrigation/__init__.py", line 688, in _async_calculate_all
    self.store.async_update_zone(zone.get(const.ZONE_ID), data)
  File "/config/custom_components/smart_irrigation/store.py", line 505, in async_update_zone
    if ATTR_NEW_MULTIPLIER_VALUE in changes:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'coroutine' is not iterable

**Comment by jeroenterheerdt** [comment]
should be fixed in next beta
