### ISSUE TITLE
Few problems with sensors

### ISSUE THREAD

**Issue by omenek159** [jeroenterheerdt/HAsmartirrigation#398]
### What happened?

1. When HA is starting some sensors can be unavailable, but integration stores their states anyway and then throws error while calculating.

I fixed to this is by adding:
```
if new_state_obj.state in ["unknown", "unavailable"]:
    _LOGGER.debug(f"async_sensor_state_changed: wrong new state for {entity}: {new_state_obj.state}, ignoring.")
    return
```
after line 382 in __init__.py

2. When sensor state changes it is stored as string. I forced conversion to float, but I don't know if it can break other sensors that use integers instead of floats.
Fix:
```
float(new_state_obj.state),
```
at line 411.

### How to reproduce

Set sensor as data source.

### Which version are you running?

2024.6.4

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
thank you, these fixes look great. I will add them in.

**Comment by omenek159** [comment]
At lines 389 and 391 should be 'new_state_obj.state' :)
