### ISSUE TITLE
 Smart Irrigation does not show up in Hacs

### ISSUE THREAD

**Issue by xHirscHx** [jeroenterheerdt/HAsmartirrigation#40]
When i look in integrations in HACS there no listing for Smart Irrigation.
is there a repository i can add  for HA Add-on store

**Comment by jeroenterheerdt** [comment]
I can see it. Did you restart HA?

**Comment by posixx** [comment]
Browser cache! Clear your cache.

**Comment by xHirscHx** [comment]
I had hacs allready installed. Cant find it in IIntegration to install it.

**Comment by jeroenterheerdt** [comment]
I cannot help you, there must be an issue on your end.
