### ISSUE TITLE
[REQ] Can I get some help understanding how to run this next to HA as a container?

### ISSUE THREAD

**Issue by imle** [jeroenterheerdt/HAsmartirrigation#407]
**Is your feature request related to a problem? Please describe.**
Seems like this being an addon makes it impossible for HA to run properly. I would like to be able to run this as a docker container next to it so that I can use it!

**Describe the solution you'd like**
Guidance on how to make that work or for someone to do so for me. I can make the dockerfile and setup the service, I just need to know what to expose.

**Comment by jeroenterheerdt** [comment]
I am no expert on docker at all, so not sure. It is designed to be installed as a custom component to HA through HACS or manually. So you should be able to run it just fine as part of HA. So not sure why that is not an option for your install but I am afraid I can't help you with running this in a container as it's really not built for that.

**Comment by imle** [comment]
I appreciate the response! I think my confusion is coming from the setup process. It doesn't seem to show up in the sidebar so I assumed that it must need to be run separately. I'll see if I can figure it out and will post what I find here.
