### ISSUE TITLE
Can't tick the Coastal option and can't enter Forecast Days into the field box 

### ISSUE THREAD

**Issue by lennon101** [jeroenterheerdt/HAsmartirrigation#416]
### What happened?

Trying to add a new module and tick the coast field and enter a value into the Forcast days field and when I tick it, the tick is removed. The same happens with the Forcast Days field when I enter a value into the box. 

Diagnostics file:

[config_entry-smart_irrigation-9106bc7afb82a5204c0365e5615cf076.json](https://github.com/user-attachments/files/15879657/config_entry-smart_irrigation-9106bc7afb82a5204c0365e5615cf076.json)

### How to reproduce

1. Navigate to the MODULES tab in the Smart Irrigation dashboard of the UI 
2. Try to tick the Coastal tick box 
3. Try to enter a value either using the keyboard or the arrow keys 
4. Observe both changes removed 

Please see the screen recoarding below: 

https://github.com/jeroenterheerdt/HAsmartirrigation/assets/1709944/057495a6-b9e8-4acc-bb49-7c0fc48db690

### Which version are you running?

v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

NB: I am not running the latest version due to issue #408

**Comment by jeroenterheerdt** [comment]
unfortunately I cannot reproduce this on the latest version.
