### ISSUE TITLE
Can't delete a second sensor group

### ISSUE THREAD

**Issue by wauswaus** [jeroenterheerdt/HAsmartirrigation#418]
### What happened?

I added a second sensor group to play around a bit, however when I press the delete button of the newly created group it is not deleted. It disappears and then appears again.

### How to reproduce

Make a a second sensor group and press the delete button for this second group

### Relevant log output

```shell
nothing in logs
```

### Which version are you running?

 v2024.6.1, also on v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-5881d6768e50d37609c438ee283ca797.json](https://github.com/user-attachments/files/16020226/config_entry-smart_irrigation-5881d6768e50d37609c438ee283ca797.json)

**Comment by jeroenterheerdt** [comment]
doesn't repro
