### ISSUE TITLE
[REQ] calculate start time

### ISSUE THREAD

**Issue by eavanvalkenburg** [jeroenterheerdt/HAsmartirrigation#42]
**Is your feature request related to a problem? Please describe.**
The best time to use your sprinklers is right before sunrise, apparently that is best for your plants, and worst for any weeds, while it being still night is obviously better with regard to evaporation.

**Describe the solution you'd like**
Event thrown when you should start watering, the amount of time before sunrise that it needs to water.

**Describe alternatives you've considered**
Complex automations with sunset offset etc. but this code should have all the knowledge on what time to start, so why not use the eventing engine to let a automation pick it up.

**Additional context**
More complex is that I have three sprinklers for my grass, so currently have them scheduled one after another, which makes it a bit more complex, but that is not necessary for this.

**Comment by jeroenterheerdt** [comment]
Awesome ideas, should be doable. One question: I think you mean using the `sun` entity. Is that a default entity? I have not looked into it too much. Wondering if we can assume that thing is always going to be there or if we need to provide an option for users to plug in their own sunrise sensor.

**Comment by eavanvalkenburg** [comment]
it is a built-in integration, not sure if it is on by default, but probably most people using HA will have it on: https://www.home-assistant.io/integrations/sun/

**Comment by jeroenterheerdt** [comment]
new release in beta: https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.61 that implements this feature - please install and test :)

**Comment by jeroenterheerdt** [comment]
I am not seeing the event being fired, added more logging on v0.0.62

**Comment by posixx** [comment]
I don't see the event as available:

![image](https://user-images.githubusercontent.com/2280400/87028662-39371380-c1df-11ea-82b0-bbe8a66439f5.png)

Shouldn't it be in the list?

**Comment by jeroenterheerdt** [comment]
I am not sure if it should be in the list - a component does not have to register an event, you just fire it. Now, maybe it is just not firing.

**Comment by jeroenterheerdt** [comment]
I am seeing it getting fired in the logs:
![image](https://user-images.githubusercontent.com/8188990/87067404-d8044580-c1c8-11ea-8327-8be06e36482d.png)

(ignore the part that says Daily Adjusted Run Time, that is just an error in the logging)

I can confirm that the start event is getting fired:
![image](https://user-images.githubusercontent.com/8188990/87069403-fa4b9280-c1cb-11ea-9101-2abb2886a8af.png)

**Comment by posixx** [comment]
Yes i can confirm the event is triggered!
