### ISSUE TITLE
Issue on precipitation value after aggregations calculus

### ISSUE THREAD

**Issue by 101000** [jeroenterheerdt/HAsmartirrigation#422]
### What happened?

The value used for precipitation seems wrong (is it an average?), I configured the Maximum of value to be used but a different one is passed.
The Maximum value is 0.6 but in the log I see 0.219... Am I missing something?
Now I will try using the Last value calculated by the sensor which should be in any case the Maximum.

I noticed that changing the selection  (from max to last) made the "aggregate" attribute appear in the diagnostic JSON, which was missing before.

Below is my diagnostic file

[config_entry-smart_irrigation-a9f9685a8c90e013ade6c6a3e0788855 (4).json](https://github.com/user-attachments/files/16090928/config_entry-smart_irrigation-a9f9685a8c90e013ade6c6a3e0788855.4.json)

### How to reproduce

It will reproduce every day with precipitation > 0

### Relevant log output

```shell
2024-07-03 22:53:39.877 DEBUG (MainThread) [custom_components.smart_irrigation] apply_aggregates_to_mapping_data returns {'data_multiplier': 0.8937533837962963, 'Dewpoint': 16.905872102135906, 'Humidity': 78.62790697674419, 'Precipitation': 0.21951219512195122, 'Pressure': 1009.8906976744186, 'Solar Radiation': 13.757538461538463, 'Maximum Temperature': 22.3, 'Minimum Temperature': 18.0, 'Temperature': 20.78372093023256, 'Windspeed': 1.8699643206712566}
```

### Which version are you running?

v2024.4.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
not sure what is happening here - the code correctly sets the aggregate to max to precipitation if not configured

**Comment by 101000** [comment]
Still waiting for rain... forecast says It will be a very dry july here
In any case, can you confirm that using maximum in the apply_aggregates_to_mapping_data return I should have seen 0.6?

**Comment by jeroenterheerdt** [comment]
You should be using the max of the precipitation, yes.

**Comment by jeroenterheerdt** [comment]
found an issue after all, should be fixed in next release.
