### ISSUE TITLE
OpenWeatherMap sensor is not available

### ISSUE THREAD

**Issue by darnox** [jeroenterheerdt/HAsmartirrigation#428]
### What happened?

After updating to `v2024.7.4`, OpenWeatherMap is no longer available as a valid source in the Sensor Groups tab. The select box is struck out, and the configuration is not persisted

### How to reproduce

Update to `v2024.7.4` and navigate to the Sensor Groups tab

### Relevant log output

```shell
I'm unable to download the diagnostics file. After pressing the "Download Diagnostics" button, nothing happens. The button's URL directs to an inaccessible page with the error "401: Unauthorized"
```

### Which version are you running?

2024.7.4

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Anything in the logs? Also please paste the contents of the smart_irrigation storage file.

**Comment by darnox** [comment]
Looks like this is a browser's cache problem. After switching to another browser, the source was renamed to "Weather service" and seems to be working correctly. Removing browser's cache also helps.

Pay attention if the version displayed in the right top corner on Smart Irrigation page says `v2024.7.4` and not `v2024.6.1`
