### ISSUE TITLE
Daily Adjusted Runtime higher than Base Scheduled Index sometimes

### ISSUE THREAD

**Issue by alexmc1510** [jeroenterheerdt/HAsmartirrigation#44]
**Describe the bug**
Daily Adjusted Runtime higher than Base Scheduled Index sometimes. If I undestood well, Base Scheduled Index should be the maximum time.

**To Reproduce**
N/A

**Expected behavior**
Maximum daily adjusted runtime should be base scheduled index according documentation.

**Screenshots**
<img width="326" alt="dar" src="https://user-images.githubusercontent.com/36837980/87589157-1d52d680-c6e5-11ea-9c74-d9eb829c195d.png">

**Installed version**
0.0.29 via HACS

**Additional context**
N/A

**Comment by jeroenterheerdt** [comment]
nope - this is by design. BSI is just a reference value based on the reference ET values you provide. DART might be higher if your ET for the day is higher than the reference value. You will see water budget > 100% in those cases.
