### ISSUE TITLE
Cannot delete sensor group

### ISSUE THREAD

**Issue by jchristianj** [jeroenterheerdt/HAsmartirrigation#442]
### What happened?

Create new sensor group, then delete new sensor group. Sensor group re-appears on every page refresh.

### How to reproduce

Create new sensor group, then delete new sensor group. Sensor group re-appears on every page refresh.
[config_entry-smart_irrigation-c34d6b3034b69cc97400485090710263.json](https://github.com/user-attachments/files/16228571/config_entry-smart_irrigation-c34d6b3034b69cc97400485090710263.json)

### Which version are you running?

v2024.7.5

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by NormannK** [comment]
Same for me. Fresh installation of HA.
