### ISSUE TITLE
wetterdata ist not been deleted after calculation of one zone

### ISSUE THREAD

**Issue by digi303** [jeroenterheerdt/HAsmartirrigation#444]
### What happened?

the weather data is not deleted after the calculation. While this seems to work for all zones, it somehow does not work for a single zone.
I have a separate sensor group for my vegetable patch, which is calculated at 10.00 14.00 18.00.
While the watering time always increases, the number of weather measurements is not set to ‘0’ again. In addition, all daily values can still be found in the smart_irrigation.storage file.

### How to reproduce

click calculate on one zone an view the display of the weather-data - or look inside the smart_irrigation.storage file.

### Which version are you running?

2024.7.5

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

#
[config_entry-smart_irrigation-01J2VYDAX8MP4K106M0SHW7RAQ.json](https://github.com/user-attachments/files/16255039/config_entry-smart_irrigation-01J2VYDAX8MP4K106M0SHW7RAQ.json)

**Comment by jeroenterheerdt** [comment]
well.. this is actually by design. Why? because you might be using the sensor group on which the zone is based for another zone or might be intending to. so I don't think we should delete it.

**Comment by jeroenterheerdt** [comment]
but I think we can be smarter to detect if there are any zones dependent on the weather on the sensor group and if not, then delete it.
