### ISSUE TITLE
Getting: [async_update_all] Unable to find mapping with id: None

### ISSUE THREAD

**Issue by sdelmas** [jeroenterheerdt/HAsmartirrigation#449]
### What happened?

The initialization of the integration/reading of the weather forecast results in an error message. This happens with both supported weather services.

[config_entry-smart_irrigation-01J3AQ4Z4N5GQ3QGA9CJ1VBE8A.json](https://github.com/user-attachments/files/16378352/config_entry-smart_irrigation-01J3AQ4Z4N5GQ3QGA9CJ1VBE8A.json)

### How to reproduce

Basic setup, this is a fresh install. I added zones, and tried both Pirate Weather as well as Open Weather Map.

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:792
integration: Smart Irrigation (documentation, issues)
First occurred: July 24, 2024 at 8:48:17 PM (12 occurrences)
Last logged: 6:48:17 AM

[async_update_all] Unable to find mapping with id: None


followed by:

This error originated from a custom integration.

Logger: custom_components.smart_irrigation
Source: custom_components/smart_irrigation/__init__.py:796
integration: Smart Irrigation (documentation, issues)
First occurred: July 24, 2024 at 8:48:17 PM (12 occurrences)
Last logged: 6:48:17 AM

[async_update_all] No weather data to parse for mapping None
```

### Which version are you running?

2024.7.6

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by sdelmas** [comment]
One thing I noticed in the logs is this... could that be related?

2024-07-25 07:45:13.894 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False), please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues

**Comment by jeroenterheerdt** [comment]
It looks like you did not configure the sensor group for your zone so of course the zone cannot be calculated. The other warning is not related and is already reported in another issue.

**Comment by sdelmas** [comment]
Argh... apologies for reporting such an obvious user error. Yes, that was it... it's fine now. Thank you for spending your time building and supoprting this awesome integration. Very much appreciated.

**Comment by sdelmas** [comment]
User error...
