### ISSUE TITLE
Explanation: Force mode, force mode duration and maximum duration

### ISSUE THREAD

**Issue by alexmc1510** [jeroenterheerdt/HAsmartirrigation#45]
Hello,

Could you explain me quickly how force mode works and the difference between maximum duration and force mode duration? I have read the wiki page but it's not clear for me.

If I want to limit daily adjusted runtime for example to base scheduled index or another fix value, what should I do? 

Thanks in advance.

**Comment by jeroenterheerdt** [comment]
you should set `maximum duration` to limit the DART to this value, so if you set it to the value of BSI you end up with what you want. Force mode forces the irrigation to run and exactly to the time specified in `force mode duration`. The difference here is that the `maximum duration` just makes sure that the irrigation does not run _longer_ than that value, but does not force it to run. If the netto precipitation > 0 your irrigation will not run at all, unless you have force mode enabled and `force mode duration` set. hope that explains the difference.
