### ISSUE TITLE
No calculation during the day

### ISSUE THREAD

**Issue by pumabaer** [jeroenterheerdt/HAsmartirrigation#455]
### What happened?

I have enabled continuous calculation.
However, I notice that the bucket values do not change throughout the day.
I have disabled the automatic calculation of the irrigation duration because it leads to the side effect of being calculated "again?" in the evening.
I have all sensors except the one for solar radiation.

![IMG_4779](https://github.com/user-attachments/assets/906eecc9-dd65-4980-95f9-f7a6613b1cb6)
Here you can see how the bucket empties and then fills up due to rain during the night. After around 9 AM, there are no further calculations or changes. Today was sunny with temperatures around 24 degrees.

### How to reproduce

Enable and run continuous calculation.

### Which version are you running?

2024.7.8

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation.json](https://github.com/user-attachments/files/16404677/config_entry-smart_irrigation.json)

**Comment by pumabaer** [comment]
Here is another version with the "solar radiation" sensor enabled. 
Same problem...

[config_entry-smart_irrigation-with-solar-radiation.json](https://github.com/user-attachments/files/16415628/config_entry-smart_irrigation-with-solar-radiation.json)

**Comment by jeroenterheerdt** [comment]
that config wasn't very helpful - is there anything in the logs when you have continuous updated enabled that can tell us something?

**Comment by pumabaer** [comment]
No, nothing is shown in the log.
The only thing displayed about Smart Irrigation is:

```
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:184
Erstmals aufgetreten: 07:31:33 (13 Vorkommnisse)
Zuletzt protokolliert: 07:33:53

Detected that custom integration 'smart_irrigation' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/api/panel_custom/smart-irrigation", "/config/custom_components/smart_irrigation/frontend/dist/smart-irrigation.js", False)])`; This function will be removed in 2025.7 at custom_components/smart_irrigation/panel.py, line 32: hass.http.register_static_path(PANEL_URL, view_url, False), please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues

```

**Comment by pumabaer** [comment]
This is displayed approximately every 5 minutes.
I think it happens every time the weather station updates the data (which is every 5 minutes for me).

![image](https://github.com/user-attachments/assets/1a65b78c-f5ab-49be-b813-91a78facc4a1)

**Comment by jeroenterheerdt** [comment]
Seems like the calculation is not actually happening. Is this still happening on the latest version (7.10)?

**Comment by pumabaer** [comment]
I upgraded to 7.10 this morning, and I’m experiencing the same issue. I will try setting everything up from scratch later; maybe that will solve the problem.

As a first attempt, I have just set an update delay. Let’s see if anything changes.

**Comment by pumabaer** [comment]
So the delay didn’t work.

Earlier, I uninstalled everything and set it up again. So far, no success.



This is my current configuration. Do you see any mistakes I might have made?

The missing 0 in the forecast doesn’t seem to be a problem.

![image](https://github.com/user-attachments/assets/75a94b69-f54e-44ac-a45d-780b804075af)
![image](https://github.com/user-attachments/assets/ae11b634-3a68-44c2-9101-d69645bdcedb)
![image](https://github.com/user-attachments/assets/59e23450-eff6-4f0b-ae2f-bd08f1b1306b)
![image](https://github.com/user-attachments/assets/8d5bed61-2572-41c5-95b1-c514e1a5accb)
![image](https://github.com/user-attachments/assets/d8d1f867-bf21-4456-9d89-ca97d8124f1c)

**Comment by jeroenterheerdt** [comment]
I'd don't see any issues, except for you using continuous updates.... So there must a bug in there somehow.

**Comment by pumabaer** [comment]
Currently, I have switched back to daily calculations. When I have time, I will turn on continuous calculation again and keep an eye on the log.

**Comment by pumabaer** [comment]
One more idea comes to mind:
I get the log entry that can be calculated several times per second (whenever the weather station updates).
The values come with a slight delay (within milliseconds).
Could this possibly cause problems?

The interval for updating the weather data does not seem to have any effect on the continuous calculation, am I right?

**Comment by jeroenterheerdt** [comment]
Correct continuous updates happen as soon as the data arrives in the integration through HA, which will have a tiny delay. Automatic we there data update schedule has no impact on the zones that are continuously updated.

**Comment by pumabaer** [comment]
Heute Nacht habe ich folgende Fehler bekommen:

```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:274
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 3. August 2024 um 18:10:27 (45 Vorkommnisse)
Zuletzt protokolliert: 00:45:31

[pyETO: calculate_et_for_day] missing Pressure

```
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:266
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 3. August 2024 um 18:10:27 (17 Vorkommnisse)
Zuletzt protokolliert: 00:05:29

[pyETO: calculate_et_for_day] missing Maximum Temperature

```
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:262
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 3. August 2024 um 18:10:27 (17 Vorkommnisse)
Zuletzt protokolliert: 00:05:29

[pyETO: calculate_et_for_day] missing Minimum Temperature

```
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:270
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 00:00:00 (1 Vorkommnisse)
Zuletzt protokolliert: 00:00:00

[pyETO: calculate_et_for_day] missing Windspeed

```
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smart_irrigation.calcmodules.pyeto
Quelle: custom_components/smart_irrigation/calcmodules/pyeto/__init__.py:258
Integration: Smart Irrigation (Dokumentation, Probleme)
Erstmals aufgetreten: 00:00:00 (1 Vorkommnisse)
Zuletzt protokolliert: 00:00:00

[pyETO: calculate_et_for_day] missing Dewpoint

```

**Comment by jeroenterheerdt** [comment]
Is your automatic calculation still on and what time is that set to?

**Comment by pumabaer** [comment]
The automatic calculation is enabled again (after your last update where this is automatically detected during continuous calculation).

The calculation is set to 11:50 PM, and the weather data clearing is set to 11:59 PM.

**Comment by pumabaer** [comment]
Yesterday around 7 PM, the continuous calculation worked until about 11:30 PM (the weather data is cleared at 11:59 PM). 

From midnight until about 4 AM, calculations were also made (minimally, which is normal at night), but since 4 AM, no further calculations have been made.

It seems to be related to the time of day, possibly the sunlight duration. The calculations seem to work at night (although not entirely reliably).

![image](https://github.com/user-attachments/assets/3fca3c92-4098-47fe-86ac-d208008751f0)

**Comment by jeroenterheerdt** [comment]
interesting, can you maybe post logs from let's say 6:45-7:15 PM and around 4AM? I am wondering if indeed the solar radiance sensor is failing to provide a value triggering a bug.

**Comment by pumabaer** [comment]
Hi,
Here is the log since last night.

Unfortunately, I can’t get it out of HA any other way…
I hope it helps you.

![IMG_4862](https://github.com/user-attachments/assets/1571b355-77f9-405e-9b82-a289d4ec9ef5)

[https://we.tl/t-1Xq8eF0246](url)

**Comment by jeroenterheerdt** [comment]
the errors you logged above are expected if your weatherstation does not always provide all values, so I am changing those to warnings and adding extra explanation. I also noticed that the values are changing during the night, but only tiny changes are made, which is expected since there is no solar radiation as it's dark...

So I do believe that unless you are seeing something else it works as expected. For any further follow-up please indicate clearly in the message what config you have an if you are using continuous updates as I easily get confused between the various issues people have open.

Please install the latest version and try again. Thank you.

**Comment by pumabaer** [comment]
I had to create a new sensor group (with the same sensors) and a new zone (with the same settings).

But now the continuous calculation is running.

Version 2024.8.0
Continuous calculation: on

Thank you for your work!!

**Comment by jeroenterheerdt** [comment]
Not sure why you needed to recreate the zone and sensor group but glad it works now.
