### ISSUE TITLE
Smart Irrigation not showing up in the side tab

### ISSUE THREAD

**Issue by Erestes** [jeroenterheerdt/HAsmartirrigation#457]
### What happened?

I am not sure whether I am not understanding something or whether something is wrong with my setup. 
I had Smart Irrigation running on my old HA which died, I've set a brand new one and want to get Smart Irrigation back. 
Installed Smart Irrigation in HACS but it doesn't show up on the side panel and I don't know what is meant by " add the integration by searcing 'Smart Irrigation' in your configuration."

What should be done exaactly to get it working?

### How to reproduce

It simply doesn't show up after installing and via HACS & rebooting

### Which version are you running?

2024.7.8

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by Erestes** [comment]
It somehow did resolve by itself...

**Comment by jeroenterheerdt** [comment]
Browser cache issues.
