### ISSUE TITLE
After 0.0.64 update, adjusted hourly runtime becomes unavailable

### ISSUE THREAD

**Issue by alexmc1510** [jeroenterheerdt/HAsmartirrigation#46]
**Describe the bug**
After 0.0.64 update, adjusted hourly runtime becomes unavailable

**To Reproduce**
1. Update from 0.0.29 to 0.0.64
2. See error

**Expected behavior**
Sensor available

**Screenshots**
![image](https://user-images.githubusercontent.com/36837980/87595661-306aa400-c6ef-11ea-9aae-a0a6e90f2d1d.png)

**Installed version**
0.0.64

**Additional context**
Updated via HACS

**Comment by alexmc1510** [comment]
Removing integration and installing it from beginning worked for me.
This info could be useful for users.

**Comment by jeroenterheerdt** [comment]
thanks for letting me know and sorry for this - you made quite a jump from 0.0.29 to 0.0.64 :)
