### ISSUE TITLE
Displaying the calculated ET value

### ISSUE THREAD

**Issue by pumabaer** [jeroenterheerdt/HAsmartirrigation#462]
Is it possible to output the calculated ET value in an entity or an attribute? 
This way, we might be able to detect some errors or at least compare the values with online services to see if they match approximately.

**Comment by jata1** [comment]
I would love to see this too but I think it is tricky as I have asked previously.

I think the ideal solution would be for ET to be calculated by sensor group and this could then be linked to a zone to calculate bucket/duration

**Comment by jeroenterheerdt** [comment]
I could show the calculated ET value for the zones sensor group in an attribute to the sensor entity for that zone... the reason I did not do that is that I had to do a lot of rewiring for that value to make it to the frontend, but if you guys really want it, it can of course be done.

**Comment by pumabaer** [comment]
If it's that much work, it doesn't have to be done.
I just thought it might help in discovering any potential errors.

If I'm the only one with this request, you don't need to do it!

**Comment by jeroenterheerdt** [comment]
I think I was able to add it in v2024.8.0!
