### ISSUE TITLE
wrong bucket values

### ISSUE THREAD

**Issue by Marty56** [jeroenterheerdt/HAsmartirrigation#463]
### What happened?

I have a rain sensor which is measuring the irrigation in inches.
Unfortunately smart irrigation does not accept a helper as input for the irrigation sensor, so I had to use the original sensor and have set the unit to inches and have set the calculation method to "Maximum". 
The bucket is measured in mm and has currently the value of 2,4 mm although the irrigation sensor has just measured 16,51 mm. 

I would assume that the bucket also should have 16,51 mm because there has hardly any time passed between the rain and the calculation.

When a press the "calculator" symbol in the "Zonen" tab, I assume I can start a recalculation of the bucket. This symbol is pretty confusing because it is not shown as a button in the WebUi. I have pressed it several times but the value does not change. Hopefully my assumption is correct that this action is really starting the calculation.

In the log file it stated
"the log file states.

"Calculate zone Garten failed: no data available. Did you update before calculating?"

So probably I did not "update". Maybe this is the reason which the calculation makes no sense. 
So how do I update? I have pressed all those symbols but no reaction.

Please help.

### How to reproduce

N.a.

### Relevant log output

```shell
N.a
```

### Which version are you running?

 v2024.7.10

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[logfile.log](https://github.com/user-attachments/files/16478081/logfile.log)

**Comment by jeroenterheerdt** [comment]
The error is clear. Your bucket is not wrong. Do the update, then calculate. Keep in mind rain! = bucket. And... Read. The. Docs.
