### ISSUE TITLE
Zone not calculated when continuous updates are on and static value is used

### ISSUE THREAD

**Issue by JiriPrchal** [jeroenterheerdt/HAsmartirrigation#470]
### What happened?

Zone is not calculated when "Continuous updates for sensors" is yes and static value of wind = 0 in zone.

### How to reproduce

Set Continuous updates for sensors yes and wind static value 0.

### Relevant log output

```shell
WARNING (MainThread) [custom_components.smart_irrigation.calcmodules.pyeto] [pyETO: calculate_et_for_day] missing Windspeed. If you have continuous updates on this is expected as windspeed is not always available.
```

### Which version are you running?

2024.8.0

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by JiriPrchal** [comment]
[config_entry-smart_irrigation-47e9ce91b4e69ceb804dddaab66e1dc6.json](https://github.com/user-attachments/files/16622461/config_entry-smart_irrigation-47e9ce91b4e69ceb804dddaab66e1dc6.json)

**Comment by jeroenterheerdt** [comment]
somehow you got into a state where the config is confused: it still says sensor is the source for the windspeed but it also has a static value. It's not supposed to be that way.
from your config:
```
 "Windspeed": {
              "source": "sensor",
              "sensorentity": "sensor.wind_speed",
              "unit": "",
              "static_value": "0"
            }
```

a valid config would be:
```
"Dewpoint": {
            "source": "static",
            "sensorentity": "input_number.test",
            "static_value": ""
          },
```

however, the sensorentity still being there is likely the culprit, so I'll change the logic in the next beta to wipe the sensor entity as well.

**Comment by jeroenterheerdt** [comment]
please install v2024.8.1-beta-10 and feel free to re-open if the issue still exists

**Comment by JiriPrchal** [comment]
It works now, thanks.
