### ISSUE TITLE
"Invalid Source" Message when trying to add a sensor

### ISSUE THREAD

**Issue by 4irm** [jeroenterheerdt/HAsmartirrigation#472]
### What happened?

As soon as I try to add a sensor...

![image](https://github.com/user-attachments/assets/649342b2-3e56-4bd5-bd29-efbf19adc5bd)

...I am getting this Error Message...

![image](https://github.com/user-attachments/assets/5c4d695a-b8fc-451d-864c-76ee9d6a009f)

I am on the latest beta. When I initially setup your integration I was able to add sensors.

Thanks!

[config_entry-smart_irrigation-09843118d6bab8742e0867528acd3656.json](https://github.com/user-attachments/files/16660026/config_entry-smart_irrigation-09843118d6bab8742e0867528acd3656.json)

### How to reproduce

Click on adding sensor...

### Relevant log output

```shell
I enabled to logger for smart irrigation; but this is the only record that could relate (but I am not sure)

Logger: homeassistant.util.json
Source: helpers/deprecation.py:197
First occurred: 11:23:59 AM (23 occurrences)
Last logged: 2:11:32 PM

json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
```

### Which version are you running?

v2024.8.1-beta-8

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Install 2024.8.0 please.

**Comment by 4irm** [comment]
> Install 2024.8.0 please to check if it works there.

Thanks for the prompt feedback - I removed your integration and re-downloaded the latest non-beta version - now it is working fine, obviously a bug on v2024.8.1-beta-8

**Comment by jeroenterheerdt** [comment]
I see there is an issue here...you did not start your sensor with `sensor`:

`
"Humidity": {
              "source": "sensor",
              "sensorentity": "home_temperatur_luftfeuchtigkeitssensor_aussen_humidity",
              "unit": ""
            },
`

Regardless, I will introduce a handling for that in the next version, but it should work right now if you just included the `sensor.` part.

**Comment by 4irm** [comment]
> I see there is an issue here...you did not start your sensor with `sensor`:
> 
> `"Humidity": { "source": "sensor", "sensorentity": "home_temperatur_luftfeuchtigkeitssensor_aussen_humidity", "unit": "" },`

Thank you. That worked, strange however that it worked without "sensor." in one of the previous versions...

**Comment by jeroenterheerdt** [comment]
that should not have been the case, but likely the validation on whether or not the source existed was not in that previous version yet, so it never told you it didn't work.
