### ISSUE TITLE
Error setting up entry Smart Irrigation for smart_irrigation

### ISSUE THREAD

**Issue by Erwiiinst** [jeroenterheerdt/HAsmartirrigation#473]
### What happened?

The integration reports it has fault (smart irrigation is not shown in the menu). downloading a diagnostic file is not possible. I don't know what is wrong. Please help.

### How to reproduce

after each start-up of HA.

### Relevant log output

```shell
Logger: homeassistant.config_entries
Bron: config_entries.py:604
Eerst voorgekomen: 18:31:46 (1 gebeurtenissen)
Laatst gelogd: 18:31:46

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 77, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 714, in async_get_registry
    data = await task
           ^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 709, in _load_reg
    await registry.async_load()
  File "/config/custom_components/smart_irrigation/store.py", line 312, in async_load
    inst = m(self.hass, module[MODULE_DESCRIPTION], modconfig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/calcmodules/static/__init__.py", line 25, in __init__
    super().__init__(
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 26, in __init__
    raise e
  File "/config/custom_components/smart_irrigation/calcmodules/calcmodule.py", line 24, in __init__
    self._schema(config)
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 549, in validate_dict
    return base_validate(path, data.items(), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 382, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['delta']
```

### Which version are you running?

V2024.8.1-beta-8

### Diagnostics file
![2024-08-19 184351](https://github.com/user-attachments/assets/bec793a0-6b44-4310-bfe6-81059dad896e)
- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Please install versions 2024.8.0

**Comment by Erwiiinst** [comment]
Also version 2024.8.0 had the same issue

**Comment by Erwiiinst** [comment]
The integration has worked correctly till a moment in time. To resolve the issues I reinstalled the integration. You may consider this as a new installation, I think.

**Comment by jeroenterheerdt** [comment]
ok, thanks for letting me know, I will try to see what is going on

**Comment by jeroenterheerdt** [comment]
I can't reproduce this, can you post the contents of the storage file please? https://jeroenterheerdt.github.io/HAsmartirrigation/usage-troubleshooting.html

**Comment by mgomezdev** [comment]
I'm having the same issue.  I'm on a docker image for HA and don't see the diagnostic folder mentioned in the link and SmartIrrigstuon isn't showing up as an integration in the menu.

**Comment by Erwiiinst** [comment]
downloading a diagnostic file is not possible.
I can not find the smart_irrigation.storage not the configuration/.storage directory on the system.
What to do?

**Comment by jeroenterheerdt** [comment]
the storage directory is hidden. it should be under `config/.storage`.

**Comment by Erwiiinst** [comment]
[smart_irrigation.storage.txt](https://github.com/user-attachments/files/16728553/smart_irrigation.storage.txt)
as requested, attached the smart_irrigation.storage file

**Comment by jeroenterheerdt** [comment]
I see there is a bug here the delta on the `Static` module is somehow an empty string, not a number. I still can't reproduce this but will try to make sure it doesn't happen any more.

**Comment by Erwiiinst** [comment]
Latest beta solved this issue. Thx.
