### ISSUE TITLE
Open Weather Map API key not accepted

### ISSUE THREAD

**Issue by richardstone** [jeroenterheerdt/HAsmartirrigation#475]
### What happened?

I'm trying to setup the irrigation integration (completely new install, never used it before), but my OWM API key gets rejected by it, while the OWM Integration accepts my key.

Only log message is:
`[custom_components.smart_irrigation.weathermodules.OWMClient] Cannot talk to OWM API, check API key.`

### How to reproduce

Fresh install of HASmartIrrigation integration, trying to setup with Open Weather Map

### Which version are you running?

v2024.8.0

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
see https://jeroenterheerdt.github.io/HAsmartirrigation/installation-weatherservice.html#getting-open-weather-map-api-key - it can take hours before your API key is activated. If you already had an API key, test it using postman or something similar that it actually works.

**Comment by richardstone** [comment]
Solution was to subscribe for the One Call API that is free for 1000 calls/day, and limited it to a 1000 as well to aviod charges. Thanks for the quick response!
