### ISSUE TITLE
Current precipitation unit

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#482]
### What happened?

Shouldn’t the unit of measurement be “mm/h” instead of “mm”?

### How to reproduce

see above

### Which version are you running?

2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by darek-margas** [comment]
Well, I have sensor with mm/m so maybe it should be with various times?

**Comment by jeroenterheerdt** [comment]
> Well, I have sensor with mm/m so maybe it should be with various times?

Time is easy to convert using a template...

**Comment by jnsflschr** [comment]
Yes I agree. The naming "current" implicates some time relation because it iss not possible that it is instantaneous. Is this a mistake in the naming or in the description and usage? If the naming is correct, the expected aggregation should also be changed to "last".
