### ISSUE TITLE
Current precipitation source does not save

### ISSUE THREAD

**Issue by clau-bucur** [jeroenterheerdt/HAsmartirrigation#483]
### What happened?

Unable to save the "Current precipitation" source, it defaults to blank sensor.

### How to reproduce

Go to `Sensor Groups` page, and enter a sensor entity for the `Current precipitation`.
Then navigate away from this page, then navigate back.
The field is empty.

Even if I select another source, like `Weather service` or `Static value`, when navigating away and back, the values are reset to `Sensor` with empty `Sensor entity`.

https://github.com/user-attachments/assets/2cc1f494-3853-4905-8b38-0ac280d84123

### Which version are you running?

v2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

 Diagnostics file: [config_entry-smart_irrigation-54a29ef14b286103055503f5030ddb5a.json](https://github.com/user-attachments/files/16759785/config_entry-smart_irrigation-54a29ef14b286103055503f5030ddb5a.json)

**Comment by mattbruman** [comment]
My buckets haven't been updating for a few weeks and I noticed this as well. I created a new Sensor Group and noticed the Current precipitation sensor actually moves position in the list. I then set up my sensors in the new one and deleted the original sensor group and all the settings stayed. I am now waiting to see if my bucket updates now. Hopefully that fixed things.

**Comment by mattbruman** [comment]
> My buckets haven't been updating for a few weeks and I noticed this as well. I created a new Sensor Group and noticed the Current precipitation sensor actually moves position in the list. I then set up my sensors in the new one and deleted the original sensor group and all the settings stayed. I am now waiting to see if my bucket updates now. Hopefully that fixed things.

Well that didn't fix anything. My buckets are still showing empty. I have done all the sensors and they all have data in them but they are not filling and we have had no rain for 2 weeks.

**Comment by jeroenterheerdt** [comment]
@clau-bucur I can't reproduce this unfortunately. Can you install the latest version and try again?

**Comment by clau-bucur** [comment]
@jeroenterheerdt it works with 2024.10.1. I was able to set the `Current precipitation` to a sensor and it got saved. Thank you!
What is the recommended value for this sensor for the `Use the ___ of sensor values to calculate duration`?

**Comment by jeroenterheerdt** [comment]
see: https://jeroenterheerdt.github.io/HAsmartirrigation/configuration-sensor-groups.html
