### ISSUE TITLE
Dummy question: Precipitation value meaning

### ISSUE THREAD

**Issue by apocaliss92** [jeroenterheerdt/HAsmartirrigation#488]
This is most probably a very dummy question

What is exactly the precipitation value (not current precipitation)?
I have multiple sensors for it on my weather station, total (accumulated since the beginning), daily, monthly, hourly

I have assumed the total accumulated one, since it's an amount and not a ratio

Thanks for the clarification

**Comment by jeroenterheerdt** [comment]
https://jeroenterheerdt.github.io/HAsmartirrigation/configuration-sensor-groups.html

**Comment by jnsflschr** [comment]
I agree with him. The documentation is not clear enough regarding this.

**Comment by jeroenterheerdt** [comment]
It's the total precipitation that you want to take into account. Assuming you use Smart Irrigation normally (ie collect data during the day, calculate at night) then it would be total daily precipitation.

**Comment by jnsflschr** [comment]
That makes sense. Thank you for the clarification and the documentation update ;)
