### ISSUE TITLE
calculated irrigation time way off

### ISSUE THREAD

**Issue by pathia** [jeroenterheerdt/HAsmartirrigation#489]
### What happened?

Since some recent version I have crazy weird irrigation times. 

### How to reproduce

I have set 1800s as the maximum and when I had the previously configured 1 as a multiplier I had acceptable and logical watering times like 300 to 600 seconds. But since some recent version I kept getting 1800 seconds. So I tuned down my multiplier to 0.4 and now it does like 1500s. Which is still way too much.
How can I debug such an issue? 
I can (over the day) press calculate all zones but that also deletes the weather sensor info up untill now (right?).

[home-assistant_smart_irrigation_2024-09-01T18-06-01.182Z.log](https://github.com/user-attachments/files/16830054/home-assistant_smart_irrigation_2024-09-01T18-06-01.182Z.log)

### Relevant log output

```shell
Dunno
```

### Which version are you running?

v2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

none

**Comment by pathia** [comment]
![Screenshot_20240901_224049_Home Assistant](https://github.com/user-attachments/assets/5510311e-667d-44e5-941f-91dc64a28fb7)
For example the last few days of irrigation seconds versus the bucket level.

**Comment by pipacsba** [comment]
I have the same experience with the 2024.8.2. When I set the Drain rate to the proposed 52mm/h, I always got the maximum irrigation duration (1800s in my case too), deleting the drain rate value set back to ~ 600s. The weather conditions were quite the same.

**Comment by pathia** [comment]
Did you actually empty the field or did you configure zero as drain rate?

**Comment by pipacsba** [comment]
I have actually emptied the field. Starting today I am trying to slowly increase the drain rate to see what happens. :-)

**Comment by pathia** [comment]
@pipacsba I'm afraid you will now hit the drainage rate null issue as discussed in: https://github.com/jeroenterheerdt/HAsmartirrigation/issues/481

**Comment by pipacsba** [comment]
@pathia : it's fixed in 2024.8.2 based on the release note - I was lucky.

**Comment by pathia** [comment]
I mean if you empty the field I would expect a null value again.
But pls let me know how it worked out .

**Comment by pipacsba** [comment]
2024.8.2 change log contains: "if drainage rate is not set, make sure sensor renders correctly (bug from v2024.8.1)"
So this null value issue is not effected me - as I wrote drain rate empty value was working for me and resulted ~600s irrigation times (maybe a bit lower than before experiences, but acceptable for me). I used it for two days without issue, now I am trying to increase the drain rate - today starting at 5 mm/h to see the effect.

**Comment by pipacsba** [comment]
Also with drain rate 5mm/h the estimated irrigation time was over 1800s instead of the expected ~600s. So for me right now only the empty value works. I do not understand why the drain rate has so significant value here, there were no rain in months.

**Comment by jeroenterheerdt** [comment]
> Also with drain rate 5mm/h the estimated irrigation time was over 1800s instead of the expected ~600s. So for me right now only the empty value works. I do not understand why the drain rate has so significant value here, there were no rain in months.

https://jeroenterheerdt.github.io/HAsmartirrigation/configuration-zones.html for info on drainage rate.
