### ISSUE TITLE
Soil Moisture Sensors for Irrigation Adjustment

### ISSUE THREAD

**Issue by cappa88** [jeroenterheerdt/HAsmartirrigation#492]
I'm back with a new suggestion/question.
I read on the community forum that no soil moisture sensor is used because it's not useful for calculating evaporation, which I fully understand. However, I was wondering if it could still be used to monitor the irrigation process itself, perhaps automatically adjusting the multiplier.

For example: a drop in water pressure makes the set flow rate unreliable, so the amount of water delivered is no longer sufficient to replenish evaporation. Over time, this can cause soil to dry out and lead to a decrease in the daily/weekly average soil moisture. At this point, thanks to the moisture sensor, the system could detect the issue and adjust the multiplier accordingly to water for a longer duration.

I'm not sure if I've been clear or if what I'm saying makes sense scientifically in terms of soil behavior.

**Comment by lynxchat4** [comment]
I have soil sensors and there was a problem with pressure. It is not visible at all from the sensors. It is better to install a water meter and watch the water consumption to avoid such a situation.

**Comment by jeroenterheerdt** [comment]
Soil moisture sensors are not going to help you here.
