### ISSUE TITLE
Wrong calculation in Windspeed

### ISSUE THREAD

**Issue by lynxchat4** [jeroenterheerdt/HAsmartirrigation#499]
### What happened?

Incorrectly saves data received from the weather station.
I noticed that there was very little watering. I made a test zone that receives data only from OpenWeatherMap. The difference in the calculation by the weather station in the yard (WittBoy 2000) and the data from the Internet was from 150% to 250%.
After looking at the diagnostic data, it became clear that the data from the weather station is recalculated and saved incorrectly.
I identified the "coefficients". They are always the same.
For example
"Windspeed": 0.08888888888888896,       REAL   3.2 km/h         koeff  *36

### How to reproduce

The weather station gives data in the following units:
Windspeed       - km/h
Sensor Groups show correct units of measurement.

### Relevant log output

```shell
3 values ​​from different zones at the same time.
Solar radiation is signed from sensor data

OpenWeatherMap

          {
              "Windspeed": 4.487706451007664,
              "Pressure": 1023.0,
              "Humidity": 36,
              "Temperature": 16.99,
              "Dewpoint": 1.83,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-09-27T09:53:15.707328"
            },
            {
              "Windspeed": 4.487706451007664,
              "Pressure": 1023.0,
              "Humidity": 36,
              "Temperature": 16.99,
              "Dewpoint": 1.83,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-09-27T10:08:15.667634"
            },
            {
              "Windspeed": 5.235657526175609,
              "Pressure": 1022.0,
              "Humidity": 32,
              "Temperature": 18.99,
              "Dewpoint": 1.94,
              "Current Precipitation": 0.0,
              "Precipitation": 0.0,
              "retrieved": "2024-09-27T10:53:15.696549"
            }

------------------------------------------
Meteo station 


          "Dewpoint": 3.8,
              "Humidity": 41.0,
              "Precipitation": 0.0,
              "Pressure": 1003.6,
              "Solar Radiation": 10.576656000000002,  
              "Temperature": 17.2,
              "Windspeed": 0.138888888888889,          REAL  5 km/h        *36
              "retrieved": "2024-09-27T09:53:15.337059"
            },
            {
              "Dewpoint": 3.9,
              "Humidity": 40.0,
              "Precipitation": 0.0,
              "Pressure": 1003.5,
              "Solar Radiation": 9.731232, 
              "Temperature": 17.6,
              "Windspeed": 0.08888888888888896,       REAL   3.2 km/h 
              "retrieved": "2024-09-27T10:08:15.343218"
            },
            {
              "Dewpoint": 4.3,
              "Humidity": 38.0,
              "Precipitation": 0.0,
              "Pressure": 1003.3,
              "Solar Radiation": 11.817792,  
              "Temperature": 18.9,
              "Windspeed": 0.138888888888889,         REAL   5
              "retrieved": "2024-09-27T10:23:15.339815"
```

### Which version are you running?

 v2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[!Statistic.json](https://github.com/user-attachments/files/17181497/Statistic.json)

**Comment by lynxchat4** [comment]
> Did you read this? We convert the wind speed and solar radiation to certain units and that's what you're seeing. https://jeroenterheerdt.github.io/HAsmartirrigation/usage-troubleshooting.html#reading-the-diagnostic--storage-file

Yes I read this troubleshooting.
But calculation windspeed have tenfold difference.

"Windspeed": 0.08888888888888896,       REAL   3.2 km/h 
0.08888 m/s = 0,319968 km/h, but real wind speed 3.2 km/h

"Windspeed": 0.138888888888889,          REAL  5 km/h
0.1388 m/s = 0,499968 km/h but real wind speed 5 km/h



Solar Radiation in MJ/day/m2 calculated correctly.  I have 50% off solar radiation sensor.

**Comment by lynxchat4** [comment]
> Did you read this? We convert the wind speed and solar radiation to certain units and that's what you're seeing. https://jeroenterheerdt.github.io/HAsmartirrigation/usage-troubleshooting.html#reading-the-diagnostic--storage-file

I find problem in code. In "const.py"

# OTHER FACTORS
KMH_TO_MS_FACTOR = 0.0277777777777778  # kmh * factor = ms
MS_TO_KMH_FACTOR = 3.6  # m/s * factor = kmh

Wrong KMH_TO_MS_FACTOR.
Must be 0.277777777777778

**Comment by jeroenterheerdt** [comment]
Great catch, not sure what happened there. Can you make a PR?

**Comment by lynxchat4** [comment]
This is my first time doing this. I hope everything is correct.
https://github.com/jeroenterheerdt/HAsmartirrigation/pull/502

**Comment by jeroenterheerdt** [comment]
it looks great, thanks for doing this. I don't have a lot of time right now, but I do have to merge PRs and hopefully make a new release soon!
