### ISSUE TITLE
[feature request] Support for Hozelock Smart Valves

### ISSUE THREAD

**Issue by Dinth** [jeroenterheerdt/HAsmartirrigation#5]
Hey. It would be nice to add some kind of support for Hozelock smart valves.
The problem with them is that they dont necessarily allow manual opening and closing of valves. Instead there's one preset length of irrigation which can happen once per day at set time or twice at sunrise and sunset and this irrigation time can be adjusted daily (using a HA script) by round numbers like 25%, 50%, 75%,150%, 200% percent.

**Comment by jeroenterheerdt** [comment]
hi @Dinth - I am not familiar with Hozelock smart valves neither do I see an integration in HA. How do you interact with them? Can you share some more specifics? I am thinking you could just use the value of `sensor.smart_irrigation_daily_adjusted_run_time` and plug it into whatever you have currently to tell the valves to run for that long. Just guessing here.

**Comment by Dinth** [comment]
Hi and thanks for the reply.
sensor.smart_irrigation_daily_adjusted_run_time may actually be what i need. Sorry for missing it earlier.
Basically Hozelock valves can be controlled using Restful API:
  hozelock_adjust:
    url: 'https://hoz3.com/restful/support/hubs/{{ hub_id }}/controllers/actions/adjust'
    method: POST
    payload: '{"controllerIDs":[{{ controler_id }}],"duration":{{ duration }},"wateringAdjustment":{{ percentage }}}'
    content_type:  'application/json'

  hozelock_unadjust:
    url: 'https://hoz3.com/restful/support/hubs/{{ hub_id }}/controllers/actions/unadjust'
    method: POST
    payload: '{"controllerIDs":[{{ controller_id }}]}'
    content_type:  'application/json'

**Comment by jeroenterheerdt** [comment]
ok, so you could build an automation that looks much like what I have [here](https://github.com/jeroenterheerdt/HAsmartirrigation#example-automation-1-one-valve-potentially-daily-irrigation) that in the actions calls `hozelock_adjust` and then `hozelock_unpause` (assuming that unpause starts the sprinkler - weird name...), right?

**Comment by Dinth** [comment]
Adjust/unadjust are adjusting watering duration by XX percent for next XX days and pause/unpause are switching off watering for XX days (for example when its raining)

**Comment by jeroenterheerdt** [comment]
interesting. can you read the current irrigation time value from somewhere? I am thinking you could do something like this: in your automation call `hozelock_adjust` with: the percentage increase/decrease as indicated by `sensor.smart_irrigation_daily_adjusted_run_time` compared to current irrigation time rounded to a whole number.

**Comment by Dinth** [comment]
So basically ive got this:
`{"errorCode":0,"controller":{"name":"Backyard lawn sprinkler","image":null,"controllerID":"0","scheduleID":"default_xxxxxxx","schedule":{"scheduleID":"default_HVV7NE","name":"Sunrise and Sunset Watering Schedule","description":null,"scheduleDays":{"Monday":{"dayOfWeek":"Monday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Thursday":{"dayOfWeek":"Thursday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Friday":{"dayOfWeek":"Friday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Sunday":{"dayOfWeek":"Sunday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Wednesday":{"dayOfWeek":"Wednesday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Tuesday":{"dayOfWeek":"Tuesday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]},"Saturday":{"dayOfWeek":"Saturday","wateringEvents":[{"startTime":-2000,"endTime":598000,"duration":600000,"enabled":true},{"startTime":-1000,"endTime":599000,"duration":600000,"enabled":true}]}}},"hasWaterNowEvent":false,"pause":null,"adjustment":null,"waterNowEvent":null,"currentWateringEvent":null,"nextWateringEvent":{"startTime":1590177000000,"endTime":1590177600000,"duration":600000,"enabled":true},"lastCommunicationWithServer":1590175924000,"nextCommunicationWithServer":1590177360000,"batteryStatus":"LOW","signalStrength":"GOOD","overrideScheduleDuration":null,"isChildlockEnabled":false,"isWatering":false,"isPanelRemoved":false,"isTested":true,"isAdjusted":false,"isScheduleUpToDate":true,"isPaused":false},"currentTime":1590176529242}`

**Comment by jeroenterheerdt** [comment]
Hard for me to help here, but I think duration is returned in milli seconds? You should be able to use that and create the calculations you need.

**Comment by Dinth** [comment]
> Hard for me to help here, but I think duration is returned in milli seconds? You should be able to use that and create the calculations you need.

yes, the thing is that duration is set so it doesnt change. I will try to tinker with it thanks!
