### ISSUE TITLE
Error 500 if I change Mappings

### ISSUE THREAD

**Issue by Bjoern3003** [jeroenterheerdt/HAsmartirrigation#500]
### What happened?

If I change some settings on the Mappings Page, the Addon tried to update by using Ajax Request. This results in an Error 500.

After that, I downgraded to v2024.7.2. Here I can set all Mappings. After that I upgraded back to the latest Version :-)

I this a known Bug?

[config_entry-smart_irrigation-01J8349TQPRXWD8WPK0Z5MTD4P.json](https://github.com/user-attachments/files/17221329/config_entry-smart_irrigation-01J8349TQPRXWD8WPK0Z5MTD4P.json)

### How to reproduce

Version v2024.7.3 and higher

### Which version are you running?

v2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
500 errors mean you are working with an older version of the frontend after you upgrade... Do this after you upgrade https://refreshyourcache.com/en/cache/
