### ISSUE TITLE
Riemann sum calculated solar radiation is correct but maybe an error in the ET calculation as watering duration too high

### ISSUE THREAD

**Issue by jata1** [jeroenterheerdt/HAsmartirrigation#501]
### What happened?

I have worked with you to investigate and improve solar radiation sensor input using riemann sum. During the winter I had a feeling that the calculated watering duration was too high. Now it is spring and it is much worse (as sun is stronger more hours of light etc).

So I think there might be something wrong with either my setup or with the ET calculation in the integration.

### How to reproduce

Integration setup and working fine
Using the standard daily calculation at 11pm.
Daily watering for a 6m2 area with 14 L/min flow rate is currently calculating bucket mm of around 35-40mm / day
It is increasing every day as the days get longer and sun stonger

### Relevant log output

```shell
will provide once we work out what we need to investigate
```

### Which version are you running?

2024.8.2

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-01J3NXJFTGQR2QDP3BMYX2SF83 (1).json](https://github.com/user-attachments/files/17253273/config_entry-smart_irrigation-01J3NXJFTGQR2QDP3BMYX2SF83.1.json)

![image](https://github.com/user-attachments/assets/6741b426-981c-43ff-a9db-4d6ca3589359)

**Comment by lynxchat4** [comment]
Maybe you have the same problem as me. Look at your diagnostic data. Compare with my calculation problem.
https://github.com/jeroenterheerdt/HAsmartirrigation/issues/499

**Comment by jeroenterheerdt** [comment]
Or... Everyone works fine but it is the riemann sun that you are using (which I don't recommend at all unless using continuous updates but only based on the input you have). So basically, this means to me riemann sum is not the solution and we're back to square one.
