### ISSUE TITLE
Duration to max even if it is raining

### ISSUE THREAD

**Issue by mattiamondini** [jeroenterheerdt/HAsmartirrigation#504]
### Did you read the docs?

- [X] I read the docs and my question is not answered there.

### What happened?

i'm new to smart irrigation and it is running since 3 days, but is raining here, but this generate a duration of 3600s (max) everyday.

as you can see in the screenshot below  my duretion is set to max, i expected it to 0 since it's raining.
also i noticed that bucket value is negative, is this something expected?

[config_entry-smart_irrigation-01JA53K2202G1VZWP530E1K2XB.json](https://github.com/user-attachments/files/17430811/config_entry-smart_irrigation-01JA53K2202G1VZWP530E1K2XB.json)

### How to reproduce

i have set up a simple zone with open weather integration as follow:
![image](https://github.com/user-attachments/assets/2aff23b4-72d1-4eda-8959-68a21bd201c8)

for modules i selected PyETO and set up 2 days of forecast.

### Which version are you running?

2024.10.1

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by jeroenterheerdt** [comment]
Your drainage rate is way to high. Did you somehow calculate that or did you indeed NOT really read the docs?

**Comment by mattiamondini** [comment]
this si what docs says:

> set the drainage rate of a zone. Use this only if you have drainage problems. You will need to do some experimentation to see what value works for you. Too low of a value are your drainage problem is not solved, too high of a value and the effects of the evapotranspiration calculation has little to no impact. Keep in mind that the values quoted on the internet (around 50.8 mm or 2 inch per hour) for drainage rates are dependent on your soil type and are for fully saturated soil only.

since i have some drainage issue as a starting point i used the value from the doc 50.8mm/h.

anyway i will set it to empty for now and see how it works

**Comment by jeroenterheerdt** [comment]
so 50.8 mm/h is for fully saturated soil only. I don't think your soil is fully saturated at all. Set it to empty and slowly increase it by 5 mm/h until you arrive at a comfortable level.
