### ISSUE TITLE
Unit for solar radiation does not set at w/m2 on the UI

### ISSUE THREAD

**Issue by pedromrg** [jeroenterheerdt/HAsmartirrigation#508]
### Did you read the docs?

- [X] I read the docs and my question is not answered there.

### What happened?

Setting the unit of solar radiation to w/m2 does not apply on UI keeps reverting back to mj/day

Extracted a system log and noticed that only the unit for windspeed is showing on the backend config.... 

### How to reproduce

Setting the unit of solar radiation to w/m2 does not apply on UI keeps reverting back to mj/day

### Relevant log output

```shell
"mappings": [
        {
          "id": 0,
          "name": "Ecowit",
          "mappings": {
            "Dewpoint": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_dewpoint",
              "unit": ""
            },
            "Evapotranspiration": {
              "source": "none",
              "sensorentity": "",
              "unit": ""
            },
            "Humidity": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_humidity",
              "unit": ""
            },
            "Precipitation": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_drain_piezo",
              "unit": ""
            },
            "Current Precipitation": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_rrain_piezo",
              "unit": ""
            },
            "Pressure": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_baromabs",
              "unit": ""
            },
            "Solar Radiation": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_solarradiation",
              "unit": ""
            },
            "Temperature": {
              "source": "sensor",
              "sensorentity": "sensor.gw2000_temp",
              "unit": ""
            },
            "Windspeed": {
              "source": "sensor",
              "sensorentity": "sensor.wind_at_2m",
              "unit": "km/h"
            }
```

### Which version are you running?

2024.10.3

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

[config_entry-smart_irrigation-01JCR7KE9NC4YWD310NT4A2Z0Q (1).json](https://github.com/user-attachments/files/17779025/config_entry-smart_irrigation-01JCR7KE9NC4YWD310NT4A2Z0Q.1.json)

**Comment by jeroenterheerdt** [comment]
the fact that only the unit is shown in the config implies you didn't change any of the defaults for any of the others. Is that correct?

**Comment by pedromrg** [comment]
> the fact that only the unit is shown in the config implies you didn't change any of the defaults for any of the others. Is that correct?

Yes, others are all default units.

**Comment by pedromrg** [comment]
Update,

I think I had some issue, mainly for changing configs a few times as a test.
Deleted everything and uninstalled the integration, rebooted.
Removed the smart_irrigation file from .storage folder
Reinstalled and reconfigured everything, with different names on the zones and sensor group.

Now working as expected, using Continuous updates for sensors (experimental) 

Thanks.
