### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by vaughnlfisher** [jeroenterheerdt/HAsmartirrigation#52]
Where would i get a Evapotranspiration sensor to use in this project?

**Comment by jeroenterheerdt** [comment]
not sure what you mean - an actual sensor? You could use a soil moisture sensor but you have to convert the output value to mm / inch lost. As the instructions say you can estimate the EV value using sources like this: https://github.com/jeroenterheerdt/HAsmartirrigation#getting-monthly-et-values
