### ISSUE TITLE
Sequential calls to smart_irrigation_calculate_daily_adjusted_run_time accumulates bucket incorrectly

### ISSUE THREAD

**Issue by juacas** [jeroenterheerdt/HAsmartirrigation#53]
**Describe the bug**
With auto-refresh disabled,: Each time the service "smart_irrigation_calculate_daily_adjusted_run_time" is called (without resetting the bucket between calls) the evaporation and, hence, the bucket and runtime is accumulated again..

**To Reproduce**
1. Disable Auto-refresh mode.
2. Call "smart_irrigation_calculate_daily_adjusted_run_time" and write down the water bucket and runtime.
3. Wait some minutes to allow the evaporation algorithm to get new estimates.
4. Call again "smart_irrigation_calculate_daily_adjusted_run_time". Now the water bucket is almost doubled. It seems that it sums again the last calculation.

**Expected behavior**
It would be desirable that the "Daily adjusted run time" sensors reflect the values calculated from the last "reset" to the current time. The service "smart_irrigation_calculate_daily_adjusted_run_time" should be callable at any time during the day (just before irrigation) and give the right values.

**Screenshots**
Daily_adjusted_run_time increments after each call to "smart_irrigation_calculate_daily_adjusted_run_time". Please note that In this screenshot the "run_time" is saturated to the maximum_duration of 900s configured.

![Screenshot - 05_04_2021 , 14_38_49](https://user-images.githubusercontent.com/1656180/113574557-a10a7580-961c-11eb-88f9-e0b171b36475.png)

**Installed version**
v0.0.65

**Additional context**
This use case appears when different watering cycles are controlled by the same instance of the component.

**Comment by jeroenterheerdt** [comment]
thanks, what do you mean with "This use case appears when different watering cycles are controlled by the same instance of the component."? you need multiple instances if you want to control multiple watering cycles.

**Comment by juacas** [comment]
In my setup I'm looking to configure each cycle runtime by a percentage of the estimated runtime. Hence, I'm trying to reset the bucket once per day but to calculate the runtime more times. from your comment, I realize that the component works that way by-design. Hence, I'll need to find a workaround in my automation logic.

However, it would be better, if it is feasible, that "smart_irrigation_calculate_daily_adjusted_run_time" calculates the runtime consistently from the last reset.

Thank you for your comment, and congratulations on this splendid component.

**Comment by jeroenterheerdt** [comment]
as long as you have one instance per cycle / group not sure what you mean with "runtime not being consistent".

**Comment by juacas** [comment]
Look at this use case:

1. call `smart_irrigation_calculate_daily_adjusted_run_time` and get a a calculation. Let's say 100 seconds for an evapotranspiration of 10mm.
2. some time later the evapotranspiration has increased to 11mm (+10%). The expected runtime would be 110 or so.
3. call again 'smart_irrigation_calculate_daily_adjusted_run_time` and you'll get around 210 seconds which seems to come from an aggregation of the previous runtime plus the newly calculated runtime  for a period that overlaps the previous.

It seems that the service `smart_irrigation_calculate_daily_adjusted_run_time` expects the bucket to be reset betweens calls to the service.

**Comment by jeroenterheerdt** [comment]
correct - you need to reset your bucket in between calls.
