### ISSUE TITLE
[REQ] Blueprint and water pump control

### ISSUE THREAD

**Issue by LPK60** [jeroenterheerdt/HAsmartirrigation#54]
### Blueprint and water pump control
Can you implement a blueprint to easily configure the automation for several taps/zones? It would be interesting also to turn-on a switch for the water pump prior to start each irrigation cycle an turn-off at the end with a few seconds delay before/after to gran the correct water pressure. Thanks

**Comment by LPK60** [comment]
thanks @jeroenterheerdt for your comment. I will make some try with `lead_time`. My poor yaml makes this a challenge using one of your documentation's example, due to the indentation

**Comment by jeroenterheerdt** [comment]
closing this issue because of staleness, please re-open an issue if this is still a problem in 2.0 version (now in beta)
