### ISSUE TITLE
[REQ] Twice a day watering

### ISSUE THREAD

**Issue by freekeys** [jeroenterheerdt/HAsmartirrigation#56]
This looks awesome - kudos 🙌. Is there a way to have it operate a twice daily watering schedule?

**Comment by jeroenterheerdt** [comment]
Thanks! I would say you could add the component twice and set the refresh time to middle of the day to get this to work. Not sure why you want this but it's possible. You would need to take into account that the other cycle that refreshes at 11PM by default would cover the whole day, so you would have to store the rum time for the first cycle and subtract that from the run time of the second cycle in your automation that runs the second cycle.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jeroenterheerdt** [comment]
closing this issue because of staleness, please re-open an issue if this is still relevant to you in 2.0 version (now in beta)
