### ISSUE TITLE
Reconfigure component?

### ISSUE THREAD

**Issue by derandiunddasbo** [jeroenterheerdt/HAsmartirrigation#58]
This is rather a question, than an issue, but is it possible to reconfigure / change the values from the initial configuration or do I need to delete and re-add the component to change these settings?

**Comment by jeroenterheerdt** [comment]
yes you can by editing config/.storage/ files by you do so at your own risk.

**Comment by derandiunddasbo** [comment]
But where are these settings stored? I only found them in core.restore_state, tried to change them there (while HA was stopped) but after restarting HA, the Base Schedule Index sensor is still showing the old values.

**Comment by jeroenterheerdt** [comment]
it's in `core.config_entries`

**Comment by derandiunddasbo** [comment]
Thank you, I must have missed that somehow. I'll close this issue, as there's already a [similar ER](https://github.com/jeroenterheerdt/HAsmartirrigation/issues/27) for making these attributes configurable via the UI.
