### ISSUE TITLE
requests.get(self.url)

### ISSUE THREAD

**Issue by tojo99** [jeroenterheerdt/HAsmartirrigation#6]
Hi, I have problem with that:

Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 18:18:04 (2 occurrences)
Last logged: 18:23:09

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smart_irrigation doing I/O at custom_components/smart_irrigation/OWMClient.py, line 24: r = requests.get(self.url)

**Comment by jeroenterheerdt** [comment]
thanks, I am aware of it.

**Comment by jeroenterheerdt** [comment]
note to self - in order to fix this avoid using sync methods in async functions, run the offending requests like: `requests_sync.get in an asyncio Executor with [asyncio.run_in_executor()`
