### ISSUE TITLE
[Bug] wind speed conversion problem

### ISSUE THREAD

**Issue by riccmike** [jeroenterheerdt/HAsmartirrigation#60]
The measured wind speed increases as the height of the meter increases. So a measurement taken at 10 meters converted to 2 meters must be smaller than the starting one, the formula you proposed increases the value for example with a wind measurement at 10 meters brought to 2 meters the conversion factor is greater than 1 (1.72).
In my opinion, a more suitable conversion, where you also need to insert a new parameter for your integration (the roughness of the sourround terrain) can be found at the following link  [https://www.homerenergy.com/products/pro/docs/latest/wind_resource_variation_with_height. html]

**Comment by jeroenterheerdt** [comment]
Hi @riccmike - thanks for the feedback - I did not propose the formula - the formula comes from the library I use to calculate evapotranspiration: https://pyeto.readthedocs.io/en/latest/api.html#pyeto.fao56_penman_monteith.

**Comment by riccmike** [comment]
Ln no log!
http://www.fao.org/3/X0490E/x0490e07.htm#wind%20speed


Il Mar 25 Mag 2021, 18:47 Jeroen ter Heerdt ***@***.***> ha
scritto:

**Comment by jeroenterheerdt** [comment]
this is the code from the pyeto library:
```
def wind_speed_2m(ws, z):
    """
    Convert wind speed measured at different heights above the soil
    surface to wind speed at 2 m above the surface, assuming a short grass
    surface.

    Based on FAO equation 47 in Allen et al (1998).

    :param ws: Measured wind speed [m s-1]
    :param z: Height of wind measurement above ground surface [m]
    :return: Wind speed at 2 m above the surface [m s-1]
    :rtype: float
    """
    return ws * (4.87 / math.log((67.8 * z) - 5.42))
    ```

So are you saying that is incorrect?

**Comment by jeroenterheerdt** [comment]
So:

```
import math
ws = 1
z = 10
ws_2m = ws * (4.87 / math.log((67.8 * z) - 5.42))
print(ws_2m)
```

returns `0.74795....` as expected.

**Comment by jeroenterheerdt** [comment]
so the documentation image was off, but the actual code in the component as well as the template sensor I provided on the wiki (https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Converting-Wind-speed-to-wind-speed-at-2m-height) provide the correct result

**Comment by riccmike** [comment]
Sorry, Sorry Sorry and Sorry. I have do cut and paste in Excel formula...... in Excel log in log in 10 base.  🤦‍♂️ and I have not been programming for at least 5 years. Quietly close the issue.
