### ISSUE TITLE
Discussion on Sensor Hardware

### ISSUE THREAD

**Issue by RalphM77** [jeroenterheerdt/HAsmartirrigation#72]
Dear all

Is there any recommendation on what set of sensors could/should be used and not spending hundreds of dollars?
As presented in the Docs it would be great to have two sensors for precipitation and evapotranspiration. But what Hardware would that be?
Up to now, I have used the publicly available data from Tempest Weather Stations. Unfortunately, this seems not to work anymore with the API of Weatherflow. 

Best regards

Ralph

**Comment by Dave-Bryant** [comment]
Ralph,
I went with this [weatherstation](https://www.instrumentchoice.com.au/7-inch-colour-wireless-weather-station-ic-xc0370). It is a reasonable price and has been very reliable. Connected it via Weather Underground but that proved to be unreliable so I now use EcoWitt.  SmartIrrigation calculates the Ev from the weather stations sensors.

**Comment by jeroenterheerdt** [comment]
AFAIK there is no sensors for Ev. I made my own weatherstation using a bunch of cheap sensors and an Arduino Uno. De code is not perfect, but I am happy to share it if interested. Cost me $100 or so and heaps of time, but that's part of the fun.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by NathanSweet** [comment]
I'd also like to know what hardware can give me ETo data, ideally without using cloud services.

I'd be fine cobbling together a solution on my own if it were just 1, maybe 2 sensors, but for a high quality solution it seems many sensors are needed so I'm interested in a ready-to-go solution that does the magic and just gives me the evapotranspiration numbers.

**Comment by jeroenterheerdt** [comment]
let's move this to the discussions: https://github.com/jeroenterheerdt/HAsmartirrigation/discussions
