### ISSUE TITLE
v0.0.73-2 wont show up in the integrations list during installation process 

### ISSUE THREAD

**Issue by gribouk** [jeroenterheerdt/HAsmartirrigation#73]
**Describe the bug**
I am trying to install v0.0.73-2 for some time, but the process is halted at an early stages with some strange behaviour - after installation with HACS when I go to config -> integrations -> add integration menu no integration with the name "Smart Irrigation" is detected in the list. The folders in the custom components folder are present though, so it did install physically...
Cannot understand what could be potentially missing from my side since every step (infact there was the only one so far) is according to the manual. Rebooted HA several times already - not being added to the list for some reasons...
HA is 2021.8.5 supervised

**To Reproduce**

**Expected behavior**
Integration to appear in the list of available integrations so I could finish a setup.

**Screenshots**
Add screenshots of the entities and their attributes. 

![smart_irrigation_missing](https://user-images.githubusercontent.com/72703085/128908579-c43c275a-5788-40b9-8e72-183c41a1fe67.jpg)

**Installed version**
Which version of the component are you running? 

**Additional context**

**Comment by jeroenterheerdt** [comment]
hmmm... the only time I have seen this is when your browser has cached something. Can you try resetting your brower's cache or use an in-private window?

**Comment by gribouk** [comment]
Yep. Clearing the cache does solve the issue. Thanks for the tip!

But it did not get me much further - definetely not my day, it is not the integration itself now, but I am stuck acessing http://wcatlas.iwmi.org/ for callibrating data. For an hour or so I keep getting the error from their web page:

Error 522 Ray ID: 67cb3e1c7fbecb9c • 2021-08-10 18:21:43 UTC
Connection timed out

Is it often like that or they have some limits for access from my country (tor did not help me either)? (Just asking incase you've seen anything like that before, maybe I get kucky again)

**Comment by jeroenterheerdt** [comment]
wcatlas has been flaky at best these days. I am not sure what is going on, but I can tell you I cannot access it either right now. Please try to find another source for your location that provides the ET values
