### ISSUE TITLE
[REQ] ET calculation inputs as HART attributes

### ISSUE THREAD

**Issue by karwosts** [jeroenterheerdt/HAsmartirrigation#75]
**Is your feature request related to a problem? Please describe.**
Sometimes late in the day (e.g. 10 or 11PM) I'll see a non-trivial change in the hourly calculated evapotranspiration rate. This is a bit surprising because this has to be attributed to some change in the inputs to the FAO formula. By my understanding at the end of the day the inputs should be relatively stable, (e.g. the daily high temperature shouldn't be changing after the day is already finished). 

Sometimes I wonder what change I'm picking up that causes the ET change. I like to watch out for anomalies like this to make sure I'm not getting weird/unexpected data as inputs. 

**Describe the solution you'd like**
I think it would be potentially useful if the non-static inputs to the fao56 formula could be added as attributes to the hourly runtime sensor, alongside the calculated ET. Then I could plot these values alongside the calculated ET and understand what changes in sensor data are driving particular changes in ET value. 

If you think this is too much information for most users, I understand, and I can just hack up my local copy of the project to have it. I'm not sure if anyone else would be interested in that data.

**Comment by jeroenterheerdt** [comment]
@karwosts today we expose a huge number of things already as attributes, what specifically are you missing? Happy to add them.

**Comment by karwosts** [comment]
I was referring to the dynamic inputs to fao56 calculation:

 temp min/max, dewpoint, humidity, wind, pressure (I think that's all of them)

**Comment by jeroenterheerdt** [comment]
so, I take it you are using OWM? Because if you were using sensors you already have these ;)

**Comment by karwosts** [comment]
Yep, OWM.

**Comment by karwosts** [comment]
Actually it might make more sense for me to create my own sensor from OWM and then supply that to the irrigation, rather than using your builtin call. 

One of the reasons I didn't fully give my system over to this was I have a 21 zone system, and I didn't want 21 instances doing 21 OWM API hits per hour, since I think that would nearly exhaust my free API tier.

**Comment by jeroenterheerdt** [comment]
So why not call OWM yourself and pass in those sensors to the 21 (!) instances of this component... Man, I really need to work on multi-zone support...

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
