### ISSUE TITLE
[Bug] Rain attribute in HART doesn't seem to work

### ISSUE THREAD

**Issue by karwosts** [jeroenterheerdt/HAsmartirrigation#76]
**Describe the bug**
All day long OWM has been giving me an expected value of 0.1 inch for rain. I see this being correctly used in the log. However, the rain attribute in the hourly runtime entity always says 0.0.

This is my current attributes in my HART entity:

```
rain: 0.0
snow: 0.0
precipitation: 0.0
evapotranspiration: 0.13
netto_precipitation: -0.12
water_budget: 67.53
adjusted_run_time_minutes: 0.08
unit_of_measurement: s
friendly_name: Hourly Adjusted Run Time
icon: mdi:sprinkler
```

I tried digging through the code but I couldn't figure out where in the code this is supposed to get set from, so I couldn't add any debug statements.

**Comment by karwosts** [comment]
nevermind, I need to look at this a little closer before I understand what's happening. might be a metric conversion issue.

**Comment by jeroenterheerdt** [comment]
please let me know if this turns out to be a bug! internally the component uses the metric system. I myself run it in imperial as well and have not seen issues, but that's no guarantee at all :)

**Comment by karwosts** [comment]
I think it was probably rounding 0.1mm down to 0.0 inches. I got the units mixed up and confused myself. I haven't got much rain lately so just got surprised when it was raining outside and it said 0.
