### ISSUE TITLE
[Bug] http://wcatlas.iwmi.org/ is down forever

### ISSUE THREAD

**Issue by SirUli** [jeroenterheerdt/HAsmartirrigation#77]
**Describe the bug**
The instructions point to http://wcatlas.iwmi.org/ to retrieve the Evapotranspiration data. However the website was down for the last few weeks. An inquiry to the provider gave the following reply:

> Dear Uli,
> I am afraid that system has been taken offline indefinitely as it was on a very old platform and no further development is to be done on it.
> Regards,
> [REDACTED]

Do you have any other possibility to retrieve that data outside the US?

**To Reproduce**
Try browsing to http://wcatlas.iwmi.org/

**Expected behavior**
Possibility to retrieve Evapotranspiration data

**Screenshots**
None

**Installed version**
None

**Additional context**
None

**Comment by jeroenterheerdt** [comment]
yeah, I know. I don't own the atlas. Your best option right now is to try to find something with your local weather service. I also send an email to the owner of the atlas to hear if it's coming back.

**Comment by SirUli** [comment]
I had a couple forth and back interactions and so far they don't seem to be able to provide the data again. I'll keep on investigating - I'd love to use your module 😀

**Comment by SirUli** [comment]
Hi @jeroenterheerdt,

for Germany, the data can be found here in 1/10mm: https://opendata.dwd.de/climate_environment/CDC/derived_germany/soil/multi_annual/mean_91-10/derived_germany_soil_multi_annual_mean_91-10_VGLS.txt (real evapotranspiration over grass and loamy sand). Before entering into your plugin, the data has to be divided by 10 to have the mm values of course.

Cheers,
Uli

**Comment by jeroenterheerdt** [comment]
Hi @SirUli I'll add it to the readme, thanks!

**Comment by jeroenterheerdt** [comment]
added a Wiki page here: https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Country-specific-Evapotranspiration-info and linked to it from my readme

**Comment by SirUli** [comment]
Lovely. Thanks so much and thanks for your hard work on the module!
