### ISSUE TITLE
[Bug] OWM API: self.rain is sticky if API response does not contain the "rain" key

### ISSUE THREAD

**Issue by karwosts** [jeroenterheerdt/HAsmartirrigation#78]
**Describe the bug**

It appears that on days where there is no rain, the OWM API calls do not contain the "rain" key under daily forecast. 

This has the effect in get_precipitation function where the self.rain value will just keep the previous value. I believe the correct behavior should be to set self.rain to 0 if the rain key does not exist in an API call. 

```
  def get_precipitation(self, data):
        """Parse out precipitation info from OWM data."""
        if data is not None:
            if "rain" in data:
                self.rain = float(data["rain"])
            if "snow" in data:
                self.snow = float(data["snow"])
            _LOGGER.info(
                "rain: {}, snow: {}".format(  # pylint: disable=logging-format-interpolation
                    self.rain, self.snow
                )
            )
            if isinstance(self.rain, str):
                self.rain = 0
            if isinstance(self.snow, str):
                self.snow = 0
            retval = self.rain + self.snow
            if isinstance(retval, str):
                if retval.count(".") > 1:
                    retval = retval.split(".")[0] + "." + retval.split(".")[1]
            retval = float(retval)
            return retval
        return 0.0
```

**Comment by jeroenterheerdt** [comment]
interesting - apparently the OWM API always returns the `rain` key for my location, even if it's 0. Can you send an example return from OWM API where I can see that what exactly is missing? You can create it using postman or something similar.

**Comment by karwosts** [comment]
Try this with your API Key:

https://api.openweathermap.org/data/2.5/onecall?units=metric&lat=45&lon=-122&appid=XXXXXX

![image](https://user-images.githubusercontent.com/32912880/131543990-775d7482-7d9e-4355-b585-8ab9dabb7f0d.png)

**Comment by jeroenterheerdt** [comment]
darn it. you're right. I need to fix this! Thanks.

**Comment by jeroenterheerdt** [comment]
please check https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v0.0.74 and let me know if this helps.

**Comment by karwosts** [comment]
Sure. No rain in the immediate forecast though, maybe a touch next weekend. I'll let you know once I get through a full rain cycle.

**Comment by jeroenterheerdt** [comment]
any news?

**Comment by karwosts** [comment]
I think it's good. Had a blip where the rain went >0, then back to 0 a few hours later, so it seems like it's not getting stuck.
