### ISSUE TITLE
[REQ] Inclusion of Australian Evapotranspiration data source

### ISSUE THREAD

**Issue by natosys** [jeroenterheerdt/HAsmartirrigation#79]
**Is your feature request related to a problem? Please describe.**
Issue #77 identified that IWMI was down for ever, the fix for this has been to begin to identify other sources of evapotranspiration data (usually at the country level). I have a potential souce for Australian data

**Describe the solution you'd like**
Consider inclusion of the Australian Bureau of Meteorology average and monthly evapotranspiration data grid (http://www.bom.gov.au/jsp/ncc/climate_averages/evapotranspiration/index.jsp?maptype=1&period=an#maps) in the country specific evapotranspiration info wiki (https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Country-specific-Evapotranspiration-info).

**Describe alternatives you've considered**
I have not yet found alternative data sources for evapotranspiration data for Australia

**Additional context**
Potential options from this tool include 'Areal Actual', 'Areal Potential', and 'Point Potential' and I haven't read up enough to know what the best would be to recommend for use here. Based on the small synopsis on the page it seems like 'Areal Actual' would be the most appropriate, but someone smarter than myself might have a better idea here.

It's also worth noting that this generates month data-sets that are space delimited where each cell represents 0.1 degree 'cells' starting from a known corner (specified at the top of the file). I highlight this because it is a bit confusing to navigate, when I've worked with these files before I've ended up using a script to find the right data based on a user input lat/lng which I can probably dig up if its useful to anyone.

@jeroenterheerdt thanks for your great wok on this great tool

**Comment by jeroenterheerdt** [comment]
thanks for providing this link! I added it to the wiki!

**Comment by qurm** [comment]
Hi @natosys - thanks for finding this.  Could you share a script or any formatted data?  I downloaded one file and it seems like a lot of work to get 12 monthly readings!!  Is the BoM trying to make this hard!!  Or if you are able to get data for coords -34.95, 138.6 ?  
Thanks for any help.

**Comment by natosys** [comment]
Hi @qurm I've put the code I used for processing it (in PHP) [here as a gist](https://gist.github.com/natosys/e015699c36763fd4a735778d29a0e121) for you, it's not at all an efficient way to do it but it works for now. I've also created a small page [here](https://brindledog.farm/evapotranspiration) that you can put your latitude and longitude into and it should return results for you. Hopefully that's helpful (and hopefully I've gotten it right!), let me know if you have any dramas.

**Comment by qurm** [comment]
That's great - many thanks for that.  I used the web page and that was perfect.  That is just what the BoM need to provide for most users!

**Comment by timh767** [comment]
> Hi @qurm I've put the code I used for processing it (in PHP) [here as a gist](https://gist.github.com/natosys/e015699c36763fd4a735778d29a0e121) for you, it's not at all an efficient way to do it but it works for now. I've also created a small page [here](https://brindledog.farm/evapotranspiration) that you can put your latitude and longitude into and it should return results for you. Hopefully that's helpful (and hopefully I've gotten it right!), let me know if you have any dramas.

Hi @natosys.  Thanks for doing the work on this, providing the web page to access that data is fantastic.

However I don't think it's referencing the correct evapotranspiration data.  For example, for my town of Mildura VIC:

I can access csv fies of daily historical ET data here http://www.bom.gov.au/watl/eto/tables/vic/mildura_airport/mildura_airport.shtml

As an example monthly ET for January 2022 is 258mm.  I am a commercial irrigator so I know how much water my crop requires in January, and this figure appears about right.

Putting my coordinates into your web site returns 33mm for January which seems far too low - that would mean only one irrigation for the entire month!

When looking at the BOM average ET maps it appears point potential ET is the closest to the real ET figures, not areal actual ET.

**Comment by natosys** [comment]
Hi @timh767. Thanks very much! I've updated the page with an option to allow you to select areal actual or point potential

<img width="693" alt="image" src="https://user-images.githubusercontent.com/7324784/189510093-f2623e9c-0f58-4649-995f-a1eecc3cf031.png">

Hopefully that is more useful. I didn't realise there was such a big difference.
