### ISSUE TITLE
[REQ] How to change Evapotranspiration values

### ISSUE THREAD

**Issue by qurm** [jeroenterheerdt/HAsmartirrigation#81]
I setup the integration and entered some approximate ET values.  Now I have my real local data, but cannot see how to get back to the "one-time" configuration!

I looked at several config files etc, but cannot see it.  I'd like something in the docs or Wiki on how to change existing values, and then reset the calculations.

Looks like a great component and I am looking forward to using it over the upcoming Australian summer - plenty of Evapotranspiration!

**Comment by ScratMan** [comment]
You need to remove the integration and add it again.

**Comment by jeroenterheerdt** [comment]
that, or if you feel adventurous (copy /paste from readme): Note If you want to go back and change your settings afterwards, you can either delete the instance and re-create it or edit the entity registry under config/.storage at your own risk.

**Comment by maxxer** [comment]
For the record, the values are in `.storage/core.config_entries`. It's a JSON file, so it should be rather easy **not** to mess it up :)
