### ISSUE TITLE
Installation through HA integrations not working

### ISSUE THREAD

**Issue by leprechaun17** [jeroenterheerdt/HAsmartirrigation#82]
When trying to install through HA integrations, I cannot get passed step 6 of 7 since I cannot input a value for evapotranspiration for the month of December.
<img width="227" alt="Screenshot 2021-10-27 160756" src="https://user-images.githubusercontent.com/45549980/139142603-437a8717-3ddb-4f88-b72a-7f8e38eb1f53.png">

**Comment by jeroenterheerdt** [comment]
@leprechaun17 do you need more help? If not, please close this item.

**Comment by leprechaun17** [comment]
With the update to HA core-2021.12.1, the issues went away.
