### ISSUE TITLE
Service call error "does not match format <domain>.<name> for dictionary value @ data['sequence'][0][Bug] 

### ISSUE THREAD

**Issue by cfrudolphy** [jeroenterheerdt/HAsmartirrigation#83]
**Describe the bug**
When I try to run this service I get the following error message:

`2021-10-28 17:47:13 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547058583488] Error handling message: Service smart_irrigation.si-zone1_reset_bucket does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'smart_irrigation.si-zone1_reset_bucket'
`
**To Reproduce**
1. Go to 'Developer Tools'
2. Click on 'Services'
3. Enter in Service "Smart Irrigation: si-zone1_reset_bucket"
4. Click on 'Call Service'
5. Message flashes on screen - but error message is listed in logs under "Supervisor" --> "System" --> "Log Provider "Core""

**Expected behavior**
Expected service to be called without error
**Screenshots**
**Installed version**
Latest issue installed via HACS

**Additional context**

**Comment by jeroenterheerdt** [comment]
@cfrudolphy sorry for the late response. I did not notice that the services were not deleted, have you rebooted afterwards?

the pyeto documentation (https://pyeto.readthedocs.io/en/latest/_modules/pyeto/fao.html) says regarding `coastal`: 
```
:param coastal: ``True`` if site is a coastal location, situated on or
        adjacent to coast of a large land mass and where air masses are
        influenced by a nearby water body, ``False`` if interior location
        where land mass dominates and air masses are not strongly influenced
        by a large water body.
```

so not sure about this, hope this helps!

**Comment by jeroenterheerdt** [comment]
@cfrudolphy please let me know if you need any more help. If not, please close this item.

**Comment by rickroetenberg** [comment]
is there a fix already without recreating all the zones again? Via an call-service button it's working, only not in an automation

**Comment by jeroenterheerdt** [comment]
closing this issue because of staleness, please re-open an issue if this is still a problem in 2.0 version (now in beta)
