### ISSUE TITLE
[REQ] Alternate or Backup Sensors

### ISSUE THREAD

**Issue by natosys** [jeroenterheerdt/HAsmartirrigation#84]
**Is your feature request related to a problem? Please describe.**
I have a weathervane that is sometimes temperamental and drops some sensors occasionally. It would be great if the smart irrigation component could treat this.

**Describe the solution you'd like**
The smart irrigation component could scan through a list of sensors for an available source stopping at the first one that is not in an unknown or unavailable state.

**Describe alternatives you've considered**
In the interim I have stopped using my weathervane and am using another custom component that draws weather information from the local bureau of meteorology, but this is less accurate and not dynamic.

**Additional context**
None that I've identified at the moment.

**Comment by jeroenterheerdt** [comment]
thanks - interesting idea. not sure I am unable to make that happen soon though.

**Comment by Bart39** [comment]
You could achieve the same result using a template sensor

see https://community.home-assistant.io/t/template-sensor-calculations-when-values-dont-exist/191393 for some examples.

Then use the template sensor as your source

**Comment by jeroenterheerdt** [comment]
please use workaround posted above
