### ISSUE TITLE
[REQ] Add New Zealand info to wiki

### ISSUE THREAD

**Issue by DataBitz** [jeroenterheerdt/HAsmartirrigation#89]
Hi,
Couldn't figure out how to update the wiki, but please add this to https://github.com/jeroenterheerdt/HAsmartirrigation.wiki.git

### New Zealand
Data can be found at the National Institute of Water and Atmospheric Research (NIWA), National Climate Database. https://cliflo.niwa.co.nz/
Register for an account first https://cliflo.niwa.co.nz/pls/niwp/wh.do_help?id=sub_join
Use the Database Query form https://cliflo.niwa.co.nz/pls/niwp/wgenf.genform1
Select "Statistics Calculated from Observations", "Monthly Statistics", "Evaporation and PET". Then "Penman" potential evapo-transpiration. Then Add.
Next choose a station which is closest to your location has lots of sensors (Rain, Wind, Sun, Temp), then start/end dates.
Download the data.
This provides the total for the month and I believe Smart Irrigation requires the daily average for the month. So next divide the monthly values by the number of days in each month.

**Comment by jeroenterheerdt** [comment]
done, thanks!
