### ISSUE TITLE
ET info for Latvia

### ISSUE THREAD

**Issue by rfvermut** [jeroenterheerdt/HAsmartirrigation#91]
I think [this URL](https://www.geo.lu.lv/fileadmin/user_upload/LU.LV/Apaksvietnes/Fakultates/www.gzzf.lu.lv/Folia_Geographica/FG_raksti_2004/2004Geografiskie_raksti_XII_2.pdf) contains Latvian ET per month. Need to delete by 30 to day daily I assume.

![image](https://user-images.githubusercontent.com/13441442/166435483-67f69363-4e4d-41ca-a9fd-e0325740fdcd.png)

**Comment by jeroenterheerdt** [comment]
thanks, added to the Wiki!
