### ISSUE TITLE
[Bug] installation problems

### ISSUE THREAD

**Issue by ametodi** [jeroenterheerdt/HAsmartirrigation#93]
after installing this integration using HACS, nothing really happens.
I can't find any config page, nor do i see any sensors
I've uninstalled and reinstalled, without success.

The image below shows all i can see
![image](https://user-images.githubusercontent.com/41694393/169312504-ee551967-4811-4061-aa75-74d5434bbf29.png)

**Comment by jeroenterheerdt** [comment]
Have you rebooted HA?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ametodi ***@***.***>
Sent: Thursday, May 19, 2022 7:05:19 AM
To: jeroenterheerdt/HAsmartirrigation ***@***.***>
Cc: Jeroen ter Heerdt ***@***.***>; Assign ***@***.***>
Subject: [jeroenterheerdt/HAsmartirrigation] [Bug] installation problems (Issue #93)


after installing this integration using HACS, nothing really happens.
I can't find any config page, nor do i see any sensors
I've uninstalled and reinstalled, without success.

The image below shows all i can see
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F41694393%2F169312504-ee551967-4811-4061-aa75-74d5434bbf29.png&data=05%7C01%7C%7C846e04c23e014567d96008da39a09bdb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637885659210452607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AmFWoM8RxjCIZvbVou4eTRypKD12Z38K00H3W95Qfv0%3D&reserved=0>

**Comment by ametodi** [comment]
Hi Jeroen, yes i have several times

Op do 19 mei 2022 16:45 schreef Jeroen ter Heerdt ***@***.***

**Comment by ametodi** [comment]
Thanks, this helped (sorry i missed it).
Now i was asked to enter the ETA's per month, the amount of sprinklers and throughput. 
I did this for one zone (not sure if i should have done it for all zones??)
but i don't see any other configuration options, like adding zones and nozzles, etc...

the result of my actions now i that i have these three entities
![image](https://user-images.githubusercontent.com/41694393/169485579-24b2c2d8-b637-45a8-8432-bb0d446955e1.png)

**Comment by ametodi** [comment]
Thank you so much for you help, i've now managed to set-up the zones and created a test automation.
The documentation tells that it's possible to have this running in multiple modes, of which a mixed mode.
I have entered the open weather API key, but i also have a POPP rain meter, which i'd like to add. Any idea how i can do this?
I didn't find n option to choose these modes

**Comment by ametodi** [comment]
I've found that there's a checkbox when you try to add the instance.
When you uncheck it asks you for the sensors.
It does not say anything about modes, but i assume that it affects it?
I've entered my sensors, but how do i know in which mode it runs?
![image](https://user-images.githubusercontent.com/41694393/169827258-923b8ceb-045d-425e-ab39-9b76f8bdd6c3.png)

**Comment by jeroenterheerdt** [comment]
It's simple really: if you uncheck this checkbox you need to specify a sensor for ET, so you bypass the entire calculation in the component. That's one mode.
If you use any sensors but leave this checkbox checked you are in the other mode (sensor mode)
If you specified a OWM API key you are in the OWM mode.

Verzonden vanuit Outlook<http://aka.ms/weboutlook>

**Comment by ametodi** [comment]
Hi Jeroen,

The system only asks for sensors when i uncheck the checkbox.
I'm trying to get a mixed mode, but i can't figure out how.

**Comment by ametodi** [comment]
you mentioned in your manual that there were 5 modes. I'm trying to get it into the mixed mode
quoting you: "Mixed. A combination of 1) and 2). In this mode part of the data is supplied by sensors and part by Open Weather Map". 
How can i do this?

**Comment by jeroenterheerdt** [comment]
Provide the API key and then also provide some sensors. What sensors you don't provide will be loaded from OWM.


Verzonden vanuit Outlook<http://aka.ms/weboutlook>

**Comment by ametodi** [comment]
Hello Jeroen, thank you for your help.
I think i've managed to set everything in YAML.
I've set a daily schedule to irrigate all zones and empty the daily buckets.
What i found strange is that the daily adjusted runtimes are even being filled when it rained or when rain was predicted.
Is there something particular i need to pay attention to?

**Comment by ametodi** [comment]
ps. here's an example of one of the zones:

`` "entry_id": "ae4944cf9644d656b6c0d32ec8662f95",
                "version": 1,
                "domain": "smart_irrigation",
                "title": "Gazon Oost",
                "data": {
                    "number_of_sprinklers": 5.0,
                    "flow": 6.6,
                    "area": 100.0,
                    "api_key": "90010a2ebd7fb441169021eeb01290f8",
                    "reference_evapotranspiration": [
                        4.1,
                        7.6,
                        19.6,
                        37.6,
                        53.0,
                        63.7,
                        63.6,
                        49.6,
                        30.7,
                        16.1,
                        6.0,
                        2.9
                    ],
                    "name": "Smart Irrigation Gazon Oost",
                    "sources": {
                        "use_owm_precipitation": false,
                        "use_owm_temperature": false,
                        "use_owm_min_temperature": false,
                        "use_owm_max_temperature": false,
                        "use_owm_dewpoint": true,
                        "use_owm_pressure": true,
                        "use_owm_humidity": true,
                        "use_owm_windspeed": true,
                        "calculate_solar_radiation": true,
                        "calculate_ET_value": true
                    },
                    "sensors": {
                        "sensor_et": "sensor.pir_achtertuin_air_temperature_3",
                        "sensor_precipitation": "sensor.popp_rain_sensor_general_purpose"
                    }
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": "Smart Irrigation Gazon Oost",
                "disabled_by": null
            }``

**Comment by jeroenterheerdt** [comment]
please don't share your API key :), even if rain is expected, things like wind, temperature, sun intensity could push the component to still want to irrigate. Imagine that all these things remove 10 units of moisture and rain adds 5, then we are still missing 5 so we need to irrigate.

**Comment by ametodi** [comment]
We had some heavy rain a few weeks ago. The next morning the irrigation anyway ran for quite a while and that same day it was again going to rain all day

**Comment by jeroenterheerdt** [comment]
if you want to, you can monitor the attributes of the component over the day. I notice you are using OWM so that is not very accurate. My guess is that it rained but that OWM did not indicate as such and therefore the component ran. Only way to tell is to monitor the attributes like rain, windspeed, temp, etc from OWM and do the math yourself.

**Comment by jeroenterheerdt** [comment]
No trying to be snarky, but why don't you read the Readme before asking these questions? Everything is detailed there.


Verzonden vanuit Outlook<http://aka.ms/weboutlook>
