### ISSUE TITLE
[Question] Non-daily irrigation

### ISSUE THREAD

**Issue by hawkeye217** [jeroenterheerdt/HAsmartirrigation#97]
My grass type (St. Augustine) does better with deep watering every few days in summer heat rather than smaller amounts daily.

I currently have some basic automations and a python script looking at rainfall since my last irrigation (usually 3 days) and predicted rainfall for the next 2 days to determine if I should irrigate or not. I don't do any calculations to determine the irrigation duration, so that's what led me to your component.

What's the best way to approach this if I wanted to utilize your component to better fine-tune my water usage? Apologies if you've answered this anywhere else - just point me there if so. 

Thanks again for your great work on this!

**Comment by jeroenterheerdt** [comment]
thanks for reaching out! I'd recommend just running this side by side with your current solution to see if you can learn something about how long to irrigate. You can just run this component and have it calculate daily run times without actually performing the irrigation.

**Comment by hawkeye217** [comment]
Thanks!

That's what I've been doing for a couple of weeks now, actually.  In order to learn more about how long I should be irrigating, should I be resetting the bucket every day, even if I don't irrigate, or should I reset it only when I irrigate? 

With the calculation made at 23:00 every day, I just want to make sure I'm getting the right values out of your component.

**Comment by jeroenterheerdt** [comment]
basically you reset after you irrigate.

**Comment by hawkeye217** [comment]
Got it. Thanks again!
