### ISSUE TITLE
evapotranspiration fao56 data derrived from sensor's data issue 

### ISSUE THREAD

**Issue by gribouk** [jeroenterheerdt/HAsmartirrigation#98]
**Describe the bug**
As we know from the component description (which is a nice work by itself by the way) the irrigation time is derived as difference between net precipitations and net evaporation during past hours from the fix time period plus boundary conditions at the beginning of that period. The net evapotranspiration, naturally, should start with 0 value at starting point and be generally increasing (positive derivative) though slightly decreasing sometimes (during time periods when outside temp is below dew point), but yet remain close to average data over the years for a specified month for a given latitude and longitude when taken for 24 hour periods - this implies we should see generally non decreasing graph for that value, with periods of growth during daytime and stagnating or slightly decreasing during night time.

I have build a sensor from evapotranspiration value provided by evapotranspiration attribute of smart_irrigation_hourly_adjusted_run_time sensor and gathered some statistics for it's daily behavior. Unfortunately I did not observe expected behavior in any of the days. It starts at some lowest non 0 value, keeps growing till sunset and then keeps gradualy decreasing to same lowest value, which physically is very unreasonable - this implies that the condensation is same as evaporation, but the temperature always remains above dew point meanwhile... The picture is attached:

![1655841372643](https://user-images.githubusercontent.com/72703085/174890665-a7e2db84-023e-4e51-8624-6f8b3bfcbd90.JPEG)

All the data for the fao56 calculations provided by the ecowitt sensors. 

**To Reproduce**

**Expected behavior**
evapotranspiration value starts to build from 0 value at the beginning of fixed interval and builds close to average over the years for considered month in 24 hours periods with some periods of slightly decreasing behaviour due to condensation. Then it drops to 0 value at fix point time.

**Screenshots**
Add screenshots of the entities and their attributes. 

**Installed version**
Which version of the component are you running? 

**Additional context**

**Comment by martin3000** [comment]
You are right. The pyeto package with the FAO Penman-Monteith equation returns mm per day. This means that the solar radiation must be the total MJ per m² and day (you cannot use a sensor value), the wind speed must be the average speed of the day. This means that calculating the ET every minute is not useful. The value is meant to be a value for the day.
