### ISSUE TITLE
[REQ] Wiki: rain sensor should deliver daily totals, but OWM does not

### ISSUE THREAD

**Issue by martin3000** [jeroenterheerdt/HAsmartirrigation#99]
The page https://github.com/jeroenterheerdt/HAsmartirrigation/wiki/Measurements-and-Units says the the rain sensor has to deliver daily accumulated totals of rain, i.e. mm per day.
OWM (https://openweathermap.org/api/one-call-api) has for the current weather only the rain value for 1h, not the daily accumulated value. 
So which value is internally required? When using the OWM data, is it internally accumlated?

Edit: I just checked the code and found that the daily rain forecast ist used from OWM. It contains the estimated total l/m² for that day.

If the sensor delivers the daily accumulated rain in l/m², then I assume it has to be reset together with the bucket-reset? I.e. after irrigating?

**Comment by jeroenterheerdt** [comment]
assuming you do a bucket-reset once a day then there is no need to reset the daily sensor.

**Comment by martin3000** [comment]
Thanks! I changed the bucket reset time to 12:00 and thought the rain sensor must be in sync.
